/*
 * Copyright (c) 2021 Cyrille Rossant and contributors. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for details.
 * SPDX-License-Identifier: MIT
 */

/* textured_planet - UV textured planet mesh via dvz_mesh + sampled fields.
 *
 * Scenario: textured_terrain_or_planet
 * Style: showcase, graphite_cyan, 1280x720 window target
 *
 * Opens a GLFW window showing an indexed sphere generated by `dvz_geometry_sphere()`, uploaded as a
 * mesh visual, and shaded with an RGBA8 texture bound to the mesh "texture" slot. The example uses
 * real Earth and Mars textures from the data submodule when available. Earth keeps a generated
 * fallback; Mars requires the real texture and is unavailable when that file is missing.
 *
 * Build:  just example-c showcases/textured_planet
 * Run:    ./build/examples/c/showcases/textured_planet --live
 * Smoke:  ./build/examples/c/showcases/textured_planet --png
 * DVZR:   ./build/examples/c/showcases/textured_planet --dvzr 60
 * Video:  ./build/examples/c/showcases/textured_planet --offscreen-record 60
 */



/*************************************************************************************************/
/*  Includes                                                                                     */
/*************************************************************************************************/

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

#include "_alloc.h"
#include "datoviz/fileio.h"
#include "datoviz/geom.h"
#ifndef DVZ_EXAMPLE_NO_MAIN
#include "datoviz/gui.h"
#endif
#include "datoviz/scene.h"
#include "example_common.h"
#include "runner/scenario_runner.h"



/*************************************************************************************************/
/*  Constants                                                                                    */
/*************************************************************************************************/

#define WIDTH  EXAMPLE_WINDOW_WIDTH
#define HEIGHT EXAMPLE_WINDOW_HEIGHT

#define TEXTURE_WIDTH  1024
#define TEXTURE_HEIGHT 512
#define EARTH_TEXTURE_PATH          "data/assets/textures/world.200412.3x5400x2700.jpg"
#define EARTH_TEXTURE_FALLBACK_PATH "data/assets/textures/earth.jpg"
#define MARS_TEXTURE_PATH           "data/assets/textures/mars_viking_mdim21.jpg"

#define SPHERE_RADIUS 0.92
#define SPHERE_SECTORS 96
#define SPHERE_RINGS 48

#define ROTATION_SPEED_RAD_PER_SEC 0.16f

#define STAR_COUNT 900
#define STAR_RADIUS 48.0f

#define SUN_DIR_X -0.80f
#define SUN_DIR_Y +0.22f
#define SUN_DIR_Z +0.55f



/*************************************************************************************************/
/*  Structs                                                                                      */
/*************************************************************************************************/

typedef enum PlanetKind
{
    PLANET_EARTH,
    PLANET_MARS,
    PLANET_COUNT,
} PlanetKind;



typedef struct PlanetTexture
{
    DvzSampledField* field;
    uint8_t* pixels;
    uint32_t width;
    uint32_t height;
    bool loaded_from_file;
} PlanetTexture;



typedef struct PlanetPreset
{
    const char* label;
    const char* texture_path;
    const char* fallback_path;
    bool require_texture_file;
    float spin_speed;
} PlanetPreset;



typedef struct TexturedPlanetState
{
    DvzVisual* visual;
    DvzTrack* spin_rotation;
    DvzAnimation* spin_animation;
    PlanetTexture textures[PLANET_COUNT];
    int planet_index;
    bool auto_rotate;
    float spin_speed;
} TexturedPlanetState;



/*************************************************************************************************/
/*  Forward declarations                                                                         */
/*************************************************************************************************/

DvzScenarioSpec dvz_showcase_textured_planet_scenario(void);



static const PlanetPreset PLANETS[PLANET_COUNT] = {
    [PLANET_EARTH] =
        {
            .label = "Earth",
            .texture_path = EARTH_TEXTURE_PATH,
            .fallback_path = EARTH_TEXTURE_FALLBACK_PATH,
            .spin_speed = ROTATION_SPEED_RAD_PER_SEC,
        },
    [PLANET_MARS] =
        {
            .label = "Mars",
            .texture_path = MARS_TEXTURE_PATH,
            .fallback_path = NULL,
            .require_texture_file = true,
            .spin_speed = 0.12f,
        },
};



/*************************************************************************************************/
/*  Helpers                                                                                      */
/*************************************************************************************************/

/**
 * Clamp a scalar to the unit interval.
 *
 * @param value input value
 * @return clamped value
 */
static double _clamp01(double value)
{
    if (value < 0.0)
        return 0.0;
    if (value > 1.0)
        return 1.0;
    return value;
}



/**
 * Convert a normalized scalar to an 8-bit color component.
 *
 * @param value normalized input value
 * @return 8-bit component
 */
static uint8_t _u8(double value)
{
    const double clamped = _clamp01(value);
    return (uint8_t)(255.0 * clamped + 0.5);
}



/**
 * Return whether a texture file exists.
 *
 * @param path file path
 * @return whether the file can be opened for reading
 */
static bool _file_exists(const char* path)
{
    ANN(path);

    FILE* fp = fopen(path, "rb");
    if (fp == NULL)
        return false;
    fclose(fp);
    return true;
}



/**
 * Return whether an image has equirectangular planet-map dimensions.
 *
 * @param width image width
 * @param height image height
 * @return whether the dimensions are exactly 2:1
 */
static bool _is_equirectangular_texture(uint32_t width, uint32_t height)
{
    return height > 0 && width == 2 * height;
}



/**
 * Remap the generic Z-up UV sphere into the Y-up planet convention.
 *
 * The shared geometry helper uses +Z as the polar axis. This showcase presents planets with +Y
 * as north. The rotation also places the geometry helper's duplicated UV seam on the back side of
 * the default view, so the original equirectangular `u/v` coordinates remain continuous.
 *
 * @param geometry sphere geometry
 */
static void _prepare_planet_geometry(DvzGeometry* geometry)
{
    ANN(geometry);

    for (uint32_t i = 0; i < geometry->vertex_count; i++)
    {
        const double x = geometry->positions[i][0];
        const double y = geometry->positions[i][1];
        const double z = geometry->positions[i][2];
        const double nx = geometry->normals[i][0];
        const double ny = geometry->normals[i][1];
        const double nz = geometry->normals[i][2];

        geometry->positions[i][0] = -y;
        geometry->positions[i][1] = z;
        geometry->positions[i][2] = -x;
        geometry->normals[i][0] = -ny;
        geometry->normals[i][1] = nz;
        geometry->normals[i][2] = -nx;
    }
}



/**
 * Fill one procedural Earth-like equirectangular RGBA texture.
 *
 * @param pixels output RGBA8 texture buffer
 * @param width texture width
 * @param height texture height
 */
static void _make_earth_texture(uint8_t* pixels, uint32_t width, uint32_t height)
{
    ANN(pixels);
    ASSERT(width > 1);
    ASSERT(height > 1);

    for (uint32_t y = 0; y < height; y++)
    {
        const double v = (double)y / (double)(height - 1);
        const double lat = (0.5 - v) * DVZ_PI;
        for (uint32_t x = 0; x < width; x++)
        {
            const double u = (double)x / (double)(width - 1);
            const double lon = (u - 0.5) * 2.0 * DVZ_PI;
            const double bands = sin(12.0 * lon + 1.7 * sin(5.0 * lat)) +
                                 0.72 * sin(9.0 * lat + 2.2 * cos(3.0 * lon)) +
                                 0.38 * sin(21.0 * (lon + lat));
            const double ridge = sin(34.0 * lon) * sin(16.0 * lat);
            const bool land = bands + 0.28 * ridge > 0.38;
            const bool ice = fabs(lat) > 1.22;
            const double grid_u = fabs(u * 24.0 - floor(u * 24.0 + 0.5));
            const double grid_v = fabs(v * 12.0 - floor(v * 12.0 + 0.5));
            const bool grid = grid_u < 0.015 || grid_v < 0.015;

            double r = 0.05;
            double g = 0.13;
            double b = 0.27;
            if (land)
            {
                const double warm = _clamp01(0.5 + 0.5 * sin(5.0 * lon - 7.0 * lat));
                r = 0.20 + 0.38 * warm;
                g = 0.34 + 0.32 * (1.0 - fabs(lat) / (0.5 * DVZ_PI));
                b = 0.16 + 0.12 * (1.0 - warm);
            }
            else
            {
                const double water = 0.5 + 0.5 * sin(8.0 * lon + 5.0 * lat);
                r = 0.03 + 0.05 * water;
                g = 0.20 + 0.18 * water;
                b = 0.44 + 0.22 * water;
            }
            if (ice)
            {
                r = 0.84;
                g = 0.90;
                b = 0.93;
            }
            if (grid)
            {
                r = 0.92;
                g = 0.94;
                b = 0.86;
            }

            const uint32_t offset = 4 * (y * width + x);
            pixels[offset + 0] = _u8(r);
            pixels[offset + 1] = _u8(g);
            pixels[offset + 2] = _u8(b);
            pixels[offset + 3] = 255;
        }
    }
}



/**
 * Try loading a JPEG texture as RGBA8 pixels.
 *
 * @param primary_path preferred file path
 * @param fallback_path fallback file path
 * @param width decoded texture width
 * @param height decoded texture height
 * @return RGBA8 pixel buffer, or NULL when the texture is unavailable or decoding fails
 */
static uint8_t*
_load_texture(const char* primary_path, const char* fallback_path, uint32_t* width, uint32_t* height)
{
    ANN(primary_path);
    ANN(width);
    ANN(height);

    *width = 0;
    *height = 0;
    if (_file_exists(primary_path))
        return dvz_read_jpeg(primary_path, width, height);
    if (fallback_path != NULL && _file_exists(fallback_path))
        return dvz_read_jpeg(fallback_path, width, height);

    return NULL;
}



/**
 * Create and populate one scene-owned planet texture field.
 *
 * @param scene scene
 * @param kind planet kind
 * @param texture texture state to populate
 * @return whether the field was created successfully
 */
static bool _create_planet_texture(
    DvzScene* scene, PlanetKind kind, PlanetTexture* texture)
{
    ANN(scene);
    ANN(texture);
    ASSERT(kind < PLANET_COUNT);
    const PlanetPreset* preset = &PLANETS[kind];

    texture->pixels =
        _load_texture(preset->texture_path, preset->fallback_path, &texture->width, &texture->height);
    texture->loaded_from_file = texture->pixels != NULL;
    if (texture->pixels != NULL && !_is_equirectangular_texture(texture->width, texture->height))
    {
        fprintf(
            stderr,
            "textured_planet: ignoring %s texture with non-equirectangular dimensions %ux%u\n",
            preset->label, texture->width, texture->height);
        dvz_free(texture->pixels);
        texture->pixels = NULL;
        texture->width = 0;
        texture->height = 0;
        texture->loaded_from_file = false;
    }
    if (texture->pixels == NULL)
    {
        if (preset->require_texture_file)
        {
            fprintf(
                stderr, "textured_planet: %s texture unavailable: missing %s\n", preset->label,
                preset->texture_path);
            return true;
        }

        texture->width = TEXTURE_WIDTH;
        texture->height = TEXTURE_HEIGHT;
        texture->pixels =
            (uint8_t*)dvz_calloc((DvzSize)texture->width * texture->height * 4, sizeof(uint8_t));
        if (texture->pixels == NULL)
            return false;
        _make_earth_texture(texture->pixels, texture->width, texture->height);
    }

    texture->field = dvz_sampled_field(
        scene, &(DvzSampledFieldDesc){DVZ_STRUCT_INIT_FIELDS(DvzSampledFieldDesc),
                   .dim = DVZ_FIELD_DIM_2D,
                   .format = DVZ_FIELD_FORMAT_RGBA8_UNORM,
                   .semantic = DVZ_FIELD_SEMANTIC_COLOR,
                   .width = texture->width,
                   .height = texture->height,
                   .depth = 1,
               });
    if (texture->field == NULL)
        return false;

    return dvz_sampled_field_set_data(
        texture->field, &(DvzFieldDataView){DVZ_STRUCT_INIT_FIELDS(DvzFieldDataView),
                            .data = texture->pixels,
                            .bytes_per_row = texture->width * 4,
                            .rows_per_image = texture->height,
                        });
}



/**
 * Deterministic 32-bit pseudo-random number.
 *
 * @param state generator state
 * @return next pseudo-random value
 */
static uint32_t _rand_u32(uint32_t* state)
{
    ANN(state);
    *state = 1664525u * (*state) + 1013904223u;
    return *state;
}



/**
 * Deterministic pseudo-random float in [0, 1].
 *
 * @param state generator state
 * @return random scalar
 */
static float _rand_f32(uint32_t* state)
{
    return (float)(_rand_u32(state) & 0x00FFFFFFu) / (float)0x01000000u;
}



/**
 * Create a sparse world-space star shell.
 *
 * @param scene scene
 * @return point visual, or NULL on failure
 */
static DvzVisual* _create_star_shell(DvzScene* scene)
{
    ANN(scene);
    vec3* positions = (vec3*)dvz_calloc(STAR_COUNT, sizeof(vec3));
    DvzColor* colors = (DvzColor*)dvz_calloc(STAR_COUNT, sizeof(DvzColor));
    float* sizes = (float*)dvz_calloc(STAR_COUNT, sizeof(float));
    if (positions == NULL || colors == NULL || sizes == NULL)
        goto fail;

    uint32_t rng = 0xD42024u;
    for (uint32_t i = 0; i < STAR_COUNT; i++)
    {
        if (i == 0)
        {
            positions[i][0] = STAR_RADIUS * SUN_DIR_X;
            positions[i][1] = STAR_RADIUS * SUN_DIR_Y;
            positions[i][2] = STAR_RADIUS * SUN_DIR_Z;
            colors[i] = (DvzColor){255, 244, 214, 255};
            sizes[i] = 14.0f;
            continue;
        }

        const float z = 2.0f * _rand_f32(&rng) - 1.0f;
        const float phi = 2.0f * (float)DVZ_PI * _rand_f32(&rng);
        const float r = sqrtf(fmaxf(0.0f, 1.0f - z * z));
        positions[i][0] = STAR_RADIUS * r * cosf(phi);
        positions[i][1] = STAR_RADIUS * r * sinf(phi);
        positions[i][2] = STAR_RADIUS * z;
        const float brightness = 0.45f + 0.55f * _rand_f32(&rng);
        colors[i].r = _u8(0.82 * brightness);
        colors[i].g = _u8(0.88 * brightness);
        colors[i].b = _u8(1.00 * brightness);
        colors[i].a = 255;
        sizes[i] = 1.0f + 2.2f * _rand_f32(&rng) * _rand_f32(&rng);
    }

    DvzVisual* stars = dvz_point(scene, 0);
    if (stars == NULL)
        goto fail;

    DvzVisualDataUpdate updates[] = {
        {.attr_name = "position", .data = positions, .item_count = STAR_COUNT},
        {.attr_name = "color", .data = colors, .item_count = STAR_COUNT},
        {.attr_name = "size", .data = sizes, .item_count = STAR_COUNT},
    };
    if (dvz_visual_set_data_many(stars, updates, 3) != 0)
        goto fail;

    dvz_free(positions);
    dvz_free(colors);
    dvz_free(sizes);
    return stars;

fail:
    dvz_free(positions);
    dvz_free(colors);
    dvz_free(sizes);
    return NULL;
}



/**
 * Reset GUI-controlled animation parameters from the selected preset.
 *
 * @param state example state
 */
static void _state_reset_controls(TexturedPlanetState* state)
{
    ANN(state);
    ASSERT(state->planet_index >= 0);
    ASSERT(state->planet_index < PLANET_COUNT);
    const PlanetPreset* preset = &PLANETS[state->planet_index];

    state->auto_rotate = true;
    state->spin_speed = preset->spin_speed;
}



/**
 * Apply GUI-controlled animation speed to the spin animation.
 *
 * @param state example state
 */
static void _state_apply_spin(TexturedPlanetState* state)
{
    ANN(state);
    if (state->spin_animation == NULL)
        return;

    const float speed = state->auto_rotate ? state->spin_speed : 0.0f;
    dvz_anim_set_speed(state->spin_animation, speed);
}



/**
 * Bind the selected planet texture to the mesh.
 *
 * @param state example state
 * @param report_error whether to print an error when the selected texture is unavailable
 * @return whether the selected planet texture was bound
 */
static bool _state_apply_planet(TexturedPlanetState* state, bool report_error)
{
    ANN(state);
    if (state->visual == NULL)
        return false;
    if (state->planet_index < 0 || state->planet_index >= PLANET_COUNT)
        return false;

    const PlanetPreset* preset = &PLANETS[state->planet_index];
    PlanetTexture* texture = &state->textures[state->planet_index];
    if (texture->field == NULL)
    {
        if (report_error)
            fprintf(
                stderr,
                "textured_planet: %s texture is unavailable; keeping the current planet\n",
                preset->label);
        return false;
    }

    return dvz_visual_set_field(state->visual, "texture", texture->field);
}



#ifndef DVZ_EXAMPLE_NO_MAIN
/**
 * Build live GUI controls for the textured planet example.
 *
 * @param gui GUI overlay
 * @param win view
 * @param user_data example state
 */
static void _textured_planet_gui(DvzGui* gui, DvzView* win, void* user_data)
{
    (void)win;
    TexturedPlanetState* state = (TexturedPlanetState*)user_data;
    if (state == NULL)
        return;

    static const char* const planet_items[PLANET_COUNT] = {"Earth", "Mars"};
    const int previous_planet_index = state->planet_index;
    bool planet_changed = false;
    bool spin_changed = false;
    bool reset = false;

    if (dvz_gui_begin(gui, "Textured Planets", NULL, 0))
    {
        dvz_gui_separator_text(gui, "Planet");
        planet_changed |=
            dvz_gui_combo(gui, "Preset", &state->planet_index, planet_items, PLANET_COUNT);

        dvz_gui_separator_text(gui, "Animation");
        spin_changed |= dvz_gui_checkbox(gui, "Auto rotate", &state->auto_rotate);
        spin_changed |= dvz_gui_slider_float_format(
            gui, "Rotation speed", &state->spin_speed, 0.0f, 0.8f, "%.2f rad/s");

        reset = dvz_gui_button(gui, "Reset");
    }
    dvz_gui_end(gui);

    if (planet_changed)
    {
        if (_state_apply_planet(state, true))
        {
            _state_reset_controls(state);
            spin_changed = true;
        }
        else
        {
            state->planet_index = previous_planet_index;
        }
    }
    if (reset)
    {
        _state_reset_controls(state);
        spin_changed = true;
    }
    if (spin_changed)
        _state_apply_spin(state);
}
#endif



/*************************************************************************************************/
/*  Functions                                                                                    */
/*************************************************************************************************/

static bool _scenario_init(DvzScenarioContext* ctx, void** out_user)
{
    DvzGeometry* sphere = NULL;
    if (ctx == NULL)
        return false;
    if (out_user != NULL)
        *out_user = NULL;

    bool ok = false;
    TexturedPlanetState* state = (TexturedPlanetState*)dvz_calloc(1, sizeof(*state));
    if (state == NULL)
        return false;
    if (out_user != NULL)
        *out_user = state;
    state->planet_index = PLANET_EARTH;
    _state_reset_controls(state);

    ctx->figure = dvz_figure(ctx->scene, ctx->width, ctx->height, 0);
    EXAMPLE_CHECK(ctx->figure != NULL, "dvz_figure() failed");

    DvzPanel* panel = dvz_panel_full(ctx->figure);
    EXAMPLE_CHECK(panel != NULL, "dvz_panel() failed");

    DvzCameraDesc camera_desc = dvz_camera_desc();
    camera_desc.view.eye[0] = 0.0f;
    camera_desc.view.eye[1] = 0.0f;
    camera_desc.view.eye[2] = 3.0f;
    camera_desc.projection.fov_y = 0.72f;
    camera_desc.projection.near_clip = 0.05f;
    camera_desc.projection.far_clip = 100.0f;
    DvzResult camera_rc = dvz_panel_set_camera_desc(panel, &camera_desc);
    DvzCamera* camera = dvz_panel_camera(panel);
    EXAMPLE_CHECK(camera_rc == 0, "dvz_panel_set_camera_desc() failed");
    EXAMPLE_CHECK(camera != NULL, "dvz_panel_set_camera_desc() failed");

    DvzVisual* stars = _create_star_shell(ctx->scene);
    EXAMPLE_CHECK(stars != NULL, "failed to create star shell");
    int rc = dvz_panel_add_visual(panel, stars, NULL);
    EXAMPLE_CHECK(rc == 0, "dvz_panel_add_visual(stars) failed");

    DvzColor white = {255, 255, 255, 255};
    sphere = dvz_geometry_sphere(&(DvzGeometrySphereDesc){
        DVZ_STRUCT_INIT_FIELDS(DvzGeometrySphereDesc),
        .radius = SPHERE_RADIUS,
        .sectors = SPHERE_SECTORS,
        .rings = SPHERE_RINGS,
        .color = white,
    });
    EXAMPLE_CHECK(sphere != NULL, "dvz_geometry_sphere() failed");
    _prepare_planet_geometry(sphere);

    DvzVisual* visual = dvz_mesh(ctx->scene, 0);
    EXAMPLE_CHECK(visual != NULL, "dvz_mesh() failed");
    state->visual = visual;

    ok = dvz_mesh_set_geometry(visual, sphere) == 0;
    EXAMPLE_CHECK(ok, "dvz_mesh_set_geometry() failed");
    dvz_geometry_destroy(sphere);
    sphere = NULL;

    DvzMaterialDesc material = dvz_phong_material_desc();
    material.light_direction[0] = SUN_DIR_X;
    material.light_direction[1] = SUN_DIR_Y;
    material.light_direction[2] = SUN_DIR_Z;
    material.phong.ambient = 0.16f;
    material.phong.diffuse = 0.92f;
    material.phong.specular = 0.015f;
    material.phong.shininess = 18.0f;
    EXAMPLE_CHECK(
        dvz_visual_set_material(visual, &material) == 0, "dvz_visual_set_material() failed");

    for (uint32_t i = 0; i < PLANET_COUNT; i++)
    {
        ok = _create_planet_texture(ctx->scene, (PlanetKind)i, &state->textures[i]);
        EXAMPLE_CHECK(ok, "failed to create planet texture");
    }

    ok = dvz_visual_set_field(visual, "texture", state->textures[state->planet_index].field);
    EXAMPLE_CHECK(ok, "dvz_visual_set_field(texture) failed");

    rc = dvz_panel_add_visual(panel, visual, NULL);
    EXAMPLE_CHECK(rc == 0, "dvz_panel_add_visual() failed");
    dvz_panel_set_background_color(panel, dvz_color_from_unit(0.006f, 0.008f, 0.014f, 1.0f));

    DvzTurntableDesc turntable_desc = dvz_turntable_desc();
    turntable_desc.min_distance = 1.45f;
    turntable_desc.max_distance = 7.50f;
    turntable_desc.zoom_speed = 0.018f;
    DvzController* controller = dvz_turntable(ctx->scene, &turntable_desc);
    EXAMPLE_CHECK(controller != NULL, "dvz_turntable() failed");
    DvzTurntable* turntable = dvz_controller_turntable(controller);
    EXAMPLE_CHECK(turntable != NULL, "failed to create or bind turntable controller");
    EXAMPLE_CHECK(
        dvz_scenario_bind_controller(ctx, panel, controller, DVZ_DIM_MASK_XYZ) == 0,
        "dvz_scenario_bind_controller() failed");

    DvzTrackRotationDesc rotation_desc = dvz_track_rotation_desc();
    rotation_desc.axis[1] = 1.0f;
    rotation_desc.speed_rad_per_sec = 1.0f;
    state->spin_rotation = dvz_track_rotation(&rotation_desc);
    EXAMPLE_CHECK(state->spin_rotation != NULL, "dvz_track_rotation(planet) failed");
    DvzTransformMotionDesc transform_desc = dvz_transform_motion_desc();
    transform_desc.rotation = state->spin_rotation;
    state->spin_animation = dvz_anim_visual_transform(ctx->scene, visual, &transform_desc);
    EXAMPLE_CHECK(state->spin_animation != NULL, "dvz_anim_visual_transform(planet) failed");
    dvz_anim_set_speed(state->spin_animation, state->spin_speed);
    dvz_anim_start(state->spin_animation, 0.0);

    ok = true;
cleanup:
    if (sphere != NULL)
        dvz_geometry_destroy(sphere);
    return ok;
}



#ifndef DVZ_EXAMPLE_NO_MAIN
static bool _scenario_native_view(DvzScenarioContext* ctx, DvzApp* app, DvzView* view, void* user)
{
    (void)ctx;
    (void)app;
    TexturedPlanetState* state = (TexturedPlanetState*)user;
    if (state == NULL || view == NULL)
        return true;

    DvzGui* gui = dvz_view_gui(view, NULL);
    if (gui == NULL)
        return true;
    dvz_view_set_gui_callback(view, _textured_planet_gui, state);
    return true;
}
#endif



static void _scenario_destroy(DvzScenarioContext* ctx, void* user)
{
    (void)ctx;
    TexturedPlanetState* state = (TexturedPlanetState*)user;
    if (state == NULL)
        return;
    dvz_track_destroy(state->spin_rotation);
    for (uint32_t i = 0; i < PLANET_COUNT; i++)
        dvz_free(state->textures[i].pixels);
    dvz_free(state);
}



DvzScenarioSpec dvz_showcase_textured_planet_scenario(void)
{
    return (DvzScenarioSpec){
        .id = "textured_terrain_or_planet",
        .title = "Textured Planets",
        .width = WIDTH,
        .height = HEIGHT,
        .fps = 60.0,
        .init = _scenario_init,
#ifndef DVZ_EXAMPLE_NO_MAIN
        .native_view = _scenario_native_view,
#endif
        .destroy = _scenario_destroy,
    };
}



#ifndef DVZ_EXAMPLE_NO_MAIN
int main(int argc, char** argv)
{
    DvzScenarioSpec spec = dvz_showcase_textured_planet_scenario();
    return dvz_scenario_run_native_cli(&spec, argc, argv) == 0 ? 0 : 1;
}
#endif
