FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    python3 \
    python3-pip \
    python3-venv \
    libx11-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    vulkan-tools \
    mesa-utils \
    nvidia-driver-460 \
    nvidia-utils-460 \
    x11-apps

ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV NVIDIA_VISIBLE_DEVICES=all
