site_name: Datoviz Documentation
site_url: https://datoviz.org
repo_url: https://github.com/datoviz/datoviz
docs_dir: docs
site_description: '⚡ Datoviz: high-performance GPU scientific data visualization C/C++/Python library'
site_author: Cyrille Rossant
theme:
  name: material
  logo: images/logow.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
hooks:
  - tools/mkdocs_hooks.py
nav:
  - Home: 'index.md'
  - User guide:
    - User API: 'userguide.md'
    - Datoviz Rendering Protocol: 'drp.md'
  - Examples:
    - Examples: 'examples.md'
  - Reference:
    - Colormaps reference: 'colormaps.md'
    - API reference: 'api.md'
  - Discussions:
    - Architecture: 'ARCHITECTURE.md'
    - Building instructions: 'BUILD.md'
    - Contributing notes: 'CONTRIBUTING.md'
    - Maintainers instructions: 'MAINTAINERS.md'
    - License: 'LICENSE.md'
