site_name: Datoviz Documentation
site_url: https://datoviz.org
repo_url: https://github.com/datoviz/datoviz
docs_dir: docs
site_description: '⚡ Datoviz: high-performance scientific data visualization'
site_author: Cyrille Rossant
theme:
  name: material
  logo: images/logow.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
hooks:
  - tools/mkdocs_hooks.py
nav:
  - Home: 'index.md'
  - User guide:
    - Overview: 'guide/index.md'
    - Figure, panels, axes: 'guide/common.md'
    - Visuals:
      - Overview: 'guide/visuals.md'
      - Basic: 'visuals/basic.md'
      - Pixel: 'visuals/pixel.md'
      - Point: 'visuals/point.md'
      - Marker: 'visuals/marker.md'
      - Segment: 'visuals/segment.md'
      - Path: 'visuals/path.md'
      - Image: 'visuals/image.md'
      - Text: 'visuals/text.md'
      - Mesh: 'visuals/mesh.md'
      - Volume: 'visuals/volume.md'
      - Slice: 'visuals/slice.md'
    - Interactivity: 'guide/interactivity.md'
    - User events: 'guide/events.md'
    - Graphical user interfaces: 'guide/gui.md'
    - Datoviz Rendering Protocol: 'guide/drp.md'
    - Using Datoviz in C: 'guide/c.md'
  - Gallery:
    - Overview: 'gallery/index.md'
    - Visuals: 'gallery/visuals/index.md'
    - Features: 'gallery/features/index.md'
    - Showcase: 'gallery/showcase/index.md'
  - Reference:
    - Python API reference: 'reference/api_py.md'
    - C API reference: 'reference/api_c.md'
    - Colormaps reference: 'reference/colormaps.md'
  - Discussions:
    - Architecture: 'discussions/ARCHITECTURE.md'
    - Build instructions: 'discussions/BUILD.md'
    - Contribution guidelines: 'discussions/CONTRIBUTING.md'
    - Maintainer guidelines: 'discussions/MAINTAINERS.md'
    - License: 'discussions/LICENSE.md'
