site_name: Datoviz Documentation
site_url: https://datoviz.org
repo_url: https://github.com/datoviz/datoviz
docs_dir: docs
site_description: '⚡ Datoviz: high-performance scientific data visualization'
site_author: Cyrille Rossant
theme:
  name: material
  logo: images/logow.png
  features:
    - content.tabs.link
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
            docstring_style: numpy
            filters: ["!^_"]
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: false
            separate_signature: true
            show_docstring_attributes: false
            show_docstring_modules: false
            show_object_full_path: false
            show_root_heading: true
            show_root_members_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            heading_level: 2
hooks:
  - tools/mkdocs_hooks.py
nav:
  - Home: 'index.md'

  - Learn:
    - Overview: 'guide/index.md'
    - Quickstart: 'quickstart.md'
    - Main Concepts: 'guide/common.md'
    - Visuals:
      - Overview: 'guide/visuals.md'
      - Basic: 'visuals/basic.md'
      - Pixel: 'visuals/pixel.md'
      - Point: 'visuals/point.md'
      - Marker: 'visuals/marker.md'
      - Segment: 'visuals/segment.md'
      - Path: 'visuals/path.md'
      - Image: 'visuals/image.md'
      - Glyph: 'visuals/glyph.md'
      - Mesh: 'visuals/mesh.md'
      - Sphere: 'visuals/sphere.md'
      - Volume: 'visuals/volume.md'
      - Slice: 'visuals/slice.md'
    - Texture: 'guide/texture.md'
    - Interactivity: 'guide/interactivity.md'

  - Advanced:
    - Shapes: 'guide/shape.md'
    - User Input: 'guide/input.md'
    - Timers and Frame Events: 'guide/events.md'
    - Graphical User Interfaces: 'guide/gui.md'
    - Using Datoviz in C: 'guide/c.md'
    - Datoviz Rendering Protocol (DRP): 'guide/drp.md'

  - Gallery:
    - Overview: 'gallery/index.md'

  - Reference:
    - Python API Reference: 'reference/api_py.md'
    - C API Reference: 'reference/api_c.md'
    - Colormaps: 'reference/colormaps.md'

  - Discussions:
    - Architecture: 'discussions/ARCHITECTURE.md'
    - Build Instructions: 'discussions/BUILD.md'
    - Contribution Guidelines: 'discussions/CONTRIBUTING.md'
    - Maintainer Guidelines: 'discussions/MAINTAINERS.md'
    - License: 'discussions/LICENSE.md'
