/*
 * Copyright (c) 2021 Cyrille Rossant and contributors. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for details.
 * SPDX-License-Identifier: MIT
 */

/* textured_mesh - UV textured sphere mesh via dvz_mesh + sampled fields.
 *
 * Opens a GLFW window showing an indexed sphere generated by `dvz_geom_sphere()`, uploaded as a
 * mesh visual, and shaded with an RGBA8 texture bound to the mesh "texture" slot. The example uses
 * the real Earth texture from the data submodule when available, with a generated texture fallback
 * so the example still runs without optional data.
 *
 * Build:  just example-c visuals/textured_mesh
 * Run:    ./build/examples/c/visuals/textured_mesh
 * Smoke:  ./build/examples/c/visuals/textured_mesh 60
 * DVZR:   DVZ_CAPTURE=dvzr ./build/examples/c/visuals/textured_mesh 60
 * Video:  DVZ_CAPTURE=mp4 ./build/examples/c/visuals/textured_mesh 60
 */



/*************************************************************************************************/
/*  Includes                                                                                     */
/*************************************************************************************************/

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

#include "_alloc.h"
#include "datoviz/app.h"
#include "datoviz/fileio.h"
#include "datoviz/geom.h"
#include "datoviz/gui.h"
#include "datoviz/scene.h"
#include "example_common.h"
#include "example_gui_controls.h"



/*************************************************************************************************/
/*  Constants                                                                                    */
/*************************************************************************************************/

#define WIDTH  1600
#define HEIGHT 1200

#define TEXTURE_WIDTH  1024
#define TEXTURE_HEIGHT 512
#define EARTH_TEXTURE_PATH "data/textures/world.200412.3x5400x2700.jpg"

#define SPHERE_RADIUS 0.92
#define SPHERE_SECTORS 96
#define SPHERE_RINGS 48

#define ROTATION_SPEED_RAD_PER_SEC 0.16f



/*************************************************************************************************/
/*  Structs                                                                                      */
/*************************************************************************************************/

typedef struct TexturedMeshState
{
    DvzVisual* visual;
    DvzExampleVisualSpin spin;
    bool auto_rotate;
    bool standard_material;
    float spin_speed;
    float light_direction[3];
    float ambient;
    float diffuse;
    float specular;
    float shininess;
    float roughness;
    float rim_strength;
} TexturedMeshState;



/*************************************************************************************************/
/*  Helpers                                                                                      */
/*************************************************************************************************/

/**
 * Clamp a scalar to the unit interval.
 *
 * @param value input value
 * @return clamped value
 */
static double _clamp01(double value)
{
    if (value < 0.0)
        return 0.0;
    if (value > 1.0)
        return 1.0;
    return value;
}



/**
 * Convert a normalized scalar to an 8-bit color component.
 *
 * @param value normalized input value
 * @return 8-bit component
 */
static uint8_t _u8(double value)
{
    const double clamped = _clamp01(value);
    return (uint8_t)(255.0 * clamped + 0.5);
}



/**
 * Return whether a texture file exists.
 *
 * @param path file path
 * @return whether the file can be opened for reading
 */
static bool _file_exists(const char* path)
{
    ANN(path);

    FILE* fp = fopen(path, "rb");
    if (fp == NULL)
        return false;
    fclose(fp);
    return true;
}



/**
 * Fill one procedural equirectangular RGBA texture.
 *
 * @param pixels output RGBA8 texture buffer
 * @param width texture width
 * @param height texture height
 */
static void _make_texture(uint8_t* pixels, uint32_t width, uint32_t height)
{
    ANN(pixels);
    ASSERT(width > 1);
    ASSERT(height > 1);

    for (uint32_t y = 0; y < height; y++)
    {
        const double v = (double)y / (double)(height - 1);
        const double lat = (0.5 - v) * M_PI;
        for (uint32_t x = 0; x < width; x++)
        {
            const double u = (double)x / (double)(width - 1);
            const double lon = (u - 0.5) * 2.0 * M_PI;
            const double bands = sin(12.0 * lon + 1.7 * sin(5.0 * lat)) +
                                 0.72 * sin(9.0 * lat + 2.2 * cos(3.0 * lon)) +
                                 0.38 * sin(21.0 * (lon + lat));
            const double ridge = sin(34.0 * lon) * sin(16.0 * lat);
            const bool land = bands + 0.28 * ridge > 0.38;
            const bool ice = fabs(lat) > 1.22;
            const double grid_u = fabs(u * 24.0 - floor(u * 24.0 + 0.5));
            const double grid_v = fabs(v * 12.0 - floor(v * 12.0 + 0.5));
            const bool grid = grid_u < 0.015 || grid_v < 0.015;

            double r = 0.05;
            double g = 0.13;
            double b = 0.27;
            if (land)
            {
                const double warm = _clamp01(0.5 + 0.5 * sin(5.0 * lon - 7.0 * lat));
                r = 0.20 + 0.38 * warm;
                g = 0.34 + 0.32 * (1.0 - fabs(lat) / (0.5 * M_PI));
                b = 0.16 + 0.12 * (1.0 - warm);
            }
            else
            {
                const double water = 0.5 + 0.5 * sin(8.0 * lon + 5.0 * lat);
                r = 0.03 + 0.05 * water;
                g = 0.20 + 0.18 * water;
                b = 0.44 + 0.22 * water;
            }
            if (ice)
            {
                r = 0.84;
                g = 0.90;
                b = 0.93;
            }
            if (grid)
            {
                r = 0.92;
                g = 0.94;
                b = 0.86;
            }

            const uint32_t offset = 4 * (y * width + x);
            pixels[offset + 0] = _u8(r);
            pixels[offset + 1] = _u8(g);
            pixels[offset + 2] = _u8(b);
            pixels[offset + 3] = 255;
        }
    }
}



/**
 * Try loading the bundled Earth texture as RGBA8 pixels.
 *
 * @param width decoded texture width
 * @param height decoded texture height
 * @return RGBA8 pixel buffer, or NULL when the texture is unavailable or decoding fails
 */
static uint8_t* _load_earth_texture(uint32_t* width, uint32_t* height)
{
    ANN(width);
    ANN(height);

    *width = 0;
    *height = 0;
    if (!_file_exists(EARTH_TEXTURE_PATH))
        return NULL;

    return dvz_read_jpeg(EARTH_TEXTURE_PATH, width, height);
}



/**
 * Reset GUI-controlled animation and material parameters.
 *
 * @param state example state
 */
static void _state_reset_controls(TexturedMeshState* state)
{
    ANN(state);

    state->auto_rotate = true;
    state->standard_material = false;
    state->spin_speed = ROTATION_SPEED_RAD_PER_SEC;
    state->light_direction[0] = -0.034f;
    state->light_direction[1] = -0.035f;
    state->light_direction[2] = +0.067f;
    state->ambient = 0.734f;
    state->diffuse = 0.637f;
    state->specular = 0.188f;
    state->shininess = 24.602f;
    state->roughness = 0.58f;
    state->rim_strength = 0.08f;
}



/**
 * Apply GUI-controlled material parameters to the textured mesh.
 *
 * @param state example state
 */
static void _state_apply_material(TexturedMeshState* state)
{
    ANN(state);
    if (state->visual == NULL)
        return;

    DvzMaterialDesc material =
        state->standard_material ? dvz_standard_material_desc() : dvz_phong_material_desc();
    material.light_direction[0] = state->light_direction[0];
    material.light_direction[1] = state->light_direction[1];
    material.light_direction[2] = state->light_direction[2];
    if (state->standard_material)
    {
        material.standard.roughness = state->roughness;
        material.standard.specular = state->specular;
        material.standard.rim_strength = state->rim_strength;
    }
    else
    {
        material.phong.ambient = state->ambient;
        material.phong.diffuse = state->diffuse;
        material.phong.specular = state->specular;
        material.phong.shininess = state->shininess;
    }
    (void)dvz_visual_set_material(state->visual, &material);
}



/**
 * Apply GUI-controlled animation speed to the spin animation.
 *
 * @param state example state
 */
static void _state_apply_spin(TexturedMeshState* state)
{
    ANN(state);
    if (state->spin.animation == NULL)
        return;

    const float speed = state->auto_rotate ? state->spin_speed : 0.0f;
    example_visual_spin_set_speed(&state->spin, speed);
}



/**
 * Build live GUI controls for the textured mesh example.
 *
 * @param gui GUI overlay
 * @param win view
 * @param user_data example state
 */
static void _textured_mesh_gui(DvzGui* gui, DvzView* win, void* user_data)
{
    (void)win;
    TexturedMeshState* state = (TexturedMeshState*)user_data;
    if (state == NULL)
        return;

    bool material_changed = false;
    bool spin_changed = false;
    bool reset = false;

    if (dvz_gui_begin(gui, "Textured Mesh", NULL, 0))
    {
        dvz_gui_separator_text(gui, "Animation");
        spin_changed |= dvz_gui_checkbox(gui, "Auto rotate", &state->auto_rotate);
        spin_changed |= dvz_gui_slider_float_format(
            gui, "Rotation speed", &state->spin_speed, 0.0f, 0.8f, "%.2f rad/s");

        dvz_gui_separator_text(gui, "Lighting");
        material_changed |=
            dvz_gui_slider_float3(gui, "Light direction", state->light_direction, -1.0f, 1.0f);
        DvzExampleGuiMaterialControls material = {
            .standard_material = state->standard_material,
            .ambient = state->ambient,
            .diffuse = state->diffuse,
            .specular = state->specular,
            .shininess = state->shininess,
            .roughness = state->roughness,
            .rim_strength = state->rim_strength,
        };
        material_changed |= dvz_example_gui_material(gui, &material);
        state->standard_material = material.standard_material;
        state->ambient = material.ambient;
        state->diffuse = material.diffuse;
        state->specular = material.specular;
        state->shininess = material.shininess;
        state->roughness = material.roughness;
        state->rim_strength = material.rim_strength;

        reset = dvz_gui_button(gui, "Reset");
    }
    dvz_gui_end(gui);

    if (reset)
    {
        _state_reset_controls(state);
        material_changed = true;
        spin_changed = true;
    }
    if (material_changed)
        _state_apply_material(state);
    if (spin_changed)
        _state_apply_spin(state);
}



/*************************************************************************************************/
/*  Functions                                                                                    */
/*************************************************************************************************/

int main(int argc, char** argv)
{
    uint32_t frame_count = example_frame_count_any(argc, argv);
    DvzAppCaptureConfig capture = dvz_app_capture_config_from_env("textured_mesh");
    bool video_enabled = (capture.flags & DVZ_APP_CAPTURE_VIDEO) != 0;

    int ret = 1;
    DvzScene* scene = NULL;
    DvzApp* app = NULL;
    DvzGeometry* sphere = NULL;
    uint8_t* pixels = NULL;
    uint32_t texture_width = 0;
    uint32_t texture_height = 0;
    TexturedMeshState gui_state = {0};
    _state_reset_controls(&gui_state);

    pixels = _load_earth_texture(&texture_width, &texture_height);
    if (pixels == NULL)
    {
        texture_width = TEXTURE_WIDTH;
        texture_height = TEXTURE_HEIGHT;
        pixels = (uint8_t*)dvz_calloc((DvzSize)texture_width * texture_height * 4, sizeof(uint8_t));
        EXAMPLE_CHECK(pixels != NULL, "texture allocation failed");
        _make_texture(pixels, texture_width, texture_height);
    }

    scene = dvz_scene();
    EXAMPLE_CHECK(scene != NULL, "dvz_scene() failed");

    DvzFigure* figure = dvz_figure(scene, WIDTH, HEIGHT, 0);
    EXAMPLE_CHECK(figure != NULL, "dvz_figure() failed");

    DvzPanel* panel = dvz_panel_full(figure);
    EXAMPLE_CHECK(panel != NULL, "dvz_panel() failed");

    DvzCameraDesc camera_desc = dvz_camera_desc();
    camera_desc.eye[0] = 0.0f;
    camera_desc.eye[1] = -3.0f;
    camera_desc.eye[2] = 0.0f;
    camera_desc.up[1] = 0.0f;
    camera_desc.up[2] = 1.0f;
    camera_desc.fov_y = 0.72f;
    camera_desc.near = 0.05f;
    camera_desc.far = 100.0f;
    bool ok = dvz_panel_set_camera(panel, &camera_desc);
    EXAMPLE_CHECK(ok, "dvz_panel_set_camera() failed");

    DvzColor white = {255, 255, 255, 255};
    sphere = dvz_geom_sphere(&(DvzGeometrySphereDesc){
        DVZ_STRUCT_INIT_FIELDS(DvzGeometrySphereDesc),
        .radius = SPHERE_RADIUS,
        .sectors = SPHERE_SECTORS,
        .rings = SPHERE_RINGS,
        .color = white,
    });
    EXAMPLE_CHECK(sphere != NULL, "dvz_geom_sphere() failed");

    DvzVisual* visual = dvz_mesh(scene, 0);
    EXAMPLE_CHECK(visual != NULL, "dvz_mesh() failed");
    gui_state.visual = visual;

    ok = example_mesh_geometry(visual, sphere);
    EXAMPLE_CHECK(ok, "example_mesh_geometry() failed");
    dvz_geometry_destroy(sphere);
    sphere = NULL;

    DvzSampledField* texture = dvz_sampled_field(
        scene, &(DvzSampledFieldDesc){
                   .dim = DVZ_FIELD_DIM_2D,
                   .format = DVZ_FIELD_FORMAT_RGBA8_UNORM,
                   .semantic = DVZ_FIELD_SEMANTIC_COLOR,
                   .width = texture_width,
                   .height = texture_height,
                   .depth = 1,
               });
    EXAMPLE_CHECK(texture != NULL, "dvz_sampled_field() failed");

    ok = dvz_sampled_field_set_data(
        texture, &(DvzFieldDataView){DVZ_STRUCT_INIT_FIELDS(DvzFieldDataView),
                     .data = pixels,
                     .bytes_per_row = texture_width * 4,
                     .rows_per_image = texture_height,
                 });
    EXAMPLE_CHECK(ok, "dvz_sampled_field_set_data() failed");

    ok = dvz_visual_set_field(visual, "texture", texture);
    EXAMPLE_CHECK(ok, "dvz_visual_set_field(texture) failed");
    _state_apply_material(&gui_state);

    int rc = dvz_panel_add_visual(panel, visual, NULL);
    EXAMPLE_CHECK(rc == 0, "dvz_panel_add_visual() failed");
    dvz_panel_set_background_color(panel, 0.025f, 0.028f, 0.034f, 1.0f);

    app = dvz_app(scene);
    EXAMPLE_CHECK(app != NULL, "dvz_app() failed (no GPU or display?)");

    DvzView* win = dvz_view_glfw(app, figure, WIDTH, HEIGHT, "textured mesh");
    EXAMPLE_CHECK(win != NULL, "dvz_view_glfw() failed (GLFW unavailable?)");

    DvzGuiConfig gui_config = dvz_gui_config();
    DvzGui* gui = dvz_view_gui(win, &gui_config);
    EXAMPLE_CHECK(gui != NULL, "dvz_view_gui() failed");
    dvz_view_set_gui_callback(win, _textured_mesh_gui, &gui_state);

    DvzArcball* arcball = dvz_view_arcball(win, panel, NULL);
    EXAMPLE_CHECK(arcball != NULL, "failed to create or bind arcball controller");
    dvz_arcball_set(arcball, (vec3){0.0f, 0.0f, +0.25f});

    dvz_scene_set_clock_mode(scene, video_enabled ? DVZ_CLOCK_OFFLINE : DVZ_CLOCK_REALTIME);
    dvz_scene_set_fps(scene, 60.0);

    rc = dvz_view_capture_start(win, &capture);
    EXAMPLE_CHECK(rc == 0, "dvz_view_capture_start() failed");

    EXAMPLE_CHECK(
        example_visual_spin(
            scene, visual, (vec3){0.0f, 0.0f, 1.0f}, gui_state.spin_speed, NULL,
            &gui_state.spin),
        "example_visual_spin() failed");
    example_visual_spin_start(&gui_state.spin, 0.0);

    dvz_app_run(app, frame_count);
    rc = dvz_view_capture_stop(win);
    EXAMPLE_CHECK(rc == 0, "dvz_view_capture_stop() failed");
    ret = 0;

cleanup:
    if (sphere != NULL)
        dvz_geometry_destroy(sphere);
    if (app != NULL)
        dvz_app_destroy(app);
    example_visual_spin_destroy(&gui_state.spin);
    if (scene != NULL)
        dvz_scene_destroy(scene);
    dvz_free(pixels);
    return ret;
}
