FROM ubuntu:24.04

# Build and run apt dependencies
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    gcc \
    git \
    ccache \
    ninja-build \
    xorg-dev \
    clang-format \
    patchelf \
    curl \
    wget \
    tree \
    libtinyxml2-dev \
    libfreetype-dev \
    python3 \
    python3-pip \
    python3-venv \
    python3-numpy \
    xvfb \
    libx11-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    vulkan-tools \
    mesa-utils \
    nvidia-driver-460 \
    nvidia-utils-460 \
    x11-apps \
    x11-utils

# Python dependencies
RUN pip install --break-system-packages numpy tqdm pillow pytest wheel setuptools twine mkdocs-material

# casey just
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash
ENV PATH="/root/bin:$PATH"

# SwiftShader
RUN git clone --recursive https://github.com/google/swiftshader.git /swiftshader
RUN cd /swiftshader && \
    mkdir -p build && cd build && \
    cmake .. -GNinja -DSWIFTSHADER_VULKAN=ON -DSWIFTSHADER_OPENGL=OFF && \
    ninja
RUN cd /swiftshader && \
    cp build/libvk_swiftshader.so /usr/local/lib/ && \
    mkdir -p /usr/local/share/vulkan/icd.d && \
    echo '{ \
        "file_format_version": "1.0.0", \
        "ICD": { \
            "library_path": "/usr/local/lib/libvk_swiftshader.so", \
            "api_version": "1.3.286" \
        } \
    }' > /usr/local/share/vulkan/icd.d/swiftshader_icd.json

# Environment variables
ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV NVIDIA_VISIBLE_DEVICES=all
ENV VK_ICD_FILENAMES="/usr/local/share/vulkan/icd.d/swiftshader_icd.json"
