# Use Windows Server Core as the base image
FROM chocolatey/choco:latest-windows

# Set environment variables
ENV VCPKG_ROOT="C:/vcpkg"
ENV PATH="C:/mingw64/bin;C:/VulkanSDK/1.3.280.0/Bin;C:/vcpkg/installed/x64-windows/bin;${PATH}"

# Install Git for Windows
RUN choco install git -y --params "/GitAndUnixToolsOnPath"

# Install WinLibs (GCC, Mingw64)
RUN curl -LO https://winlibs.com/gcc-latest-ucrt-posix-64.zip && \
    powershell -Command "Expand-Archive -Path gcc-latest-ucrt-posix-64.zip -DestinationPath C:/mingw64"

# Install Just
RUN curl -LO https://github.com/casey/just/releases/download/1.35.0/just-1.35.0-x86_64-pc-windows-msvc.zip && \
    powershell -Command "Expand-Archive -Path just-1.35.0-x86_64-pc-windows-msvc.zip -DestinationPath C:/mingw64/bin"

# Install Vulkan SDK
RUN curl -LO https://sdk.lunarg.com/sdk/download/1.3.280.0/windows/vulkan-sdk.exe
RUN Start-Process -FilePath vulkan-sdk.exe -ArgumentList "/S" -Wait

# Install Python using Chocolatey
RUN choco install python --version=3.12 -y

# Install vcpkg
RUN git clone https://github.com/microsoft/vcpkg.git C:/vcpkg && \
    powershell -Command "C:/vcpkg/bootstrap-vcpkg.bat"

# Set up environment variables
RUN setx /M VCPKG_ROOT "C:/vcpkg"

# Install Python dependencies
RUN python -m pip install --upgrade pip && \
    python -m pip install -r https://raw.githubusercontent.com/datoviz/datoviz/main/requirements-dev.txt
