"""
Array-aware facade for the Datoviz v0.4 Python binding.

This file is generated by tools/bindings/generate_array_facade.py. Do not edit it by hand.
"""

from __future__ import annotations

import ctypes

import numpy as np

from . import raw as _raw


def _encode_string(value, name):
    if isinstance(value, str):
        return value.encode('utf-8')
    if isinstance(value, bytes) or value is None:
        return value
    raise TypeError(f'{name} must be str, bytes, or None')


def _raw_pointer(value):
    if isinstance(value, (int, ctypes.c_void_p, ctypes.Array, ctypes._Pointer)):
        return True
    if type(value).__name__ == 'CArgObject' and hasattr(value, '_obj'):
        return True
    return hasattr(value, '_as_parameter_')


def _array_arg(value, name, raw_func, pointer_index, dtype=None, shape_tail=None):
    if _raw_pointer(value):
        return value, None
    array = np.asarray(value)
    if dtype is not None:
        expected = np.dtype(dtype)
        if array.dtype != expected:
            raise ValueError(f'{name} must have dtype {expected}, got {array.dtype}')
    if array.ndim == 0:
        raise ValueError(f'{name} must be at least one-dimensional')
    if shape_tail is not None and tuple(array.shape[1:]) != tuple(shape_tail):
        raise ValueError(f'{name} must have shape (n, {", ".join(map(str, shape_tail))})')
    if not array.flags.c_contiguous:
        array = np.ascontiguousarray(array)
    pointer = ctypes.c_void_p(array.ctypes.data)
    target = None
    argtypes = getattr(raw_func, 'argtypes', None)
    if argtypes is not None and pointer_index < len(argtypes):
        target = argtypes[pointer_index]
    if target is not None and target is not ctypes.c_void_p:
        pointer = ctypes.cast(pointer, target)
    return pointer, array


def _typed_sequence(value, dtype):
    if _raw_pointer(value) or isinstance(value, np.ndarray):
        return value
    array = np.asarray(value)
    expected = np.dtype(dtype)
    if expected.kind in 'ui':
        if array.dtype.kind not in 'ui':
            raise ValueError(f'values must contain integers for dtype {expected}')
        if array.size:
            limits = np.iinfo(expected)
            if array.min() < limits.min or array.max() > limits.max:
                raise ValueError(f'values are outside the range of dtype {expected}')
    return np.asarray(value, dtype=expected)


def _shape0_count(array, name):
    if array is None:
        raise TypeError(f'{name} count must be provided when passing a raw pointer')
    return int(array.shape[0])


def _nbytes_size(array, name):
    if array is None:
        raise TypeError(f'{name} byte size must be provided when passing a raw pointer')
    return int(array.nbytes)


def _gui_strings(value, name, count=None, optional=False):
    if value is None and optional:
        return None, ()
    if _raw_pointer(value):
        if count is None:
            raise TypeError(f'{name} count must be provided when passing a raw pointer')
        return value, (value,)
    try:
        items = list(value)
    except TypeError as exc:
        raise TypeError(f'{name} must be a sequence of strings') from exc
    if count is not None and len(items) != int(count):
        raise ValueError(f'{name} length {len(items)} does not match row count {count}')
    encoded = [_encode_string(item, f'{name}[{i}]') for i, item in enumerate(items)]
    array = (ctypes.c_char_p * len(encoded))(*encoded) if encoded else None
    return array, (array, encoded)


def _gui_array(value, name, target, dtype=None, count=None, optional=False, shape_tail=None):
    if value is None and optional:
        return None, ()
    if _raw_pointer(value):
        if count is None:
            raise TypeError(f'{name} count must be provided when passing a raw pointer')
        return value, (value,)
    array = np.asarray(value)
    if dtype is not None and array.dtype != np.dtype(dtype):
        raise ValueError(f'{name} must have dtype {np.dtype(dtype)}, got {array.dtype}')
    if array.ndim == 0:
        raise ValueError(f'{name} must be at least one-dimensional')
    if shape_tail is not None and tuple(array.shape[1:]) != tuple(shape_tail):
        raise ValueError(f'{name} must have shape (n, {", ".join(map(str, shape_tail))})')
    if count is not None and array.shape[0] != int(count):
        raise ValueError(f'{name} length {array.shape[0]} does not match row count {count}')
    if not array.flags.c_contiguous:
        array = np.ascontiguousarray(array)
    pointer = ctypes.c_void_p(array.ctypes.data)
    if target is not ctypes.c_void_p:
        pointer = ctypes.cast(pointer, target)
    return pointer, (array,)


def _gui_records(value, record_type, name, count=None):
    if _raw_pointer(value):
        if count is None:
            raise TypeError(f'{name} count must be provided when passing a raw pointer')
        return value, (value,)
    items = list(value)
    if count is not None and len(items) != int(count):
        raise ValueError(f'{name} length {len(items)} does not match expected count {count}')
    records = (record_type * len(items))()
    for i, item in enumerate(items):
        if not isinstance(item, record_type):
            raise TypeError(f'{name}[{i}] must be {record_type.__name__}')
        records[i] = item
    return records, (records,)


def _gui_draw(raw_func, gui, widget, events, capacity):
    if events is None:
        if capacity is None:
            capacity = 64
        if int(capacity) < 0:
            raise ValueError('capacity must be non-negative')
        events = (_raw.DvzGuiDataEvent * int(capacity))()
    elif isinstance(events, ctypes.Array):
        capacity = len(events)
    elif _raw_pointer(events):
        if capacity is None:
            raise TypeError('capacity must be provided for a raw event pointer')
    else:
        raise TypeError('events must be omitted, a ctypes array, or a raw pointer')
    written = ctypes.c_uint32()
    dropped = ctypes.c_uint32()
    result = raw_func(gui, widget, events, int(capacity), ctypes.byref(written), ctypes.byref(dropped))
    return result, [events[i] for i in range(min(written.value, int(capacity)))], dropped.value


def _visual_data_updates_arg(updates):
    if isinstance(updates, dict):
        items = list(updates.items())
    else:
        try:
            items = list(updates)
        except TypeError as exc:
            raise TypeError('updates must be a mapping or iterable of (attr_name, data) pairs') from exc
    if not items:
        raise ValueError('updates must not be empty')

    records = (_raw.DvzVisualDataUpdate * len(items))()
    keepalive = []
    item_count = None

    for i, item in enumerate(items):
        try:
            attr_name, data = item
        except (TypeError, ValueError) as exc:
            raise TypeError('updates must contain (attr_name, data) pairs') from exc

        attr_name_bytes = _encode_string(attr_name, f'updates[{i}].attr_name')
        data_array = np.asarray(data)
        if data_array.ndim == 0:
            raise ValueError(f'updates[{attr_name!r}] data must be at least one-dimensional')
        if not data_array.flags.c_contiguous:
            data_array = np.ascontiguousarray(data_array)
        count = int(data_array.shape[0])
        if item_count is None:
            item_count = count
        elif count != item_count:
            raise ValueError(
                f'updates[{attr_name!r}] item count {count} does not match expected {item_count}'
            )

        records[i].attr_name = attr_name_bytes
        records[i].data = ctypes.c_void_p(data_array.ctypes.data)
        records[i].item_count = count
        keepalive.extend((attr_name_bytes, data_array))

    return records, keepalive


def _axis_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzAxisTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzAxisTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzAxisTicks
    ):
        return value
    return None


def _axis_ticks_arg(values, labels):
    raw_descriptor = _axis_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzAxisTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzAxisTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzAxisTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def _colorbar_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzColorbarTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzColorbarTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzColorbarTicks
    ):
        return value
    return None


def _colorbar_ticks_arg(values, labels):
    raw_descriptor = _colorbar_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzColorbarTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzColorbarTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzColorbarTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def dvz_view_capture_rgba(view):
    canvas = _raw.dvz_view_canvas(view)
    if not canvas:
        raise RuntimeError('dvz_view_capture_rgba failed: view has no canvas')

    width = ctypes.c_uint32()
    height = ctypes.c_uint32()
    _raw.dvz_view_framebuffer_size(view, ctypes.byref(width), ctypes.byref(height))
    if width.value == 0 or height.value == 0:
        raise RuntimeError('dvz_view_capture_rgba failed: view framebuffer size is zero')

    rgba = np.empty((height.value, width.value, 4), dtype=np.uint8)
    out = rgba.ctypes.data_as(ctypes.POINTER(ctypes.c_uint8))
    rc = _raw.dvz_canvas_capture_rgba_into(
        canvas, width.value, height.value, out, rgba.nbytes
    )
    if rc != 0:
        raise RuntimeError(f'dvz_view_capture_rgba failed with code {rc}')
    return rgba


def _sampled_field_layout(array, field_format, semantic, color_role, dim):
    if array.ndim == 2:
        inferred_dim = _raw.DVZ_FIELD_DIM_2D
        height, width = array.shape
        depth = 1
        channels = 1
        bytes_per_row = array.strides[0]
        rows_per_image = 0
    elif (
        array.ndim == 3
        and array.shape[2] in (1, 2, 4)
        and array.dtype == np.uint8
        and (dim in (None, _raw.DVZ_FIELD_DIM_2D))
    ):
        inferred_dim = _raw.DVZ_FIELD_DIM_2D
        height, width, channels = array.shape
        depth = 1
        bytes_per_row = array.strides[0]
        rows_per_image = 0
    elif array.ndim == 3:
        inferred_dim = _raw.DVZ_FIELD_DIM_3D
        depth, height, width = array.shape
        channels = 1
        bytes_per_row = array.strides[1]
        rows_per_image = height
    else:
        raise ValueError(
            'array must have shape (height, width), (height, width, channels), '
            'or (depth, height, width)'
        )

    if dim is not None and dim != inferred_dim:
        raise ValueError('dim override is incompatible with array shape')
    if width <= 0 or height <= 0 or depth <= 0:
        raise ValueError('array dimensions must be non-empty')

    if field_format is None:
        if channels == 4 and array.dtype == np.uint8:
            field_format = _raw.DVZ_FIELD_FORMAT_RGBA8_UNORM
        elif channels == 1 and array.dtype == np.uint8:
            field_format = _raw.DVZ_FIELD_FORMAT_R8_UNORM
        elif channels == 1 and array.dtype == np.uint32:
            field_format = _raw.DVZ_FIELD_FORMAT_R32_UINT
        elif channels == 1 and array.dtype == np.float32:
            field_format = _raw.DVZ_FIELD_FORMAT_R32_FLOAT
        else:
            raise ValueError(
                f'unsupported sampled-field dtype/shape: {array.dtype}, {array.shape}; '
                'pass format=... for an explicit field format'
            )

    if semantic is None:
        if field_format == _raw.DVZ_FIELD_FORMAT_RGBA8_UNORM:
            semantic = _raw.DVZ_FIELD_SEMANTIC_COLOR
        elif field_format == _raw.DVZ_FIELD_FORMAT_R32_UINT:
            semantic = _raw.DVZ_FIELD_SEMANTIC_LABEL
        else:
            semantic = _raw.DVZ_FIELD_SEMANTIC_SCALAR

    if color_role is None:
        if semantic == _raw.DVZ_FIELD_SEMANTIC_COLOR:
            color_role = _raw.DVZ_COLOR_ROLE_SRGB_COLOR
        elif semantic == _raw.DVZ_FIELD_SEMANTIC_SCALAR:
            color_role = _raw.DVZ_COLOR_ROLE_DATA
        else:
            color_role = _raw.DVZ_COLOR_ROLE_NONE

    return {
        'dim': inferred_dim,
        'format': field_format,
        'semantic': semantic,
        'color_role': color_role,
        'width': int(width),
        'height': int(height),
        'depth': int(depth),
        'bytes_per_row': int(bytes_per_row),
        'rows_per_image': int(rows_per_image),
    }


def dvz_sampled_field_from_array(
    scene,
    array,
    *,
    format=None,
    semantic=None,
    color_role=None,
    dim=None,
):
    """Create a scene-owned sampled field and upload a NumPy-compatible array.

    Supported inferred inputs are RGBA8 2D arrays shaped ``(height, width, 4)``,
    scalar 2D arrays shaped ``(height, width)``, and scalar 3D arrays shaped
    ``(depth, height, width)``. The payload is copied by Datoviz before return.
    """
    data = np.asarray(array)
    if data.ndim == 0:
        raise ValueError('array must be at least two-dimensional')
    if not data.flags.c_contiguous:
        data = np.ascontiguousarray(data)

    layout = _sampled_field_layout(data, format, semantic, color_role, dim)

    desc = _raw.dvz_sampled_field_desc()
    desc.dim = layout['dim']
    desc.format = layout['format']
    desc.semantic = layout['semantic']
    desc.color_role = layout['color_role']
    desc.width = layout['width']
    desc.height = layout['height']
    desc.depth = layout['depth']

    field = _raw.dvz_sampled_field(scene, ctypes.byref(desc))
    if not field:
        raise RuntimeError('dvz_sampled_field() failed')

    view = _raw.dvz_field_data_view()
    view.data = ctypes.c_void_p(data.ctypes.data)
    view.bytes_per_row = layout['bytes_per_row']
    view.rows_per_image = layout['rows_per_image']

    rc = _raw.dvz_sampled_field_set_data(field, ctypes.byref(view))
    if rc != 0:
        raise RuntimeError(f'dvz_sampled_field_set_data() failed with code {rc}')
    return field


def _field_region_tuple(value, name, *, default_z=None):
    if value is None:
        raise ValueError(f'{name} must not be None')
    items = tuple(int(v) for v in value)
    if len(items) == 2 and default_z is not None:
        items = (items[0], items[1], default_z)
    if len(items) != 3:
        raise ValueError(f'{name} must contain 2 or 3 values')
    return items


def dvz_sampled_field_update_from_array(
    field,
    array,
    *,
    offset=(0, 0, 0),
    extent=None,
    format=None,
    semantic=None,
    color_role=None,
    dim=None,
):
    """Update a sampled-field subregion from a NumPy-compatible patch array.

    The patch array uses the same inferred layouts as ``dvz_sampled_field_from_array``.
    ``offset`` is expressed in sample coordinates as ``(x, y)`` or ``(x, y, z)``.
    When provided, ``extent`` must match the array-derived ``(width, height, depth)``.
    The payload is copied by Datoviz before return.
    """
    data = np.asarray(array)
    if data.ndim == 0:
        raise ValueError('array must be at least two-dimensional')
    if not data.flags.c_contiguous:
        data = np.ascontiguousarray(data)

    layout = _sampled_field_layout(data, format, semantic, color_role, dim)
    region_extent = (layout['width'], layout['height'], layout['depth'])
    if extent is not None:
        explicit_extent = _field_region_tuple(extent, 'extent', default_z=1)
        if explicit_extent != region_extent:
            raise ValueError(
                f'extent {explicit_extent} does not match array-derived extent {region_extent}'
            )

    x, y, z = _field_region_tuple(offset, 'offset', default_z=0)
    if x < 0 or y < 0 or z < 0:
        raise ValueError('offset values must be non-negative')

    region = _raw.DvzFieldRegion()
    region.x = x
    region.y = y
    region.z = z
    region.width = region_extent[0]
    region.height = region_extent[1]
    region.depth = region_extent[2]

    view = _raw.dvz_field_data_view()
    view.data = ctypes.c_void_p(data.ctypes.data)
    view.bytes_per_row = layout['bytes_per_row']
    view.rows_per_image = layout['rows_per_image']

    rc = _raw.dvz_sampled_field_update_region(field, region, ctypes.byref(view))
    if rc != 0:
        raise RuntimeError(f'dvz_sampled_field_update_region() failed with code {rc}')
    return field


def dvz_axis_set_ticks(axis, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _axis_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_axis_set_ticks(axis, _ticks_ptr)


dvz_axis_set_ticks.__doc__ = getattr(_raw.dvz_axis_set_ticks, "__doc__", None)
dvz_axis_set_ticks.argtypes = getattr(_raw.dvz_axis_set_ticks, "argtypes", None)
dvz_axis_set_ticks.restype = getattr(_raw.dvz_axis_set_ticks, "restype", None)


def dvz_band_set_bounds(band, x, lower, upper, count=None):
    _x_ptr, _x_array = _array_arg(x, 'x', _raw.dvz_band_set_bounds, 1, 'float64', None)
    if _x_array is not None:
        _x_count = _shape0_count(_x_array, 'x')
        if count is None:
            count = _x_count
        elif _x_count != int(count):
            raise ValueError(f'x count {_x_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_x_array, 'x')
    _lower_ptr, _lower_array = _array_arg(lower, 'lower', _raw.dvz_band_set_bounds, 2, 'float64', None)
    if _lower_array is not None:
        _lower_count = _shape0_count(_lower_array, 'lower')
        if count is None:
            count = _lower_count
        elif _lower_count != int(count):
            raise ValueError(f'lower count {_lower_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_lower_array, 'lower')
    _upper_ptr, _upper_array = _array_arg(upper, 'upper', _raw.dvz_band_set_bounds, 3, 'float64', None)
    if _upper_array is not None:
        _upper_count = _shape0_count(_upper_array, 'upper')
        if count is None:
            count = _upper_count
        elif _upper_count != int(count):
            raise ValueError(f'upper count {_upper_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_upper_array, 'upper')
    _keepalive = (_x_array, _lower_array, _upper_array,)
    return _raw.dvz_band_set_bounds(band, _x_ptr, _lower_ptr, _upper_ptr, count)


dvz_band_set_bounds.__doc__ = getattr(_raw.dvz_band_set_bounds, "__doc__", None)
dvz_band_set_bounds.argtypes = getattr(_raw.dvz_band_set_bounds, "argtypes", None)
dvz_band_set_bounds.restype = getattr(_raw.dvz_band_set_bounds, "restype", None)


def dvz_band_set_center(band, x, y, count=None):
    _x_ptr, _x_array = _array_arg(x, 'x', _raw.dvz_band_set_center, 1, 'float64', None)
    if _x_array is not None:
        _x_count = _shape0_count(_x_array, 'x')
        if count is None:
            count = _x_count
        elif _x_count != int(count):
            raise ValueError(f'x count {_x_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_x_array, 'x')
    _y_ptr, _y_array = _array_arg(y, 'y', _raw.dvz_band_set_center, 2, 'float64', None)
    if _y_array is not None:
        _y_count = _shape0_count(_y_array, 'y')
        if count is None:
            count = _y_count
        elif _y_count != int(count):
            raise ValueError(f'y count {_y_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_y_array, 'y')
    _keepalive = (_x_array, _y_array,)
    return _raw.dvz_band_set_center(band, _x_ptr, _y_ptr, count)


dvz_band_set_center.__doc__ = getattr(_raw.dvz_band_set_center, "__doc__", None)
dvz_band_set_center.argtypes = getattr(_raw.dvz_band_set_center, "argtypes", None)
dvz_band_set_center.restype = getattr(_raw.dvz_band_set_center, "restype", None)


def dvz_bars_set_intervals(bars, starts, ends, values, count=None):
    _starts_ptr, _starts_array = _array_arg(starts, 'starts', _raw.dvz_bars_set_intervals, 1, 'float64', None)
    if _starts_array is not None:
        _starts_count = _shape0_count(_starts_array, 'starts')
        if count is None:
            count = _starts_count
        elif _starts_count != int(count):
            raise ValueError(f'starts count {_starts_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_starts_array, 'starts')
    _ends_ptr, _ends_array = _array_arg(ends, 'ends', _raw.dvz_bars_set_intervals, 2, 'float64', None)
    if _ends_array is not None:
        _ends_count = _shape0_count(_ends_array, 'ends')
        if count is None:
            count = _ends_count
        elif _ends_count != int(count):
            raise ValueError(f'ends count {_ends_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_ends_array, 'ends')
    _values_ptr, _values_array = _array_arg(values, 'values', _raw.dvz_bars_set_intervals, 3, 'float64', None)
    if _values_array is not None:
        _values_count = _shape0_count(_values_array, 'values')
        if count is None:
            count = _values_count
        elif _values_count != int(count):
            raise ValueError(f'values count {_values_count} does not match count {count}')
    elif count is None:
        count = _shape0_count(_values_array, 'values')
    _keepalive = (_starts_array, _ends_array, _values_array,)
    return _raw.dvz_bars_set_intervals(bars, _starts_ptr, _ends_ptr, _values_ptr, count)


dvz_bars_set_intervals.__doc__ = getattr(_raw.dvz_bars_set_intervals, "__doc__", None)
dvz_bars_set_intervals.argtypes = getattr(_raw.dvz_bars_set_intervals, "argtypes", None)
dvz_bars_set_intervals.restype = getattr(_raw.dvz_bars_set_intervals, "restype", None)


def dvz_colorbar_set_ticks(colorbar, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _colorbar_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_colorbar_set_ticks(colorbar, _ticks_ptr)


dvz_colorbar_set_ticks.__doc__ = getattr(_raw.dvz_colorbar_set_ticks, "__doc__", None)
dvz_colorbar_set_ticks.argtypes = getattr(_raw.dvz_colorbar_set_ticks, "argtypes", None)
dvz_colorbar_set_ticks.restype = getattr(_raw.dvz_colorbar_set_ticks, "restype", None)


def dvz_colormap_custom(scene, label, colors, count=None):
    label_bytes = _encode_string(label, 'label')
    colors = _typed_sequence(colors, np.uint8)
    ptr, keepalive = _array_arg(colors, 'colors', _raw.dvz_colormap_custom, 2, np.uint8, (4,))
    if keepalive is not None:
        if count is None:
            count = len(colors)
        elif len(colors) != int(count):
            raise ValueError(f'colors count {len(colors)} does not match count {count}')
    elif count is None:
        raise TypeError('count must be provided when passing a raw colors pointer')
    return _raw.dvz_colormap_custom(scene, label_bytes, ptr, int(count or 0))


dvz_colormap_custom.__doc__ = getattr(_raw.dvz_colormap_custom, "__doc__", None)
dvz_colormap_custom.argtypes = getattr(_raw.dvz_colormap_custom, "argtypes", None)
dvz_colormap_custom.restype = getattr(_raw.dvz_colormap_custom, "restype", None)


def dvz_gui_table(widget_id, columns, flags=0, column_count=None):
    widget_id = _encode_string(widget_id, 'widget_id')
    if _raw_pointer(columns):
        if column_count is None:
            raise TypeError('column_count must be provided for a raw column pointer')
        return _raw.dvz_gui_table(widget_id, int(column_count), columns, flags)
    items = list(columns)
    if column_count is not None and len(items) != int(column_count):
        raise ValueError(f'columns length {len(items)} does not match column_count {column_count}')
    records = (_raw.DvzGuiTableColumnDesc * len(items))()
    keepalive = [widget_id]
    allowed = {'struct_size', 'flags', 'column_id', 'type', 'initial_width', 'title', 'format', 'reserved'}
    for i, item in enumerate(items):
        if isinstance(item, dict):
            item = dict(item)
            unknown = sorted(set(item) - allowed)
            if unknown:
                raise TypeError(f'columns[{i}] has unknown fields: {", ".join(unknown)}')
            title = _encode_string(item.get('title'), f'columns[{i}].title')
            fmt = _encode_string(item.get('format'), f'columns[{i}].format')
            record = _raw.dvz_gui_table_column_desc()
            for key, value in item.items():
                if key not in {'title', 'format'} and hasattr(record, key):
                    setattr(record, key, value)
            record.title, record.format = title, fmt
            keepalive.extend((title, fmt))
        elif isinstance(item, _raw.DvzGuiTableColumnDesc):
            record = item
        else:
            raise TypeError(f'columns[{i}] must be a mapping or DvzGuiTableColumnDesc')
        if not record.struct_size:
            record.struct_size = ctypes.sizeof(_raw.DvzGuiTableColumnDesc)
        records[i] = record
    return _raw.dvz_gui_table(widget_id, len(records), records, flags)


_raw_dvz_gui_table = getattr(_raw, "dvz_gui_table", None)
dvz_gui_table.__doc__ = getattr(_raw_dvz_gui_table, "__doc__", None)
dvz_gui_table.argtypes = getattr(_raw_dvz_gui_table, "argtypes", None)
dvz_gui_table.restype = getattr(_raw_dvz_gui_table, "restype", None)


def dvz_gui_table_draw(gui, table, events=None, capacity=None):
    return _gui_draw(_raw.dvz_gui_table_draw, gui, table, events, capacity)


_raw_dvz_gui_table_draw = getattr(_raw, "dvz_gui_table_draw", None)
dvz_gui_table_draw.__doc__ = getattr(_raw_dvz_gui_table_draw, "__doc__", None)
dvz_gui_table_draw.argtypes = getattr(_raw_dvz_gui_table_draw, "argtypes", None)
dvz_gui_table_draw.restype = getattr(_raw_dvz_gui_table_draw, "restype", None)


def dvz_gui_table_get_filter(widget):
    size = _raw.dvz_gui_table_get_filter(widget, 0, None)
    if not size:
        return ''
    buffer = ctypes.create_string_buffer(int(size))
    _raw.dvz_gui_table_get_filter(widget, int(size), buffer)
    return buffer.value.decode('utf-8')


_raw_dvz_gui_table_get_filter = getattr(_raw, "dvz_gui_table_get_filter", None)
dvz_gui_table_get_filter.__doc__ = getattr(_raw_dvz_gui_table_get_filter, "__doc__", None)
dvz_gui_table_get_filter.argtypes = getattr(_raw_dvz_gui_table_get_filter, "argtypes", None)
dvz_gui_table_get_filter.restype = getattr(_raw_dvz_gui_table_get_filter, "restype", None)


def dvz_gui_table_get_selection(widget):
    count = _raw.dvz_gui_table_get_selection(widget, 0, None)
    values = (ctypes.c_uint64 * int(count))() if count else None
    if count:
        _raw.dvz_gui_table_get_selection(widget, int(count), values)
    return [] if not count else [int(values[i]) for i in range(int(count))]


_raw_dvz_gui_table_get_selection = getattr(_raw, "dvz_gui_table_get_selection", None)
dvz_gui_table_get_selection.__doc__ = getattr(_raw_dvz_gui_table_get_selection, "__doc__", None)
dvz_gui_table_get_selection.argtypes = getattr(_raw_dvz_gui_table_get_selection, "argtypes", None)
dvz_gui_table_get_selection.restype = getattr(_raw_dvz_gui_table_get_selection, "restype", None)


def dvz_gui_table_get_sort(table):
    column_id = ctypes.c_uint32()
    direction = ctypes.c_int32()
    result = _raw.dvz_gui_table_get_sort(table, ctypes.byref(column_id), ctypes.byref(direction))
    return result, int(column_id.value), int(direction.value)


_raw_dvz_gui_table_get_sort = getattr(_raw, "dvz_gui_table_get_sort", None)
dvz_gui_table_get_sort.__doc__ = getattr(_raw_dvz_gui_table_get_sort, "__doc__", None)
dvz_gui_table_get_sort.argtypes = getattr(_raw_dvz_gui_table_get_sort, "argtypes", None)
dvz_gui_table_get_sort.restype = getattr(_raw_dvz_gui_table_get_sort, "restype", None)


def dvz_gui_table_set_column_bool(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(ctypes.c_bool), np.bool_, row_count)
    return _raw.dvz_gui_table_set_column_bool(table, column_id, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_column_bool = getattr(_raw, "dvz_gui_table_set_column_bool", None)
dvz_gui_table_set_column_bool.__doc__ = getattr(_raw_dvz_gui_table_set_column_bool, "__doc__", None)
dvz_gui_table_set_column_bool.argtypes = getattr(_raw_dvz_gui_table_set_column_bool, "argtypes", None)
dvz_gui_table_set_column_bool.restype = getattr(_raw_dvz_gui_table_set_column_bool, "restype", None)


def dvz_gui_table_set_column_color(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(_raw.DvzColor), np.uint8, row_count, shape_tail=(4,))
    return _raw.dvz_gui_table_set_column_color(table, column_id, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_column_color = getattr(_raw, "dvz_gui_table_set_column_color", None)
dvz_gui_table_set_column_color.__doc__ = getattr(_raw_dvz_gui_table_set_column_color, "__doc__", None)
dvz_gui_table_set_column_color.argtypes = getattr(_raw_dvz_gui_table_set_column_color, "argtypes", None)
dvz_gui_table_set_column_color.restype = getattr(_raw_dvz_gui_table_set_column_color, "restype", None)


def dvz_gui_table_set_column_double(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(ctypes.c_double), np.float64, row_count)
    return _raw.dvz_gui_table_set_column_double(table, column_id, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_column_double = getattr(_raw, "dvz_gui_table_set_column_double", None)
dvz_gui_table_set_column_double.__doc__ = getattr(_raw_dvz_gui_table_set_column_double, "__doc__", None)
dvz_gui_table_set_column_double.argtypes = getattr(_raw_dvz_gui_table_set_column_double, "argtypes", None)
dvz_gui_table_set_column_double.restype = getattr(_raw_dvz_gui_table_set_column_double, "restype", None)


def dvz_gui_table_set_column_int64(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(ctypes.c_int64), np.int64, row_count)
    return _raw.dvz_gui_table_set_column_int64(table, column_id, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_column_int64 = getattr(_raw, "dvz_gui_table_set_column_int64", None)
dvz_gui_table_set_column_int64.__doc__ = getattr(_raw_dvz_gui_table_set_column_int64, "__doc__", None)
dvz_gui_table_set_column_int64.argtypes = getattr(_raw_dvz_gui_table_set_column_int64, "argtypes", None)
dvz_gui_table_set_column_int64.restype = getattr(_raw_dvz_gui_table_set_column_int64, "restype", None)


def dvz_gui_table_set_column_text(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_strings(values, 'values', row_count)
    return _raw.dvz_gui_table_set_column_text(table, column_id, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_column_text = getattr(_raw, "dvz_gui_table_set_column_text", None)
dvz_gui_table_set_column_text.__doc__ = getattr(_raw_dvz_gui_table_set_column_text, "__doc__", None)
dvz_gui_table_set_column_text.argtypes = getattr(_raw_dvz_gui_table_set_column_text, "argtypes", None)
dvz_gui_table_set_column_text.restype = getattr(_raw_dvz_gui_table_set_column_text, "restype", None)


def dvz_gui_table_set_matches(table, values, row_count=None):
    if row_count is None and values is not None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(ctypes.c_bool), np.bool_, row_count, optional=True)
    return _raw.dvz_gui_table_set_matches(table, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_matches = getattr(_raw, "dvz_gui_table_set_matches", None)
dvz_gui_table_set_matches.__doc__ = getattr(_raw_dvz_gui_table_set_matches, "__doc__", None)
dvz_gui_table_set_matches.argtypes = getattr(_raw_dvz_gui_table_set_matches, "argtypes", None)
dvz_gui_table_set_matches.restype = getattr(_raw_dvz_gui_table_set_matches, "restype", None)


def dvz_gui_table_set_rows(table, keys, flags=0, row_count=None):
    if row_count is None and not _raw_pointer(keys):
        row_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, row_count)
    return _raw.dvz_gui_table_set_rows(table, int(row_count or 0), ptr, flags)


_raw_dvz_gui_table_set_rows = getattr(_raw, "dvz_gui_table_set_rows", None)
dvz_gui_table_set_rows.__doc__ = getattr(_raw_dvz_gui_table_set_rows, "__doc__", None)
dvz_gui_table_set_rows.argtypes = getattr(_raw_dvz_gui_table_set_rows, "argtypes", None)
dvz_gui_table_set_rows.restype = getattr(_raw_dvz_gui_table_set_rows, "restype", None)


def dvz_gui_table_set_selection(table, keys, key_count=None):
    if key_count is None and not _raw_pointer(keys):
        key_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, key_count)
    return _raw.dvz_gui_table_set_selection(table, int(key_count or 0), ptr)


_raw_dvz_gui_table_set_selection = getattr(_raw, "dvz_gui_table_set_selection", None)
dvz_gui_table_set_selection.__doc__ = getattr(_raw_dvz_gui_table_set_selection, "__doc__", None)
dvz_gui_table_set_selection.argtypes = getattr(_raw_dvz_gui_table_set_selection, "argtypes", None)
dvz_gui_table_set_selection.restype = getattr(_raw_dvz_gui_table_set_selection, "restype", None)


def dvz_gui_table_set_styles(table, styles, style_count=None):
    if style_count is None and not _raw_pointer(styles):
        style_count = len(styles)
    ptr, keepalive = _gui_records(styles, _raw.DvzGuiDataStyle, 'styles', style_count)
    return _raw.dvz_gui_table_set_styles(table, int(style_count or 0), ptr)


_raw_dvz_gui_table_set_styles = getattr(_raw, "dvz_gui_table_set_styles", None)
dvz_gui_table_set_styles.__doc__ = getattr(_raw_dvz_gui_table_set_styles, "__doc__", None)
dvz_gui_table_set_styles.argtypes = getattr(_raw_dvz_gui_table_set_styles, "argtypes", None)
dvz_gui_table_set_styles.restype = getattr(_raw_dvz_gui_table_set_styles, "restype", None)


def dvz_gui_table_set_visible(table, values, row_count=None):
    if row_count is None and values is not None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(ctypes.c_bool), np.bool_, row_count, optional=True)
    return _raw.dvz_gui_table_set_visible(table, int(row_count or 0), ptr)


_raw_dvz_gui_table_set_visible = getattr(_raw, "dvz_gui_table_set_visible", None)
dvz_gui_table_set_visible.__doc__ = getattr(_raw_dvz_gui_table_set_visible, "__doc__", None)
dvz_gui_table_set_visible.argtypes = getattr(_raw_dvz_gui_table_set_visible, "argtypes", None)
dvz_gui_table_set_visible.restype = getattr(_raw_dvz_gui_table_set_visible, "restype", None)


def dvz_gui_tree_draw(gui, tree, events=None, capacity=None):
    return _gui_draw(_raw.dvz_gui_tree_draw, gui, tree, events, capacity)


_raw_dvz_gui_tree_draw = getattr(_raw, "dvz_gui_tree_draw", None)
dvz_gui_tree_draw.__doc__ = getattr(_raw_dvz_gui_tree_draw, "__doc__", None)
dvz_gui_tree_draw.argtypes = getattr(_raw_dvz_gui_tree_draw, "argtypes", None)
dvz_gui_tree_draw.restype = getattr(_raw_dvz_gui_tree_draw, "restype", None)


def dvz_gui_tree_get_expanded(widget):
    count = _raw.dvz_gui_tree_get_expanded(widget, 0, None)
    values = (ctypes.c_uint64 * int(count))() if count else None
    if count:
        _raw.dvz_gui_tree_get_expanded(widget, int(count), values)
    return [] if not count else [int(values[i]) for i in range(int(count))]


_raw_dvz_gui_tree_get_expanded = getattr(_raw, "dvz_gui_tree_get_expanded", None)
dvz_gui_tree_get_expanded.__doc__ = getattr(_raw_dvz_gui_tree_get_expanded, "__doc__", None)
dvz_gui_tree_get_expanded.argtypes = getattr(_raw_dvz_gui_tree_get_expanded, "argtypes", None)
dvz_gui_tree_get_expanded.restype = getattr(_raw_dvz_gui_tree_get_expanded, "restype", None)


def dvz_gui_tree_get_filter(widget):
    size = _raw.dvz_gui_tree_get_filter(widget, 0, None)
    if not size:
        return ''
    buffer = ctypes.create_string_buffer(int(size))
    _raw.dvz_gui_tree_get_filter(widget, int(size), buffer)
    return buffer.value.decode('utf-8')


_raw_dvz_gui_tree_get_filter = getattr(_raw, "dvz_gui_tree_get_filter", None)
dvz_gui_tree_get_filter.__doc__ = getattr(_raw_dvz_gui_tree_get_filter, "__doc__", None)
dvz_gui_tree_get_filter.argtypes = getattr(_raw_dvz_gui_tree_get_filter, "argtypes", None)
dvz_gui_tree_get_filter.restype = getattr(_raw_dvz_gui_tree_get_filter, "restype", None)


def dvz_gui_tree_get_selection(widget):
    count = _raw.dvz_gui_tree_get_selection(widget, 0, None)
    values = (ctypes.c_uint64 * int(count))() if count else None
    if count:
        _raw.dvz_gui_tree_get_selection(widget, int(count), values)
    return [] if not count else [int(values[i]) for i in range(int(count))]


_raw_dvz_gui_tree_get_selection = getattr(_raw, "dvz_gui_tree_get_selection", None)
dvz_gui_tree_get_selection.__doc__ = getattr(_raw_dvz_gui_tree_get_selection, "__doc__", None)
dvz_gui_tree_get_selection.argtypes = getattr(_raw_dvz_gui_tree_get_selection, "argtypes", None)
dvz_gui_tree_get_selection.restype = getattr(_raw_dvz_gui_tree_get_selection, "restype", None)


def dvz_gui_tree_set_expanded(tree, keys, key_count=None):
    if key_count is None and not _raw_pointer(keys):
        key_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, key_count)
    return _raw.dvz_gui_tree_set_expanded(tree, int(key_count or 0), ptr)


_raw_dvz_gui_tree_set_expanded = getattr(_raw, "dvz_gui_tree_set_expanded", None)
dvz_gui_tree_set_expanded.__doc__ = getattr(_raw_dvz_gui_tree_set_expanded, "__doc__", None)
dvz_gui_tree_set_expanded.argtypes = getattr(_raw_dvz_gui_tree_set_expanded, "argtypes", None)
dvz_gui_tree_set_expanded.restype = getattr(_raw_dvz_gui_tree_set_expanded, "restype", None)


def dvz_gui_tree_set_matches(tree, matches, row_count=None):
    if row_count is None and matches is not None and not _raw_pointer(matches):
        row_count = len(matches)
    ptr, keepalive = _gui_records(matches, _raw.DvzGuiDataStyle, 'matches', row_count) if 'matches' == 'styles' else _gui_array(matches, 'matches', ctypes.POINTER(ctypes.c_bool), np.bool_, row_count, optional=True)
    return _raw.dvz_gui_tree_set_matches(tree, int(row_count or 0), ptr)


_raw_dvz_gui_tree_set_matches = getattr(_raw, "dvz_gui_tree_set_matches", None)
dvz_gui_tree_set_matches.__doc__ = getattr(_raw_dvz_gui_tree_set_matches, "__doc__", None)
dvz_gui_tree_set_matches.argtypes = getattr(_raw_dvz_gui_tree_set_matches, "argtypes", None)
dvz_gui_tree_set_matches.restype = getattr(_raw_dvz_gui_tree_set_matches, "restype", None)


def dvz_gui_tree_set_rows(tree, keys, parents, labels, secondary_labels=None, flags=0, row_count=None):
    keys_ptr, keys_keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, row_count)
    if row_count is None:
        row_count = len(keys) if not _raw_pointer(keys) else None
    parents_ptr, parents_keepalive = _gui_array(parents, 'parents', ctypes.POINTER(ctypes.c_uint32), np.uint32, row_count)
    labels_ptr, labels_keepalive = _gui_strings(labels, 'labels', row_count)
    secondary_ptr, secondary_keepalive = _gui_strings(secondary_labels, 'secondary_labels', row_count, optional=True)
    return _raw.dvz_gui_tree_set_rows(tree, int(row_count), keys_ptr, parents_ptr, labels_ptr, secondary_ptr, flags)


_raw_dvz_gui_tree_set_rows = getattr(_raw, "dvz_gui_tree_set_rows", None)
dvz_gui_tree_set_rows.__doc__ = getattr(_raw_dvz_gui_tree_set_rows, "__doc__", None)
dvz_gui_tree_set_rows.argtypes = getattr(_raw_dvz_gui_tree_set_rows, "argtypes", None)
dvz_gui_tree_set_rows.restype = getattr(_raw_dvz_gui_tree_set_rows, "restype", None)


def dvz_gui_tree_set_selection(tree, keys, key_count=None):
    if key_count is None and not _raw_pointer(keys):
        key_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, key_count)
    return _raw.dvz_gui_tree_set_selection(tree, int(key_count or 0), ptr)


_raw_dvz_gui_tree_set_selection = getattr(_raw, "dvz_gui_tree_set_selection", None)
dvz_gui_tree_set_selection.__doc__ = getattr(_raw_dvz_gui_tree_set_selection, "__doc__", None)
dvz_gui_tree_set_selection.argtypes = getattr(_raw_dvz_gui_tree_set_selection, "argtypes", None)
dvz_gui_tree_set_selection.restype = getattr(_raw_dvz_gui_tree_set_selection, "restype", None)


def dvz_gui_tree_set_styles(tree, styles, row_count=None):
    if row_count is None and styles is not None and not _raw_pointer(styles):
        row_count = len(styles)
    ptr, keepalive = _gui_records(styles, _raw.DvzGuiDataStyle, 'styles', row_count) if 'styles' == 'styles' else _gui_array(styles, 'styles', ctypes.POINTER(_raw.DvzGuiDataStyle), None, row_count, optional=True)
    return _raw.dvz_gui_tree_set_styles(tree, int(row_count or 0), ptr)


_raw_dvz_gui_tree_set_styles = getattr(_raw, "dvz_gui_tree_set_styles", None)
dvz_gui_tree_set_styles.__doc__ = getattr(_raw_dvz_gui_tree_set_styles, "__doc__", None)
dvz_gui_tree_set_styles.argtypes = getattr(_raw_dvz_gui_tree_set_styles, "argtypes", None)
dvz_gui_tree_set_styles.restype = getattr(_raw_dvz_gui_tree_set_styles, "restype", None)


def dvz_gui_tree_set_swatches(tree, colors, row_count=None):
    if row_count is None and colors is not None and not _raw_pointer(colors):
        row_count = len(colors)
    ptr, keepalive = _gui_records(colors, _raw.DvzGuiDataStyle, 'colors', row_count) if 'swatches' == 'styles' else _gui_array(colors, 'colors', ctypes.POINTER(_raw.DvzColor), np.uint8, row_count, optional=True, shape_tail=(4,))
    return _raw.dvz_gui_tree_set_swatches(tree, int(row_count or 0), ptr)


_raw_dvz_gui_tree_set_swatches = getattr(_raw, "dvz_gui_tree_set_swatches", None)
dvz_gui_tree_set_swatches.__doc__ = getattr(_raw_dvz_gui_tree_set_swatches, "__doc__", None)
dvz_gui_tree_set_swatches.argtypes = getattr(_raw_dvz_gui_tree_set_swatches, "argtypes", None)
dvz_gui_tree_set_swatches.restype = getattr(_raw_dvz_gui_tree_set_swatches, "restype", None)


def dvz_gui_tree_set_visible(tree, visible, row_count=None):
    if row_count is None and visible is not None and not _raw_pointer(visible):
        row_count = len(visible)
    ptr, keepalive = _gui_records(visible, _raw.DvzGuiDataStyle, 'visible', row_count) if 'visible' == 'styles' else _gui_array(visible, 'visible', ctypes.POINTER(ctypes.c_bool), np.bool_, row_count, optional=True)
    return _raw.dvz_gui_tree_set_visible(tree, int(row_count or 0), ptr)


_raw_dvz_gui_tree_set_visible = getattr(_raw, "dvz_gui_tree_set_visible", None)
dvz_gui_tree_set_visible.__doc__ = getattr(_raw_dvz_gui_tree_set_visible, "__doc__", None)
dvz_gui_tree_set_visible.argtypes = getattr(_raw_dvz_gui_tree_set_visible, "argtypes", None)
dvz_gui_tree_set_visible.restype = getattr(_raw_dvz_gui_tree_set_visible, "restype", None)


def dvz_panel_set_lights(panel, lights, count=None):
    if _raw_pointer(lights):
        if count is None:
            raise TypeError('count must be provided when passing a raw light pointer')
        ptr = lights
    else:
        items = list(lights)
        if count is not None and len(items) != int(count):
            raise ValueError(f'lights length {len(items)} does not match count {count}')
        count = len(items)
        target = _raw.dvz_panel_set_lights.argtypes[1]._type_
        ptr = (target * count)(*items) if count else None
    return _raw.dvz_panel_set_lights(panel, ptr, int(count or 0))


dvz_panel_set_lights.__doc__ = getattr(_raw.dvz_panel_set_lights, "__doc__", None)
dvz_panel_set_lights.argtypes = getattr(_raw.dvz_panel_set_lights, "argtypes", None)
dvz_panel_set_lights.restype = getattr(_raw.dvz_panel_set_lights, "restype", None)


def dvz_path_set_subpaths(visual, subpath_count, lengths=None):
    if lengths is None and not _raw_pointer(subpath_count):
        lengths = subpath_count
        subpath_count = len(lengths)
    lengths = _typed_sequence(lengths, np.uint32)
    ptr, keepalive = _array_arg(lengths, 'lengths', _raw.dvz_path_set_subpaths, 2, np.uint32)
    if keepalive is not None and len(lengths) != int(subpath_count):
        raise ValueError(f'lengths count {len(lengths)} does not match subpath_count {subpath_count}')
    return _raw.dvz_path_set_subpaths(visual, int(subpath_count), ptr)


dvz_path_set_subpaths.__doc__ = getattr(_raw.dvz_path_set_subpaths, "__doc__", None)
dvz_path_set_subpaths.argtypes = getattr(_raw.dvz_path_set_subpaths, "argtypes", None)
dvz_path_set_subpaths.restype = getattr(_raw.dvz_path_set_subpaths, "restype", None)


def dvz_scene_buffer_set_data(buffer, data, byte_size=None):
    _data_ptr, _data_array = _array_arg(data, 'data', _raw.dvz_scene_buffer_set_data, 1, None, None)
    if _data_array is not None:
        _data_size = _nbytes_size(_data_array, 'data')
        if byte_size is None:
            byte_size = _data_size
        elif _data_size != int(byte_size):
            raise ValueError(f'data byte size {_data_size} does not match byte_size {byte_size}')
    elif byte_size is None:
        byte_size = _nbytes_size(_data_array, 'data')
    _keepalive = (_data_array,)
    return _raw.dvz_scene_buffer_set_data(buffer, _data_ptr, byte_size)


dvz_scene_buffer_set_data.__doc__ = getattr(_raw.dvz_scene_buffer_set_data, "__doc__", None)
dvz_scene_buffer_set_data.argtypes = getattr(_raw.dvz_scene_buffer_set_data, "argtypes", None)
dvz_scene_buffer_set_data.restype = getattr(_raw.dvz_scene_buffer_set_data, "restype", None)


def dvz_text_set_anchors(text, anchors, item_count=None):
    _anchors_ptr, _anchors_array = _array_arg(anchors, 'anchors', _raw.dvz_text_set_anchors, 1, 'float32', None)
    if _anchors_array is not None:
        _anchors_count = _shape0_count(_anchors_array, 'anchors')
        if item_count is None:
            item_count = _anchors_count
        elif _anchors_count != int(item_count):
            raise ValueError(f'anchors count {_anchors_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_anchors_array, 'anchors')
    _keepalive = (_anchors_array,)
    return _raw.dvz_text_set_anchors(text, _anchors_ptr, item_count)


dvz_text_set_anchors.__doc__ = getattr(_raw.dvz_text_set_anchors, "__doc__", None)
dvz_text_set_anchors.argtypes = getattr(_raw.dvz_text_set_anchors, "argtypes", None)
dvz_text_set_anchors.restype = getattr(_raw.dvz_text_set_anchors, "restype", None)


def dvz_text_set_angles(text, angles, item_count=None):
    _angles_ptr, _angles_array = _array_arg(angles, 'angles', _raw.dvz_text_set_angles, 1, 'float32', None)
    if _angles_array is not None:
        _angles_count = _shape0_count(_angles_array, 'angles')
        if item_count is None:
            item_count = _angles_count
        elif _angles_count != int(item_count):
            raise ValueError(f'angles count {_angles_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_angles_array, 'angles')
    _keepalive = (_angles_array,)
    return _raw.dvz_text_set_angles(text, _angles_ptr, item_count)


dvz_text_set_angles.__doc__ = getattr(_raw.dvz_text_set_angles, "__doc__", None)
dvz_text_set_angles.argtypes = getattr(_raw.dvz_text_set_angles, "argtypes", None)
dvz_text_set_angles.restype = getattr(_raw.dvz_text_set_angles, "restype", None)


def dvz_text_set_colors(text, colors, item_count=None):
    _colors_ptr, _colors_array = _array_arg(colors, 'colors', _raw.dvz_text_set_colors, 1, 'uint8', None)
    if _colors_array is not None:
        _colors_count = _shape0_count(_colors_array, 'colors')
        if item_count is None:
            item_count = _colors_count
        elif _colors_count != int(item_count):
            raise ValueError(f'colors count {_colors_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_colors_array, 'colors')
    _keepalive = (_colors_array,)
    return _raw.dvz_text_set_colors(text, _colors_ptr, item_count)


dvz_text_set_colors.__doc__ = getattr(_raw.dvz_text_set_colors, "__doc__", None)
dvz_text_set_colors.argtypes = getattr(_raw.dvz_text_set_colors, "argtypes", None)
dvz_text_set_colors.restype = getattr(_raw.dvz_text_set_colors, "restype", None)


def dvz_text_set_items(text, items, item_count=None):
    _items_ptr, _items_array = _array_arg(items, 'items', _raw.dvz_text_set_items, 1, None, None)
    if _items_array is not None:
        _items_count = _shape0_count(_items_array, 'items')
        if item_count is None:
            item_count = _items_count
        elif _items_count != int(item_count):
            raise ValueError(f'items count {_items_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_items_array, 'items')
    _keepalive = (_items_array,)
    return _raw.dvz_text_set_items(text, _items_ptr, item_count)


dvz_text_set_items.__doc__ = getattr(_raw.dvz_text_set_items, "__doc__", None)
dvz_text_set_items.argtypes = getattr(_raw.dvz_text_set_items, "argtypes", None)
dvz_text_set_items.restype = getattr(_raw.dvz_text_set_items, "restype", None)


def dvz_text_set_offsets(text, offsets, item_count=None):
    _offsets_ptr, _offsets_array = _array_arg(offsets, 'offsets', _raw.dvz_text_set_offsets, 1, 'float32', None)
    if _offsets_array is not None:
        _offsets_count = _shape0_count(_offsets_array, 'offsets')
        if item_count is None:
            item_count = _offsets_count
        elif _offsets_count != int(item_count):
            raise ValueError(f'offsets count {_offsets_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_offsets_array, 'offsets')
    _keepalive = (_offsets_array,)
    return _raw.dvz_text_set_offsets(text, _offsets_ptr, item_count)


dvz_text_set_offsets.__doc__ = getattr(_raw.dvz_text_set_offsets, "__doc__", None)
dvz_text_set_offsets.argtypes = getattr(_raw.dvz_text_set_offsets, "argtypes", None)
dvz_text_set_offsets.restype = getattr(_raw.dvz_text_set_offsets, "restype", None)


def dvz_text_set_positions(text, positions, item_count=None):
    _positions_ptr, _positions_array = _array_arg(positions, 'positions', _raw.dvz_text_set_positions, 1, 'float64', None)
    if _positions_array is not None:
        _positions_count = _shape0_count(_positions_array, 'positions')
        if item_count is None:
            item_count = _positions_count
        elif _positions_count != int(item_count):
            raise ValueError(f'positions count {_positions_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_positions_array, 'positions')
    _keepalive = (_positions_array,)
    return _raw.dvz_text_set_positions(text, _positions_ptr, item_count)


dvz_text_set_positions.__doc__ = getattr(_raw.dvz_text_set_positions, "__doc__", None)
dvz_text_set_positions.argtypes = getattr(_raw.dvz_text_set_positions, "argtypes", None)
dvz_text_set_positions.restype = getattr(_raw.dvz_text_set_positions, "restype", None)


def dvz_text_set_sizes(text, sizes_px, item_count=None):
    _sizes_px_ptr, _sizes_px_array = _array_arg(sizes_px, 'sizes_px', _raw.dvz_text_set_sizes, 1, 'float32', None)
    if _sizes_px_array is not None:
        _sizes_px_count = _shape0_count(_sizes_px_array, 'sizes_px')
        if item_count is None:
            item_count = _sizes_px_count
        elif _sizes_px_count != int(item_count):
            raise ValueError(f'sizes_px count {_sizes_px_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_sizes_px_array, 'sizes_px')
    _keepalive = (_sizes_px_array,)
    return _raw.dvz_text_set_sizes(text, _sizes_px_ptr, item_count)


dvz_text_set_sizes.__doc__ = getattr(_raw.dvz_text_set_sizes, "__doc__", None)
dvz_text_set_sizes.argtypes = getattr(_raw.dvz_text_set_sizes, "argtypes", None)
dvz_text_set_sizes.restype = getattr(_raw.dvz_text_set_sizes, "restype", None)


def dvz_text_set_strings(text, strings, item_count=None):
    ptr, keepalive = _gui_strings(strings, 'strings', item_count)
    if item_count is None and not _raw_pointer(strings):
        item_count = len(strings)
    return _raw.dvz_text_set_strings(text, ptr, int(item_count or 0))


dvz_text_set_strings.__doc__ = getattr(_raw.dvz_text_set_strings, "__doc__", None)
dvz_text_set_strings.argtypes = getattr(_raw.dvz_text_set_strings, "argtypes", None)
dvz_text_set_strings.restype = getattr(_raw.dvz_text_set_strings, "restype", None)


def dvz_view_window(app, figure, width, height, title):
    _title_bytes = _encode_string(title, 'title')
    _keepalive = (_title_bytes,)
    return _raw.dvz_view_window(app, figure, width, height, _title_bytes)


dvz_view_window.__doc__ = getattr(_raw.dvz_view_window, "__doc__", None)
dvz_view_window.argtypes = getattr(_raw.dvz_view_window, "argtypes", None)
dvz_view_window.restype = getattr(_raw.dvz_view_window, "restype", None)


def dvz_visual_set_data(visual, attr_name, data, item_count=None):
    _attr_name_bytes = _encode_string(attr_name, 'attr_name')
    _data_ptr, _data_array = _array_arg(data, 'data', _raw.dvz_visual_set_data, 2, None, None)
    if _data_array is not None:
        _data_count = _shape0_count(_data_array, 'data')
        if item_count is None:
            item_count = _data_count
        elif _data_count != int(item_count):
            raise ValueError(f'data count {_data_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_data_array, 'data')
    _keepalive = (_attr_name_bytes, _data_array,)
    return _raw.dvz_visual_set_data(visual, _attr_name_bytes, _data_ptr, item_count)


dvz_visual_set_data.__doc__ = getattr(_raw.dvz_visual_set_data, "__doc__", None)
dvz_visual_set_data.argtypes = getattr(_raw.dvz_visual_set_data, "argtypes", None)
dvz_visual_set_data.restype = getattr(_raw.dvz_visual_set_data, "restype", None)


def dvz_visual_set_data_many(visual, updates, update_count=None):
    if update_count is not None:
        return _raw.dvz_visual_set_data_many(visual, updates, update_count)
    if _raw_pointer(updates):
        raise TypeError('update_count must be provided when passing raw update descriptors')
    _updates_records, _updates_keepalive = _visual_data_updates_arg(updates)
    _keepalive = (_updates_records, _updates_keepalive,)
    return _raw.dvz_visual_set_data_many(visual, _updates_records, len(_updates_records))


dvz_visual_set_data_many.__doc__ = getattr(_raw.dvz_visual_set_data_many, "__doc__", None)
dvz_visual_set_data_many.argtypes = getattr(_raw.dvz_visual_set_data_many, "argtypes", None)
dvz_visual_set_data_many.restype = getattr(_raw.dvz_visual_set_data_many, "restype", None)


def dvz_visual_set_data_range(visual, attr_name, first_item, data, item_count=None):
    _attr_name_bytes = _encode_string(attr_name, 'attr_name')
    _data_ptr, _data_array = _array_arg(data, 'data', _raw.dvz_visual_set_data_range, 3, None, None)
    if _data_array is not None:
        _data_count = _shape0_count(_data_array, 'data')
        if item_count is None:
            item_count = _data_count
        elif _data_count != int(item_count):
            raise ValueError(f'data count {_data_count} does not match item_count {item_count}')
    elif item_count is None:
        item_count = _shape0_count(_data_array, 'data')
    _keepalive = (_attr_name_bytes, _data_array,)
    return _raw.dvz_visual_set_data_range(visual, _attr_name_bytes, first_item, _data_ptr, item_count)


dvz_visual_set_data_range.__doc__ = getattr(_raw.dvz_visual_set_data_range, "__doc__", None)
dvz_visual_set_data_range.argtypes = getattr(_raw.dvz_visual_set_data_range, "argtypes", None)
dvz_visual_set_data_range.restype = getattr(_raw.dvz_visual_set_data_range, "restype", None)


def dvz_visual_set_index_data(visual, indices, index_count=None):
    _indices_ptr, _indices_array = _array_arg(indices, 'indices', _raw.dvz_visual_set_index_data, 1, 'uint32', None)
    if _indices_array is not None:
        _indices_count = _shape0_count(_indices_array, 'indices')
        if index_count is None:
            index_count = _indices_count
        elif _indices_count != int(index_count):
            raise ValueError(f'indices count {_indices_count} does not match index_count {index_count}')
    elif index_count is None:
        index_count = _shape0_count(_indices_array, 'indices')
    _keepalive = (_indices_array,)
    return _raw.dvz_visual_set_index_data(visual, _indices_ptr, index_count)


dvz_visual_set_index_data.__doc__ = getattr(_raw.dvz_visual_set_index_data, "__doc__", None)
dvz_visual_set_index_data.argtypes = getattr(_raw.dvz_visual_set_index_data, "argtypes", None)
dvz_visual_set_index_data.restype = getattr(_raw.dvz_visual_set_index_data, "restype", None)


def dvz_visual_set_link_keys(visual, channel, link_keys, item_count=None):
    link_keys = _typed_sequence(link_keys, np.uint64)
    ptr, keepalive = _array_arg(link_keys, 'link_keys', _raw.dvz_visual_set_link_keys, 2, np.uint64)
    if keepalive is not None:
        if item_count is None:
            item_count = len(link_keys)
        elif len(link_keys) != int(item_count):
            raise ValueError(f'link_keys count {len(link_keys)} does not match item_count {item_count}')
    elif item_count is None:
        raise TypeError('item_count must be provided when passing a raw link_keys pointer')
    return _raw.dvz_visual_set_link_keys(visual, channel, ptr, int(item_count or 0))


dvz_visual_set_link_keys.__doc__ = getattr(_raw.dvz_visual_set_link_keys, "__doc__", None)
dvz_visual_set_link_keys.argtypes = getattr(_raw.dvz_visual_set_link_keys, "argtypes", None)
dvz_visual_set_link_keys.restype = getattr(_raw.dvz_visual_set_link_keys, "restype", None)


_ARRAY_FACADE_FUNCTIONS = ['dvz_axis_set_ticks', 'dvz_band_set_bounds', 'dvz_band_set_center', 'dvz_bars_set_intervals', 'dvz_colorbar_set_ticks', 'dvz_colormap_custom', 'dvz_gui_table', 'dvz_gui_table_draw', 'dvz_gui_table_get_filter', 'dvz_gui_table_get_selection', 'dvz_gui_table_get_sort', 'dvz_gui_table_set_column_bool', 'dvz_gui_table_set_column_color', 'dvz_gui_table_set_column_double', 'dvz_gui_table_set_column_int64', 'dvz_gui_table_set_column_text', 'dvz_gui_table_set_matches', 'dvz_gui_table_set_rows', 'dvz_gui_table_set_selection', 'dvz_gui_table_set_styles', 'dvz_gui_table_set_visible', 'dvz_gui_tree_draw', 'dvz_gui_tree_get_expanded', 'dvz_gui_tree_get_filter', 'dvz_gui_tree_get_selection', 'dvz_gui_tree_set_expanded', 'dvz_gui_tree_set_matches', 'dvz_gui_tree_set_rows', 'dvz_gui_tree_set_selection', 'dvz_gui_tree_set_styles', 'dvz_gui_tree_set_swatches', 'dvz_gui_tree_set_visible', 'dvz_panel_set_lights', 'dvz_path_set_subpaths', 'dvz_scene_buffer_set_data', 'dvz_text_set_anchors', 'dvz_text_set_angles', 'dvz_text_set_colors', 'dvz_text_set_items', 'dvz_text_set_offsets', 'dvz_text_set_positions', 'dvz_text_set_sizes', 'dvz_text_set_strings', 'dvz_view_window', 'dvz_visual_set_data', 'dvz_visual_set_data_many', 'dvz_visual_set_data_range', 'dvz_visual_set_index_data', 'dvz_visual_set_link_keys']

for _name in getattr(_raw, "__all__", dir(_raw)):
    if _name not in globals():
        globals()[_name] = getattr(_raw, _name)

__all__ = [name for name in globals() if name.startswith(('dvz_', 'Dvz', 'DVZ_'))]
