"""
Array-aware facade for the Datoviz v0.4 Python binding.

This file is generated by tools/bindings/generate_array_facade.py. Do not edit it by hand.
"""

from __future__ import annotations

import ctypes

import numpy as np

from . import raw as _raw


def _encode_string(value, name):
    if isinstance(value, str):
        return value.encode('utf-8')
    if isinstance(value, bytes) or value is None:
        return value
    raise TypeError(f'{name} must be str, bytes, or None')


def _raw_pointer(value):
    if isinstance(value, (int, ctypes.c_void_p, ctypes.Array, ctypes._Pointer)):
        return True
    if type(value).__name__ == 'CArgObject' and hasattr(value, '_obj'):
        return True
    return hasattr(value, '_as_parameter_')


def _array_arg(value, name, raw_func, pointer_index, dtype=None):
    if _raw_pointer(value):
        return value, None
    array = np.asarray(value)
    if dtype is not None:
        expected = np.dtype(dtype)
        if array.dtype != expected:
            raise ValueError(f'{name} must have dtype {expected}, got {array.dtype}')
    if array.ndim == 0:
        raise ValueError(f'{name} must be at least one-dimensional')
    if not array.flags.c_contiguous:
        array = np.ascontiguousarray(array)
    pointer = ctypes.c_void_p(array.ctypes.data)
    target = None
    argtypes = getattr(raw_func, 'argtypes', None)
    if argtypes is not None and pointer_index < len(argtypes):
        target = argtypes[pointer_index]
    if target is not None and target is not ctypes.c_void_p:
        pointer = ctypes.cast(pointer, target)
    return pointer, array


def _shape0_count(array, name):
    if array is None:
        raise TypeError(f'{name} count must be provided when passing a raw pointer')
    return int(array.shape[0])


def _nbytes_size(array, name):
    if array is None:
        raise TypeError(f'{name} byte size must be provided when passing a raw pointer')
    return int(array.nbytes)


def _visual_data_updates_arg(updates):
    if isinstance(updates, dict):
        items = list(updates.items())
    else:
        try:
            items = list(updates)
        except TypeError as exc:
            raise TypeError('updates must be a mapping or iterable of (attr_name, data) pairs') from exc
    if not items:
        raise ValueError('updates must not be empty')

    records = (_raw.DvzVisualDataUpdate * len(items))()
    keepalive = []
    item_count = None

    for i, item in enumerate(items):
        try:
            attr_name, data = item
        except (TypeError, ValueError) as exc:
            raise TypeError('updates must contain (attr_name, data) pairs') from exc

        attr_name_bytes = _encode_string(attr_name, f'updates[{i}].attr_name')
        data_array = np.asarray(data)
        if data_array.ndim == 0:
            raise ValueError(f'updates[{attr_name!r}] data must be at least one-dimensional')
        if not data_array.flags.c_contiguous:
            data_array = np.ascontiguousarray(data_array)
        count = int(data_array.shape[0])
        if item_count is None:
            item_count = count
        elif count != item_count:
            raise ValueError(
                f'updates[{attr_name!r}] item count {count} does not match expected {item_count}'
            )

        records[i].attr_name = attr_name_bytes
        records[i].data = ctypes.c_void_p(data_array.ctypes.data)
        records[i].item_count = count
        keepalive.extend((attr_name_bytes, data_array))

    return records, keepalive


def _axis_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzAxisTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzAxisTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzAxisTicks
    ):
        return value
    return None


def _axis_ticks_arg(values, labels):
    raw_descriptor = _axis_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzAxisTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzAxisTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzAxisTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def _colorbar_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzColorbarTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzColorbarTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzColorbarTicks
    ):
        return value
    return None


def _colorbar_ticks_arg(values, labels):
    raw_descriptor = _colorbar_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzColorbarTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzColorbarTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzColorbarTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def dvz_view_capture_rgba(view):
    canvas = _raw.dvz_view_canvas(view)
    if not canvas:
        raise RuntimeError('dvz_view_capture_rgba failed: view has no canvas')

    width = ctypes.c_uint32()
    height = ctypes.c_uint32()
    _raw.dvz_view_framebuffer_size(view, ctypes.byref(width), ctypes.byref(height))
    if width.value == 0 or height.value == 0:
        raise RuntimeError('dvz_view_capture_rgba failed: view framebuffer size is zero')

    rgba = np.empty((height.value, width.value, 4), dtype=np.uint8)
    out = rgba.ctypes.data_as(ctypes.POINTER(ctypes.c_uint8))
    rc = _raw.dvz_canvas_capture_rgba_into(
        canvas, width.value, height.value, out, rgba.nbytes
    )
    if rc != 0:
        raise RuntimeError(f'dvz_view_capture_rgba failed with code {rc}')
    return rgba


def _sampled_field_layout(array, field_format, semantic, color_role, dim):
    if array.ndim == 2:
        inferred_dim = _raw.DVZ_FIELD_DIM_2D
        height, width = array.shape
        depth = 1
        channels = 1
        bytes_per_row = array.strides[0]
        rows_per_image = 0
    elif (
        array.ndim == 3
        and array.shape[2] in (1, 2, 4)
        and array.dtype == np.uint8
        and (dim in (None, _raw.DVZ_FIELD_DIM_2D))
    ):
        inferred_dim = _raw.DVZ_FIELD_DIM_2D
        height, width, channels = array.shape
        depth = 1
        bytes_per_row = array.strides[0]
        rows_per_image = 0
    elif array.ndim == 3:
        inferred_dim = _raw.DVZ_FIELD_DIM_3D
        depth, height, width = array.shape
        channels = 1
        bytes_per_row = array.strides[1]
        rows_per_image = height
    else:
        raise ValueError(
            'array must have shape (height, width), (height, width, channels), '
            'or (depth, height, width)'
        )

    if dim is not None and dim != inferred_dim:
        raise ValueError('dim override is incompatible with array shape')
    if width <= 0 or height <= 0 or depth <= 0:
        raise ValueError('array dimensions must be non-empty')

    if field_format is None:
        if channels == 4 and array.dtype == np.uint8:
            field_format = _raw.DVZ_FIELD_FORMAT_RGBA8_UNORM
        elif channels == 1 and array.dtype == np.uint8:
            field_format = _raw.DVZ_FIELD_FORMAT_R8_UNORM
        elif channels == 1 and array.dtype == np.uint32:
            field_format = _raw.DVZ_FIELD_FORMAT_R32_UINT
        elif channels == 1 and array.dtype == np.float32:
            field_format = _raw.DVZ_FIELD_FORMAT_R32_FLOAT
        else:
            raise ValueError(
                f'unsupported sampled-field dtype/shape: {array.dtype}, {array.shape}; '
                'pass format=... for an explicit field format'
            )

    if semantic is None:
        if field_format == _raw.DVZ_FIELD_FORMAT_RGBA8_UNORM:
            semantic = _raw.DVZ_FIELD_SEMANTIC_COLOR
        elif field_format == _raw.DVZ_FIELD_FORMAT_R32_UINT:
            semantic = _raw.DVZ_FIELD_SEMANTIC_LABEL
        else:
            semantic = _raw.DVZ_FIELD_SEMANTIC_SCALAR

    if color_role is None:
        if semantic == _raw.DVZ_FIELD_SEMANTIC_COLOR:
            color_role = _raw.DVZ_COLOR_ROLE_SRGB_COLOR
        elif semantic == _raw.DVZ_FIELD_SEMANTIC_SCALAR:
            color_role = _raw.DVZ_COLOR_ROLE_DATA
        else:
            color_role = _raw.DVZ_COLOR_ROLE_NONE

    return {
        'dim': inferred_dim,
        'format': field_format,
        'semantic': semantic,
        'color_role': color_role,
        'width': int(width),
        'height': int(height),
        'depth': int(depth),
        'bytes_per_row': int(bytes_per_row),
        'rows_per_image': int(rows_per_image),
    }


def dvz_sampled_field_from_array(
    scene,
    array,
    *,
    format=None,
    semantic=None,
    color_role=None,
    dim=None,
):
    """Create a scene-owned sampled field and upload a NumPy-compatible array.

    Supported inferred inputs are RGBA8 2D arrays shaped ``(height, width, 4)``,
    scalar 2D arrays shaped ``(height, width)``, and scalar 3D arrays shaped
    ``(depth, height, width)``. The payload is copied by Datoviz before return.
    """
    data = np.asarray(array)
    if data.ndim == 0:
        raise ValueError('array must be at least two-dimensional')
    if not data.flags.c_contiguous:
        data = np.ascontiguousarray(data)

    layout = _sampled_field_layout(data, format, semantic, color_role, dim)

    desc = _raw.dvz_sampled_field_desc()
    desc.dim = layout['dim']
    desc.format = layout['format']
    desc.semantic = layout['semantic']
    desc.color_role = layout['color_role']
    desc.width = layout['width']
    desc.height = layout['height']
    desc.depth = layout['depth']

    field = _raw.dvz_sampled_field(scene, ctypes.byref(desc))
    if not field:
        raise RuntimeError('dvz_sampled_field() failed')

    view = _raw.dvz_field_data_view()
    view.data = ctypes.c_void_p(data.ctypes.data)
    view.bytes_per_row = layout['bytes_per_row']
    view.rows_per_image = layout['rows_per_image']

    rc = _raw.dvz_sampled_field_set_data(field, ctypes.byref(view))
    if rc != 0:
        raise RuntimeError(f'dvz_sampled_field_set_data() failed with code {rc}')
    return field


def dvz_axis_set_ticks(axis, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _axis_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_axis_set_ticks(axis, _ticks_ptr)


dvz_axis_set_ticks.__doc__ = getattr(_raw.dvz_axis_set_ticks, "__doc__", None)
dvz_axis_set_ticks.argtypes = getattr(_raw.dvz_axis_set_ticks, "argtypes", None)
dvz_axis_set_ticks.restype = getattr(_raw.dvz_axis_set_ticks, "restype", None)


def dvz_colorbar_set_ticks(colorbar, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _colorbar_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_colorbar_set_ticks(colorbar, _ticks_ptr)


dvz_colorbar_set_ticks.__doc__ = getattr(_raw.dvz_colorbar_set_ticks, "__doc__", None)
dvz_colorbar_set_ticks.argtypes = getattr(_raw.dvz_colorbar_set_ticks, "argtypes", None)
dvz_colorbar_set_ticks.restype = getattr(_raw.dvz_colorbar_set_ticks, "restype", None)


def dvz_scene_buffer_set_data(buffer, data, byte_size=None):
    _data_ptr, _data_array = _array_arg(data, 'data', _raw.dvz_scene_buffer_set_data, 1, None)
    if byte_size is None:
        byte_size = _nbytes_size(_data_array, 'data')
    _keepalive = (_data_array,)
    return _raw.dvz_scene_buffer_set_data(buffer, _data_ptr, byte_size)


dvz_scene_buffer_set_data.__doc__ = getattr(_raw.dvz_scene_buffer_set_data, "__doc__", None)
dvz_scene_buffer_set_data.argtypes = getattr(_raw.dvz_scene_buffer_set_data, "argtypes", None)
dvz_scene_buffer_set_data.restype = getattr(_raw.dvz_scene_buffer_set_data, "restype", None)


def dvz_text_set_anchors(text, anchors, item_count=None):
    _anchors_ptr, _anchors_array = _array_arg(anchors, 'anchors', _raw.dvz_text_set_anchors, 1, 'float32')
    if item_count is None:
        item_count = _shape0_count(_anchors_array, 'anchors')
    _keepalive = (_anchors_array,)
    return _raw.dvz_text_set_anchors(text, _anchors_ptr, item_count)


dvz_text_set_anchors.__doc__ = getattr(_raw.dvz_text_set_anchors, "__doc__", None)
dvz_text_set_anchors.argtypes = getattr(_raw.dvz_text_set_anchors, "argtypes", None)
dvz_text_set_anchors.restype = getattr(_raw.dvz_text_set_anchors, "restype", None)


def dvz_text_set_angles(text, angles, item_count=None):
    _angles_ptr, _angles_array = _array_arg(angles, 'angles', _raw.dvz_text_set_angles, 1, 'float32')
    if item_count is None:
        item_count = _shape0_count(_angles_array, 'angles')
    _keepalive = (_angles_array,)
    return _raw.dvz_text_set_angles(text, _angles_ptr, item_count)


dvz_text_set_angles.__doc__ = getattr(_raw.dvz_text_set_angles, "__doc__", None)
dvz_text_set_angles.argtypes = getattr(_raw.dvz_text_set_angles, "argtypes", None)
dvz_text_set_angles.restype = getattr(_raw.dvz_text_set_angles, "restype", None)


def dvz_text_set_colors(text, colors, item_count=None):
    _colors_ptr, _colors_array = _array_arg(colors, 'colors', _raw.dvz_text_set_colors, 1, 'uint8')
    if item_count is None:
        item_count = _shape0_count(_colors_array, 'colors')
    _keepalive = (_colors_array,)
    return _raw.dvz_text_set_colors(text, _colors_ptr, item_count)


dvz_text_set_colors.__doc__ = getattr(_raw.dvz_text_set_colors, "__doc__", None)
dvz_text_set_colors.argtypes = getattr(_raw.dvz_text_set_colors, "argtypes", None)
dvz_text_set_colors.restype = getattr(_raw.dvz_text_set_colors, "restype", None)


def dvz_text_set_items(text, items, item_count=None):
    _items_ptr, _items_array = _array_arg(items, 'items', _raw.dvz_text_set_items, 1, None)
    if item_count is None:
        item_count = _shape0_count(_items_array, 'items')
    _keepalive = (_items_array,)
    return _raw.dvz_text_set_items(text, _items_ptr, item_count)


dvz_text_set_items.__doc__ = getattr(_raw.dvz_text_set_items, "__doc__", None)
dvz_text_set_items.argtypes = getattr(_raw.dvz_text_set_items, "argtypes", None)
dvz_text_set_items.restype = getattr(_raw.dvz_text_set_items, "restype", None)


def dvz_text_set_offsets(text, offsets, item_count=None):
    _offsets_ptr, _offsets_array = _array_arg(offsets, 'offsets', _raw.dvz_text_set_offsets, 1, 'float32')
    if item_count is None:
        item_count = _shape0_count(_offsets_array, 'offsets')
    _keepalive = (_offsets_array,)
    return _raw.dvz_text_set_offsets(text, _offsets_ptr, item_count)


dvz_text_set_offsets.__doc__ = getattr(_raw.dvz_text_set_offsets, "__doc__", None)
dvz_text_set_offsets.argtypes = getattr(_raw.dvz_text_set_offsets, "argtypes", None)
dvz_text_set_offsets.restype = getattr(_raw.dvz_text_set_offsets, "restype", None)


def dvz_text_set_positions(text, positions, item_count=None):
    _positions_ptr, _positions_array = _array_arg(positions, 'positions', _raw.dvz_text_set_positions, 1, 'float64')
    if item_count is None:
        item_count = _shape0_count(_positions_array, 'positions')
    _keepalive = (_positions_array,)
    return _raw.dvz_text_set_positions(text, _positions_ptr, item_count)


dvz_text_set_positions.__doc__ = getattr(_raw.dvz_text_set_positions, "__doc__", None)
dvz_text_set_positions.argtypes = getattr(_raw.dvz_text_set_positions, "argtypes", None)
dvz_text_set_positions.restype = getattr(_raw.dvz_text_set_positions, "restype", None)


def dvz_text_set_sizes(text, sizes_px, item_count=None):
    _sizes_px_ptr, _sizes_px_array = _array_arg(sizes_px, 'sizes_px', _raw.dvz_text_set_sizes, 1, 'float32')
    if item_count is None:
        item_count = _shape0_count(_sizes_px_array, 'sizes_px')
    _keepalive = (_sizes_px_array,)
    return _raw.dvz_text_set_sizes(text, _sizes_px_ptr, item_count)


dvz_text_set_sizes.__doc__ = getattr(_raw.dvz_text_set_sizes, "__doc__", None)
dvz_text_set_sizes.argtypes = getattr(_raw.dvz_text_set_sizes, "argtypes", None)
dvz_text_set_sizes.restype = getattr(_raw.dvz_text_set_sizes, "restype", None)


def dvz_view_window(app, figure, width, height, title):
    _title_bytes = _encode_string(title, 'title')
    _keepalive = (_title_bytes,)
    return _raw.dvz_view_window(app, figure, width, height, _title_bytes)


dvz_view_window.__doc__ = getattr(_raw.dvz_view_window, "__doc__", None)
dvz_view_window.argtypes = getattr(_raw.dvz_view_window, "argtypes", None)
dvz_view_window.restype = getattr(_raw.dvz_view_window, "restype", None)


def dvz_visual_set_data(visual, attr_name, data, item_count=None):
    _attr_name_bytes = _encode_string(attr_name, 'attr_name')
    _data_ptr, _data_array = _array_arg(data, 'data', _raw.dvz_visual_set_data, 2, None)
    if item_count is None:
        item_count = _shape0_count(_data_array, 'data')
    _keepalive = (_attr_name_bytes, _data_array,)
    return _raw.dvz_visual_set_data(visual, _attr_name_bytes, _data_ptr, item_count)


dvz_visual_set_data.__doc__ = getattr(_raw.dvz_visual_set_data, "__doc__", None)
dvz_visual_set_data.argtypes = getattr(_raw.dvz_visual_set_data, "argtypes", None)
dvz_visual_set_data.restype = getattr(_raw.dvz_visual_set_data, "restype", None)


def dvz_visual_set_data_many(visual, updates, update_count=None):
    if update_count is not None:
        return _raw.dvz_visual_set_data_many(visual, updates, update_count)
    if _raw_pointer(updates):
        raise TypeError('update_count must be provided when passing raw update descriptors')
    _updates_records, _updates_keepalive = _visual_data_updates_arg(updates)
    _keepalive = (_updates_records, _updates_keepalive,)
    return _raw.dvz_visual_set_data_many(visual, _updates_records, len(_updates_records))


dvz_visual_set_data_many.__doc__ = getattr(_raw.dvz_visual_set_data_many, "__doc__", None)
dvz_visual_set_data_many.argtypes = getattr(_raw.dvz_visual_set_data_many, "argtypes", None)
dvz_visual_set_data_many.restype = getattr(_raw.dvz_visual_set_data_many, "restype", None)


def dvz_visual_set_data_range(visual, attr_name, first_item, data, item_count=None):
    _attr_name_bytes = _encode_string(attr_name, 'attr_name')
    _data_ptr, _data_array = _array_arg(data, 'data', _raw.dvz_visual_set_data_range, 3, None)
    if item_count is None:
        item_count = _shape0_count(_data_array, 'data')
    _keepalive = (_attr_name_bytes, _data_array,)
    return _raw.dvz_visual_set_data_range(visual, _attr_name_bytes, first_item, _data_ptr, item_count)


dvz_visual_set_data_range.__doc__ = getattr(_raw.dvz_visual_set_data_range, "__doc__", None)
dvz_visual_set_data_range.argtypes = getattr(_raw.dvz_visual_set_data_range, "argtypes", None)
dvz_visual_set_data_range.restype = getattr(_raw.dvz_visual_set_data_range, "restype", None)


def dvz_visual_set_index_data(visual, indices, index_count=None):
    _indices_ptr, _indices_array = _array_arg(indices, 'indices', _raw.dvz_visual_set_index_data, 1, 'uint32')
    if index_count is None:
        index_count = _shape0_count(_indices_array, 'indices')
    _keepalive = (_indices_array,)
    return _raw.dvz_visual_set_index_data(visual, _indices_ptr, index_count)


dvz_visual_set_index_data.__doc__ = getattr(_raw.dvz_visual_set_index_data, "__doc__", None)
dvz_visual_set_index_data.argtypes = getattr(_raw.dvz_visual_set_index_data, "argtypes", None)
dvz_visual_set_index_data.restype = getattr(_raw.dvz_visual_set_index_data, "restype", None)


_ARRAY_FACADE_FUNCTIONS = ['dvz_axis_set_ticks', 'dvz_colorbar_set_ticks', 'dvz_scene_buffer_set_data', 'dvz_text_set_anchors', 'dvz_text_set_angles', 'dvz_text_set_colors', 'dvz_text_set_items', 'dvz_text_set_offsets', 'dvz_text_set_positions', 'dvz_text_set_sizes', 'dvz_view_window', 'dvz_visual_set_data', 'dvz_visual_set_data_many', 'dvz_visual_set_data_range', 'dvz_visual_set_index_data']

for _name in getattr(_raw, "__all__", dir(_raw)):
    if _name not in globals():
        globals()[_name] = getattr(_raw, _name)

__all__ = [name for name in globals() if name.startswith(('dvz_', 'Dvz', 'DVZ_'))]
