from pprint import pprint
import os
from pathlib import Path
import re

from skbuild import setup


ROOT_DIR = (Path(__file__).parent / '../../').resolve()


def _float(x):
    x = x.replace('f', '')
    try:
        return float(x)
    except ValueError:
        return


def _python(x):
    try:
        return eval(x)
    except Exception:
        return


def parse_constants():
    d = {}
    r1 = re.compile(r'(VKY_[A-Za-z0-9\_]+)\s+=\s+([^\n\,]+)')
    r2 = re.compile(
        r'#define\s(VKY_[A-Za-z0-9_]+)[ ]+([*A-Za-z0-9\.,_ +-/]+)\n')
    r3 = re.compile(
        r'#define\s(VKY_[^ ]+)\s+VKY_CONST[_INT]*\([A-Za-z0-9_]+\s*,\s*([*A-Za-z0-9\.,_ +-/]+)\)')

    fns = ('constants.h', 'scene.h', 'app.h', 'agg.h', 'colormaps.h')
    for fn in fns:
        path = Path(__file__).parent / '../../include/visky' / fn
        constants = path.read_text()
        for r in (r1, r2, r3):
            for m in r.finditer(constants):
                k, v = m.group(1), m.group(2)
                if v.isdigit():
                    v = int(v)
                elif _float(v) is not None:
                    v = _float(v)
                elif _python(v) is not None:
                    v = _python(v)
                elif 'true' in v or 'false' in v:
                    v = eval(v.capitalize())
                else:
                    v = f"'{v}'  # TODO"
                # TODO: handle VK_* header #define's
                d[k] = v
    # Write the Python constants.py file
    output = '# automatically-generated by setup.py -- DO NOT EDIT\n\n'
    output += '\n'.join(f'{k.replace("VKY_", "")} = {d[k]}' for k in sorted(d))
    output += '\n'
    (Path(__file__).parent / 'visky/_constants.py').write_text(output)


parse_constants()


setup(
    name='visky',
    version='0.0.0a0',
    description='Scientific visualization',
    author='Cyrille Rossant',
    author_email='rossant@users.noreply.github.com',
    url='https://visky.dev',
    long_description='''Scientific visualization''',
    packages=['visky'],
    cmake_args=[
        '-DVISKY_WITH_EXAMPLES=0',
    ],
    cmake_source_dir=ROOT_DIR,
)
