set(DVZ_CGLM_DIR "${DVZ_EXTERNAL_DIR}/cglm")
set(DVZ_CGLM_SOURCE_RESOLVED "OFF")

if(DVZ_CGLM_SOURCE STREQUAL "OFF")
    message(FATAL_ERROR "DVZ_CGLM_SOURCE=OFF is not supported: cglm is required by the active math stack.")
endif()

dvz_dependency_source_order(_dvz_cglm_sources "${DVZ_CGLM_SOURCE}")

foreach(_dvz_cglm_source IN LISTS _dvz_cglm_sources)
    if(DVZ_HAS_CGLM)
        break()
    endif()

    if(_dvz_cglm_source STREQUAL "SYSTEM")
        find_package(cglm CONFIG QUIET)

        if(TARGET cglm::cglm)
            add_library(dvz_cglm INTERFACE)
            target_link_libraries(dvz_cglm INTERFACE cglm::cglm)
            set(DVZ_HAS_CGLM 1)
            set(DVZ_CGLM_SOURCE_RESOLVED "SYSTEM")
        elseif(TARGET cglm)
            add_library(dvz_cglm INTERFACE)
            target_link_libraries(dvz_cglm INTERFACE cglm)
            set(DVZ_HAS_CGLM 1)
            set(DVZ_CGLM_SOURCE_RESOLVED "SYSTEM")
        endif()

        if(NOT DVZ_HAS_CGLM)
            find_package(PkgConfig QUIET)

            if(PkgConfig_FOUND)
                pkg_check_modules(CGLM QUIET IMPORTED_TARGET cglm)
            endif()

            if(TARGET PkgConfig::CGLM)
                add_library(dvz_cglm INTERFACE)
                target_link_libraries(dvz_cglm INTERFACE PkgConfig::CGLM)
                set(DVZ_HAS_CGLM 1)
                set(DVZ_CGLM_SOURCE_RESOLVED "SYSTEM")
            endif()
        endif()

        if(NOT DVZ_HAS_CGLM)
            find_path(DVZ_CGLM_INCLUDE_DIR NAMES cglm/cglm.h)

            if(DVZ_CGLM_INCLUDE_DIR)
                add_library(dvz_cglm INTERFACE)
                target_include_directories(dvz_cglm INTERFACE "${DVZ_CGLM_INCLUDE_DIR}")
                set(DVZ_HAS_CGLM 1)
                set(DVZ_CGLM_SOURCE_RESOLVED "SYSTEM")
            endif()
        endif()
    elseif(_dvz_cglm_source STREQUAL "VENDORED")
        if(EXISTS "${DVZ_CGLM_DIR}/include/cglm/cglm.h")
            add_library(dvz_cglm INTERFACE)
            target_include_directories(dvz_cglm INTERFACE "${DVZ_CGLM_DIR}/include")
            set(DVZ_HAS_CGLM 1)
            set(DVZ_CGLM_SOURCE_RESOLVED "VENDORED")
        endif()
    endif()
endforeach()

if(NOT DVZ_HAS_CGLM)
    if(DVZ_CGLM_SOURCE STREQUAL "SYSTEM")
        message(FATAL_ERROR "DVZ_CGLM_SOURCE=SYSTEM but system cglm was not found.")
    elseif(DVZ_CGLM_SOURCE STREQUAL "VENDORED")
        message(FATAL_ERROR "DVZ_CGLM_SOURCE=VENDORED but external/cglm is missing.")
    else()
        message(FATAL_ERROR "cglm was not found from system packages or external/cglm.")
    endif()
endif()

set(DVZ_HAS_CGLM "${DVZ_HAS_CGLM}" CACHE INTERNAL "cglm availability flag" FORCE)
set(DVZ_CGLM_SOURCE_RESOLVED "${DVZ_CGLM_SOURCE_RESOLVED}" CACHE INTERNAL "Resolved cglm source" FORCE)
