foreach(_dvz_source_var IN ITEMS DVZ_MIMALLOC_SOURCE DVZ_CGLM_SOURCE DVZ_KVAZAAR_SOURCE)
    string(TOUPPER "${${_dvz_source_var}}" _dvz_source_mode)
    if(NOT _dvz_source_mode MATCHES "^(AUTO|SYSTEM|VENDORED|OFF)$")
        message(FATAL_ERROR "${_dvz_source_var} must be AUTO, SYSTEM, VENDORED, or OFF")
    endif()
    set(${_dvz_source_var} "${_dvz_source_mode}" CACHE STRING "" FORCE)
endforeach()

function(dvz_dependency_source_order out_var mode)
    if(mode STREQUAL "AUTO")
        if(DVZ_VENDORED_DEPS)
            set(_order VENDORED SYSTEM)
        else()
            set(_order SYSTEM VENDORED)
        endif()
    else()
        set(_order "${mode}")
    endif()

    set(${out_var} "${_order}" PARENT_SCOPE)
endfunction()
