#!/usr/bin/env python3
"""Generate the raw Datoviz ctypes module from extracted API JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT_DIR / 'build' / 'bindings' / 'datoviz_api.json'
DEFAULT_OUTPUT = ROOT_DIR / 'datoviz' / '_ctypes.py'

HEADER = '''\
"""
Raw ctypes bindings for Datoviz v0.4.

This file is generated by tools/bindings/generate_ctypes.py. Do not edit it by hand.
"""

from __future__ import annotations

import ctypes
import os
import pathlib
import platform
from enum import IntEnum


class CtypesEnum(IntEnum):
    @classmethod
    def from_param(cls, obj):
        return int(obj)


_PLATFORM_LIB_NAMES = {
    'Linux': 'libdatoviz.so',
    'Darwin': 'libdatoviz.dylib',
    'Windows': 'libdatoviz.dll',
}


def _candidate_library_paths():
    env_path = os.environ.get('DATOVIZ_LIBRARY')
    if env_path:
        yield pathlib.Path(env_path)

    name = _PLATFORM_LIB_NAMES.get(platform.system())
    if not name:
        return

    here = pathlib.Path(__file__).resolve().parent
    root = here.parent
    yield here / name
    yield root / 'build' / 'src' / name
    yield root / 'build' / name


def _load_library():
    errors = []
    for path in _candidate_library_paths():
        if not path.exists():
            continue
        try:
            return ctypes.cdll.LoadLibrary(str(path))
        except OSError as exc:
            errors.append(f'{path}: {exc}')
    details = '; '.join(errors) if errors else 'no candidate file exists'
    raise RuntimeError(f'Unable to load libdatoviz ({details})')


dvz = _load_library()
_MISSING_FUNCTIONS = []

'''

CTYPE_MAP = {
    'void': 'None',
    'bool': 'ctypes.c_bool',
    '_Bool': 'ctypes.c_bool',
    'char': 'ctypes.c_char',
    'signed char': 'ctypes.c_int8',
    'unsigned char': 'ctypes.c_uint8',
    'int8_t': 'ctypes.c_int8',
    'uint8_t': 'ctypes.c_uint8',
    'int16_t': 'ctypes.c_int16',
    'uint16_t': 'ctypes.c_uint16',
    'int32_t': 'ctypes.c_int32',
    'uint32_t': 'ctypes.c_uint32',
    'int64_t': 'ctypes.c_int64',
    'uint64_t': 'ctypes.c_uint64',
    'int': 'ctypes.c_int',
    'unsigned int': 'ctypes.c_uint',
    'long': 'ctypes.c_long',
    'unsigned long': 'ctypes.c_ulong',
    'long long': 'ctypes.c_longlong',
    'unsigned long long': 'ctypes.c_ulonglong',
    'size_t': 'ctypes.c_size_t',
    'ssize_t': 'ctypes.c_ssize_t',
    'float': 'ctypes.c_float',
    'double': 'ctypes.c_double',
    'DvzId': 'ctypes.c_uint64',
    'DvzSize': 'ctypes.c_uint64',
}


def _clean_type(qualtype: str) -> str:
    out = ' '.join(qualtype.replace(' *', '*').replace('*', ' * ').split())
    return out.replace(' const', '').replace('const ', '')


def _class_name_for_pointer(qualtype: str, records: set[str]) -> str | None:
    t = _clean_type(qualtype)
    if not t.endswith('*'):
        return None
    target = t[:-1].strip()
    if target.startswith('struct '):
        target = target[len('struct ') :]
    if target.startswith('enum '):
        target = target[len('enum ') :]
    if target in records:
        return target
    return None


def _ctype_for(qualtype: str, records: set[str], enums: set[str]) -> str | None:
    t = _clean_type(qualtype)
    if t in CTYPE_MAP:
        return CTYPE_MAP[t]
    if t in enums:
        return 'ctypes.c_int'
    if t in records:
        return t
    if t in ('char *', 'const char *'):
        return 'ctypes.c_char_p'
    if t in ('void *', 'const void *'):
        return 'ctypes.c_void_p'
    cls = _class_name_for_pointer(t, records)
    if cls:
        return f'ctypes.POINTER({cls})'
    return None


def generate(api: dict) -> tuple[str, list[str]]:
    records = {record['name'] for record in api.get('records', []) if record.get('name')}
    enums = {enum['name'] for enum in api.get('enums', []) if enum.get('name')}
    lines = [HEADER]

    for enum in api.get('enums', []):
        name = enum.get('name')
        if not name:
            continue
        lines.append(f'class {name}(CtypesEnum):\n')
        values = [value for value in enum.get('values', []) if value.get('name')]
        if values:
            for value in values:
                lines.append(f"    {value['name']} = {value.get('value', 0)}\n")
        else:
            lines.append('    pass\n')
        lines.append('\n\n')

    for record in api.get('records', []):
        name = record.get('name')
        if not name:
            continue
        base = 'Union' if record.get('kind') == 'union' else 'Structure'
        lines.append(f'class {name}(ctypes.{base}):\n')
        lines.append('    pass\n\n\n')

    skipped = []
    emitted = []
    for function in api.get('functions', []):
        name = function['name']
        result = _ctype_for(function.get('result', {}).get('qualtype', 'void'), records, enums)
        argtypes = []
        for param in function.get('parameters', []):
            ctype = _ctype_for(param.get('type', {}).get('qualtype', ''), records, enums)
            if ctype is None:
                break
            argtypes.append(ctype)
        else:
            if result is None:
                skipped.append(name)
                continue
            lines.append('try:\n')
            lines.append(f'    {name} = dvz.{name}\n')
            lines.append('except AttributeError:\n')
            lines.append(f"    _MISSING_FUNCTIONS.append('{name}')\n")
            lines.append('else:\n')
            if function.get('doc'):
                doc = function['doc'].replace('"""', "'''")
                lines.append(f'    {name}.__doc__ = """{doc}"""\n')
            lines.append(f'    {name}.argtypes = [{", ".join(argtypes)}]\n')
            if result != 'None':
                lines.append(f'    {name}.restype = {result}\n')
            lines.append('\n\n')
            emitted.append(name)
            continue
        skipped.append(name)

    lines.append(f'_GENERATED_FUNCTION_COUNT = {len(emitted)}\n')
    lines.append(f'_SKIPPED_FUNCTIONS = {skipped!r}\n')
    lines.append("__all__ = [name for name in globals() if name.startswith(('dvz_', 'Dvz'))]\n")
    return ''.join(lines), skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, default=DEFAULT_INPUT)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--check', action='store_true', help='fail if the generated file is stale')
    args = parser.parse_args()

    with args.input.open() as f:
        api = json.load(f)
    text, skipped = generate(api)

    if args.check:
        current = args.output.read_text() if args.output.exists() else ''
        if current != text:
            raise SystemExit(f'{args.output} is stale; run `just ctypes`')
        print(f'{args.output} is up to date ({len(skipped)} skipped functions)')
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f'wrote {args.output} ({len(skipped)} skipped functions)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
