#!/usr/bin/env python3
"""Generate the array-aware Datoviz facade from API JSON and binding policy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT_DIR / 'build' / 'bindings' / 'datoviz_api.json'
DEFAULT_OUTPUT = ROOT_DIR / 'datoviz' / '_array_facade.py'
DEFAULT_POLICY = ROOT_DIR / 'spec' / 'bindings' / 'ctypes.yml'

HEADER = '''\
"""
Array-aware facade for the Datoviz v0.4 Python binding.

This file is generated by tools/bindings/generate_array_facade.py. Do not edit it by hand.
"""

from __future__ import annotations

import ctypes

import numpy as np

from . import raw as _raw


def _encode_string(value, name):
    if isinstance(value, str):
        return value.encode('utf-8')
    if isinstance(value, bytes) or value is None:
        return value
    raise TypeError(f'{name} must be str, bytes, or None')


def _raw_pointer(value):
    if isinstance(value, (int, ctypes.c_void_p, ctypes.Array, ctypes._Pointer)):
        return True
    if type(value).__name__ == 'CArgObject' and hasattr(value, '_obj'):
        return True
    return hasattr(value, '_as_parameter_')


def _array_arg(value, name, raw_func, pointer_index, dtype=None, shape_tail=None):
    if _raw_pointer(value):
        return value, None
    array = np.asarray(value)
    if dtype is not None:
        expected = np.dtype(dtype)
        if array.dtype != expected:
            raise ValueError(f'{name} must have dtype {expected}, got {array.dtype}')
    if array.ndim == 0:
        raise ValueError(f'{name} must be at least one-dimensional')
    if shape_tail is not None and tuple(array.shape[1:]) != tuple(shape_tail):
        raise ValueError(f'{name} must have shape (n, {", ".join(map(str, shape_tail))})')
    if not array.flags.c_contiguous:
        array = np.ascontiguousarray(array)
    pointer = ctypes.c_void_p(array.ctypes.data)
    target = None
    argtypes = getattr(raw_func, 'argtypes', None)
    if argtypes is not None and pointer_index < len(argtypes):
        target = argtypes[pointer_index]
    if target is not None and target is not ctypes.c_void_p:
        pointer = ctypes.cast(pointer, target)
    return pointer, array


def _typed_sequence(value, dtype):
    if _raw_pointer(value) or isinstance(value, np.ndarray):
        return value
    array = np.asarray(value)
    expected = np.dtype(dtype)
    if expected.kind in 'ui':
        if array.dtype.kind not in 'ui':
            raise ValueError(f'values must contain integers for dtype {expected}')
        if array.size:
            limits = np.iinfo(expected)
            if array.min() < limits.min or array.max() > limits.max:
                raise ValueError(f'values are outside the range of dtype {expected}')
    return np.asarray(value, dtype=expected)


def _shape0_count(array, name):
    if array is None:
        raise TypeError(f'{name} count must be provided when passing a raw pointer')
    return int(array.shape[0])


def _nbytes_size(array, name):
    if array is None:
        raise TypeError(f'{name} byte size must be provided when passing a raw pointer')
    return int(array.nbytes)


def _gui_strings(value, name, count=None, optional=False):
    if value is None and optional:
        return None, ()
    if _raw_pointer(value):
        if count is None:
            raise TypeError(f'{name} count must be provided when passing a raw pointer')
        return value, (value,)
    try:
        items = list(value)
    except TypeError as exc:
        raise TypeError(f'{name} must be a sequence of strings') from exc
    if count is not None and len(items) != int(count):
        raise ValueError(f'{name} length {len(items)} does not match row count {count}')
    encoded = [_encode_string(item, f'{name}[{i}]') for i, item in enumerate(items)]
    array = (ctypes.c_char_p * len(encoded))(*encoded) if encoded else None
    return array, (array, encoded)


def _gui_array(value, name, target, dtype=None, count=None, optional=False, shape_tail=None):
    if value is None and optional:
        return None, ()
    if _raw_pointer(value):
        if count is None:
            raise TypeError(f'{name} count must be provided when passing a raw pointer')
        return value, (value,)
    array = np.asarray(value)
    if dtype is not None and array.dtype != np.dtype(dtype):
        raise ValueError(f'{name} must have dtype {np.dtype(dtype)}, got {array.dtype}')
    if array.ndim == 0:
        raise ValueError(f'{name} must be at least one-dimensional')
    if shape_tail is not None and tuple(array.shape[1:]) != tuple(shape_tail):
        raise ValueError(f'{name} must have shape (n, {", ".join(map(str, shape_tail))})')
    if count is not None and array.shape[0] != int(count):
        raise ValueError(f'{name} length {array.shape[0]} does not match row count {count}')
    if not array.flags.c_contiguous:
        array = np.ascontiguousarray(array)
    pointer = ctypes.c_void_p(array.ctypes.data)
    if target is not ctypes.c_void_p:
        pointer = ctypes.cast(pointer, target)
    return pointer, (array,)


def _gui_records(value, record_type, name, count=None):
    if _raw_pointer(value):
        if count is None:
            raise TypeError(f'{name} count must be provided when passing a raw pointer')
        return value, (value,)
    items = list(value)
    if count is not None and len(items) != int(count):
        raise ValueError(f'{name} length {len(items)} does not match expected count {count}')
    records = (record_type * len(items))()
    for i, item in enumerate(items):
        if not isinstance(item, record_type):
            raise TypeError(f'{name}[{i}] must be {record_type.__name__}')
        records[i] = item
    return records, (records,)


def _gui_draw(raw_func, gui, widget, events, capacity):
    if events is None:
        if capacity is None:
            capacity = 64
        if int(capacity) < 0:
            raise ValueError('capacity must be non-negative')
        events = (_raw.DvzGuiDataEvent * int(capacity))()
    elif isinstance(events, ctypes.Array):
        capacity = len(events)
    elif _raw_pointer(events):
        if capacity is None:
            raise TypeError('capacity must be provided for a raw event pointer')
    else:
        raise TypeError('events must be omitted, a ctypes array, or a raw pointer')
    written = ctypes.c_uint32()
    dropped = ctypes.c_uint32()
    result = raw_func(gui, widget, events, int(capacity), ctypes.byref(written), ctypes.byref(dropped))
    return result, [events[i] for i in range(min(written.value, int(capacity)))], dropped.value


def _visual_data_updates_arg(updates):
    if isinstance(updates, dict):
        items = list(updates.items())
    else:
        try:
            items = list(updates)
        except TypeError as exc:
            raise TypeError('updates must be a mapping or iterable of (attr_name, data) pairs') from exc
    if not items:
        raise ValueError('updates must not be empty')

    records = (_raw.DvzVisualDataUpdate * len(items))()
    keepalive = []
    item_count = None

    for i, item in enumerate(items):
        try:
            attr_name, data = item
        except (TypeError, ValueError) as exc:
            raise TypeError('updates must contain (attr_name, data) pairs') from exc

        attr_name_bytes = _encode_string(attr_name, f'updates[{i}].attr_name')
        data_array = np.asarray(data)
        if data_array.ndim == 0:
            raise ValueError(f'updates[{attr_name!r}] data must be at least one-dimensional')
        if not data_array.flags.c_contiguous:
            data_array = np.ascontiguousarray(data_array)
        count = int(data_array.shape[0])
        if item_count is None:
            item_count = count
        elif count != item_count:
            raise ValueError(
                f'updates[{attr_name!r}] item count {count} does not match expected {item_count}'
            )

        records[i].attr_name = attr_name_bytes
        records[i].data = ctypes.c_void_p(data_array.ctypes.data)
        records[i].item_count = count
        keepalive.extend((attr_name_bytes, data_array))

    return records, keepalive


def _axis_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzAxisTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzAxisTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzAxisTicks
    ):
        return value
    return None


def _axis_ticks_arg(values, labels):
    raw_descriptor = _axis_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzAxisTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzAxisTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzAxisTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def _colorbar_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzColorbarTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzColorbarTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzColorbarTicks
    ):
        return value
    return None


def _colorbar_ticks_arg(values, labels):
    raw_descriptor = _colorbar_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzColorbarTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzColorbarTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzColorbarTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def dvz_view_capture_rgba(view):
    canvas = _raw.dvz_view_canvas(view)
    if not canvas:
        raise RuntimeError('dvz_view_capture_rgba failed: view has no canvas')

    width = ctypes.c_uint32()
    height = ctypes.c_uint32()
    _raw.dvz_view_framebuffer_size(view, ctypes.byref(width), ctypes.byref(height))
    if width.value == 0 or height.value == 0:
        raise RuntimeError('dvz_view_capture_rgba failed: view framebuffer size is zero')

    rgba = np.empty((height.value, width.value, 4), dtype=np.uint8)
    out = rgba.ctypes.data_as(ctypes.POINTER(ctypes.c_uint8))
    rc = _raw.dvz_canvas_capture_rgba_into(
        canvas, width.value, height.value, out, rgba.nbytes
    )
    if rc != 0:
        raise RuntimeError(f'dvz_view_capture_rgba failed with code {rc}')
    return rgba


def _sampled_field_layout(array, field_format, semantic, color_role, dim):
    if array.ndim == 2:
        inferred_dim = _raw.DVZ_FIELD_DIM_2D
        height, width = array.shape
        depth = 1
        channels = 1
        bytes_per_row = array.strides[0]
        rows_per_image = 0
    elif (
        array.ndim == 3
        and array.shape[2] in (1, 2, 4)
        and array.dtype == np.uint8
        and (dim in (None, _raw.DVZ_FIELD_DIM_2D))
    ):
        inferred_dim = _raw.DVZ_FIELD_DIM_2D
        height, width, channels = array.shape
        depth = 1
        bytes_per_row = array.strides[0]
        rows_per_image = 0
    elif array.ndim == 3:
        inferred_dim = _raw.DVZ_FIELD_DIM_3D
        depth, height, width = array.shape
        channels = 1
        bytes_per_row = array.strides[1]
        rows_per_image = height
    else:
        raise ValueError(
            'array must have shape (height, width), (height, width, channels), '
            'or (depth, height, width)'
        )

    if dim is not None and dim != inferred_dim:
        raise ValueError('dim override is incompatible with array shape')
    if width <= 0 or height <= 0 or depth <= 0:
        raise ValueError('array dimensions must be non-empty')

    if field_format is None:
        if channels == 4 and array.dtype == np.uint8:
            field_format = _raw.DVZ_FIELD_FORMAT_RGBA8_UNORM
        elif channels == 1 and array.dtype == np.uint8:
            field_format = _raw.DVZ_FIELD_FORMAT_R8_UNORM
        elif channels == 1 and array.dtype == np.uint32:
            field_format = _raw.DVZ_FIELD_FORMAT_R32_UINT
        elif channels == 1 and array.dtype == np.float32:
            field_format = _raw.DVZ_FIELD_FORMAT_R32_FLOAT
        else:
            raise ValueError(
                f'unsupported sampled-field dtype/shape: {array.dtype}, {array.shape}; '
                'pass format=... for an explicit field format'
            )

    if semantic is None:
        if field_format == _raw.DVZ_FIELD_FORMAT_RGBA8_UNORM:
            semantic = _raw.DVZ_FIELD_SEMANTIC_COLOR
        elif field_format == _raw.DVZ_FIELD_FORMAT_R32_UINT:
            semantic = _raw.DVZ_FIELD_SEMANTIC_LABEL
        else:
            semantic = _raw.DVZ_FIELD_SEMANTIC_SCALAR

    if color_role is None:
        if semantic == _raw.DVZ_FIELD_SEMANTIC_COLOR:
            color_role = _raw.DVZ_COLOR_ROLE_SRGB_COLOR
        elif semantic == _raw.DVZ_FIELD_SEMANTIC_SCALAR:
            color_role = _raw.DVZ_COLOR_ROLE_DATA
        else:
            color_role = _raw.DVZ_COLOR_ROLE_NONE

    return {
        'dim': inferred_dim,
        'format': field_format,
        'semantic': semantic,
        'color_role': color_role,
        'width': int(width),
        'height': int(height),
        'depth': int(depth),
        'bytes_per_row': int(bytes_per_row),
        'rows_per_image': int(rows_per_image),
    }


def dvz_sampled_field_from_array(
    scene,
    array,
    *,
    format=None,
    semantic=None,
    color_role=None,
    dim=None,
):
    """Create a scene-owned sampled field and upload a NumPy-compatible array.

    Supported inferred inputs are RGBA8 2D arrays shaped ``(height, width, 4)``,
    scalar 2D arrays shaped ``(height, width)``, and scalar 3D arrays shaped
    ``(depth, height, width)``. The payload is copied by Datoviz before return.
    """
    data = np.asarray(array)
    if data.ndim == 0:
        raise ValueError('array must be at least two-dimensional')
    if not data.flags.c_contiguous:
        data = np.ascontiguousarray(data)

    layout = _sampled_field_layout(data, format, semantic, color_role, dim)

    desc = _raw.dvz_sampled_field_desc()
    desc.dim = layout['dim']
    desc.format = layout['format']
    desc.semantic = layout['semantic']
    desc.color_role = layout['color_role']
    desc.width = layout['width']
    desc.height = layout['height']
    desc.depth = layout['depth']

    field = _raw.dvz_sampled_field(scene, ctypes.byref(desc))
    if not field:
        raise RuntimeError('dvz_sampled_field() failed')

    view = _raw.dvz_field_data_view()
    view.data = ctypes.c_void_p(data.ctypes.data)
    view.bytes_per_row = layout['bytes_per_row']
    view.rows_per_image = layout['rows_per_image']

    rc = _raw.dvz_sampled_field_set_data(field, ctypes.byref(view))
    if rc != 0:
        raise RuntimeError(f'dvz_sampled_field_set_data() failed with code {rc}')
    return field


def _field_region_tuple(value, name, *, default_z=None):
    if value is None:
        raise ValueError(f'{name} must not be None')
    items = tuple(int(v) for v in value)
    if len(items) == 2 and default_z is not None:
        items = (items[0], items[1], default_z)
    if len(items) != 3:
        raise ValueError(f'{name} must contain 2 or 3 values')
    return items


def dvz_sampled_field_update_from_array(
    field,
    array,
    *,
    offset=(0, 0, 0),
    extent=None,
    format=None,
    semantic=None,
    color_role=None,
    dim=None,
):
    """Update a sampled-field subregion from a NumPy-compatible patch array.

    The patch array uses the same inferred layouts as ``dvz_sampled_field_from_array``.
    ``offset`` is expressed in sample coordinates as ``(x, y)`` or ``(x, y, z)``.
    When provided, ``extent`` must match the array-derived ``(width, height, depth)``.
    The payload is copied by Datoviz before return.
    """
    data = np.asarray(array)
    if data.ndim == 0:
        raise ValueError('array must be at least two-dimensional')
    if not data.flags.c_contiguous:
        data = np.ascontiguousarray(data)

    layout = _sampled_field_layout(data, format, semantic, color_role, dim)
    region_extent = (layout['width'], layout['height'], layout['depth'])
    if extent is not None:
        explicit_extent = _field_region_tuple(extent, 'extent', default_z=1)
        if explicit_extent != region_extent:
            raise ValueError(
                f'extent {explicit_extent} does not match array-derived extent {region_extent}'
            )

    x, y, z = _field_region_tuple(offset, 'offset', default_z=0)
    if x < 0 or y < 0 or z < 0:
        raise ValueError('offset values must be non-negative')

    region = _raw.DvzFieldRegion()
    region.x = x
    region.y = y
    region.z = z
    region.width = region_extent[0]
    region.height = region_extent[1]
    region.depth = region_extent[2]

    view = _raw.dvz_field_data_view()
    view.data = ctypes.c_void_p(data.ctypes.data)
    view.bytes_per_row = layout['bytes_per_row']
    view.rows_per_image = layout['rows_per_image']

    rc = _raw.dvz_sampled_field_update_region(field, region, ctypes.byref(view))
    if rc != 0:
        raise RuntimeError(f'dvz_sampled_field_update_region() failed with code {rc}')
    return field


'''


def _load_policy(path: Path) -> dict:
    try:
        import yaml  # type: ignore

        with path.open(encoding='utf8') as f:
            policy = yaml.safe_load(f) or {}
        facade = policy.get('array_facade', {})
    except ModuleNotFoundError:
        facade = _array_facade_policy_fallback(path)
    if not isinstance(facade, dict):
        raise SystemExit('array_facade policy must be a mapping')
    return facade


def _array_facade_policy_fallback(path: Path) -> dict:
    facade: dict[str, dict] = {}
    current_function: str | None = None
    current_section: str | None = None
    current_group: dict | None = None
    in_facade = False

    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        indent = len(line) - len(line.lstrip(' '))
        if stripped == 'array_facade:':
            in_facade = True
            current_function = None
            current_section = None
            current_group = None
            continue
        if not in_facade:
            continue
        if indent == 0 and stripped != 'array_facade:':
            break
        if indent == 2 and stripped.endswith(':'):
            current_function = stripped[:-1]
            facade[current_function] = {}
            current_section = None
            current_group = None
            continue
        if current_function is None:
            continue
        if indent == 4 and stripped.endswith(':'):
            current_section = stripped[:-1]
            if current_section == 'strings':
                facade[current_function][current_section] = []
            elif current_section == 'groups':
                facade[current_function][current_section] = []
            current_group = None
            continue
        if indent == 4 and ':' in stripped and current_section is None:
            key, value = stripped.split(':', 1)
            facade[current_function][key.strip()] = value.strip()
            continue
        if current_section == 'strings' and indent == 6 and stripped.startswith('- '):
            facade[current_function]['strings'].append(stripped[2:].strip())
            continue
        if current_section == 'groups' and indent == 6 and stripped.startswith('- '):
            current_group = {}
            facade[current_function]['groups'].append(current_group)
            key, value = stripped[2:].split(':', 1)
            current_group[key.strip()] = value.strip()
            continue
        if current_section == 'groups' and current_group is not None and indent == 8:
            key, value = stripped.split(':', 1)
            current_group[key.strip()] = value.strip()
    return facade


def _functions_by_name(api: dict) -> dict[str, dict]:
    return {
        function['name']: function
        for function in api.get('functions', [])
        if isinstance(function, dict) and function.get('name')
    }


def _validate_policy(api: dict, policy: dict) -> None:
    functions = _functions_by_name(api)
    for function_name, rules in policy.items():
        if function_name not in functions:
            raise SystemExit(f'array_facade policy references unknown function {function_name}')
        if not isinstance(rules, dict):
            raise SystemExit(f'array_facade.{function_name} must be a mapping')
        params = {
            param.get('name')
            for param in functions[function_name].get('parameters', [])
            if param.get('name')
        }
        for string_arg in rules.get('strings', []) or []:
            if string_arg not in params:
                raise SystemExit(
                    f'array_facade.{function_name} references unknown string arg {string_arg}'
                )
        for group in rules.get('groups', []) or []:
            for key in ('pointer_arg',):
                if group.get(key) not in params:
                    raise SystemExit(
                        f'array_facade.{function_name} references unknown {key} {group.get(key)}'
                    )
            count_arg = group.get('count_arg')
            size_arg = group.get('size_arg')
            if bool(count_arg) == bool(size_arg):
                raise SystemExit(
                    f'array_facade.{function_name} group must define exactly one count_arg or size_arg'
                )
            if count_arg and count_arg not in params:
                raise SystemExit(
                    f'array_facade.{function_name} references unknown count_arg {count_arg}'
                )
            if size_arg and size_arg not in params:
                raise SystemExit(
                    f'array_facade.{function_name} references unknown size_arg {size_arg}'
                )
            if group.get('lifetime') != 'copied_before_return':
                raise SystemExit(
                    f'array_facade.{function_name} group lifetime must be copied_before_return'
                )
        special = rules.get('special')
        if special is not None and special not in {
            'visual_data_updates',
            'axis_ticks',
            'colorbar_ticks',
            'gui_tree_set_rows', 'gui_tree_set_swatches', 'gui_tree_set_styles',
            'gui_tree_set_selection', 'gui_tree_set_expanded', 'gui_tree_set_visible',
            'gui_tree_set_matches', 'gui_tree_draw', 'gui_table', 'gui_table_set_rows',
            'gui_table_set_column_text', 'gui_table_set_column_int64',
            'gui_table_set_column_double', 'gui_table_set_column_bool',
            'gui_table_set_column_color', 'gui_table_set_styles',
            'gui_table_set_selection', 'gui_table_set_visible', 'gui_table_set_matches',
            'gui_table_draw', 'gui_tree_get_selection', 'gui_tree_get_expanded',
            'gui_tree_get_filter', 'gui_table_get_selection', 'gui_table_get_filter',
            'gui_table_get_sort',
            'path_subpaths', 'text_strings', 'visual_link_keys', 'visual_target_link_keys',
            'colormap_custom',
            'panel_set_lights',
        }:
            raise SystemExit(f'array_facade.{function_name} has unknown special wrapper {special}')


def _signature(function: dict, rules: dict) -> tuple[list[str], set[str]]:
    group_targets = set()
    for group in rules.get('groups', []) or []:
        group_targets.add(group.get('count_arg') or group.get('size_arg'))
    params = [
        param.get('name') or f'arg{i}'
        for i, param in enumerate(function.get('parameters', []))
    ]
    signature = [f'{name}=None' if name in group_targets else name for name in params]
    return signature, group_targets


def _emit_wrapper(function: dict, rules: dict) -> str:
    name = function['name']
    gui_special = rules.get('special')
    gui_specials = {
        'gui_tree_set_rows', 'gui_tree_set_swatches', 'gui_tree_set_styles',
        'gui_tree_set_selection', 'gui_tree_set_expanded', 'gui_tree_set_visible',
        'gui_tree_set_matches', 'gui_tree_draw', 'gui_table', 'gui_table_set_rows',
        'gui_table_set_column_text', 'gui_table_set_column_int64',
        'gui_table_set_column_double', 'gui_table_set_column_bool',
        'gui_table_set_column_color', 'gui_table_set_styles',
        'gui_table_set_selection', 'gui_table_set_visible', 'gui_table_set_matches',
        'gui_table_draw', 'gui_tree_get_selection', 'gui_tree_get_expanded',
        'gui_tree_get_filter', 'gui_table_get_selection', 'gui_table_get_filter',
        'gui_table_get_sort',
        'path_subpaths', 'text_strings', 'visual_link_keys', 'visual_target_link_keys',
        'colormap_custom',
        'panel_set_lights',
    }
    if gui_special in gui_specials:
        if gui_special == 'path_subpaths':
            return '''\
def dvz_path_set_subpaths(visual, subpath_count, lengths=None):
    if lengths is None and not _raw_pointer(subpath_count):
        lengths = subpath_count
        subpath_count = len(lengths)
    lengths = _typed_sequence(lengths, np.uint32)
    ptr, keepalive = _array_arg(lengths, 'lengths', _raw.dvz_path_set_subpaths, 2, np.uint32)
    if keepalive is not None and len(lengths) != int(subpath_count):
        raise ValueError(f'lengths count {len(lengths)} does not match subpath_count {subpath_count}')
    return _raw.dvz_path_set_subpaths(visual, int(subpath_count), ptr)


dvz_path_set_subpaths.__doc__ = getattr(_raw.dvz_path_set_subpaths, "__doc__", None)
dvz_path_set_subpaths.argtypes = getattr(_raw.dvz_path_set_subpaths, "argtypes", None)
dvz_path_set_subpaths.restype = getattr(_raw.dvz_path_set_subpaths, "restype", None)


'''
        if gui_special == 'text_strings':
            return '''\
def dvz_text_set_strings(text, strings, item_count=None):
    ptr, keepalive = _gui_strings(strings, 'strings', item_count)
    if item_count is None and not _raw_pointer(strings):
        item_count = len(strings)
    return _raw.dvz_text_set_strings(text, ptr, int(item_count or 0))


dvz_text_set_strings.__doc__ = getattr(_raw.dvz_text_set_strings, "__doc__", None)
dvz_text_set_strings.argtypes = getattr(_raw.dvz_text_set_strings, "argtypes", None)
dvz_text_set_strings.restype = getattr(_raw.dvz_text_set_strings, "restype", None)


'''
        if gui_special == 'visual_link_keys':
            return '''\
def dvz_visual_set_link_keys(visual, channel, link_keys, item_count=None):
    link_keys = _typed_sequence(link_keys, np.uint64)
    ptr, keepalive = _array_arg(link_keys, 'link_keys', _raw.dvz_visual_set_link_keys, 2, np.uint64)
    if keepalive is not None:
        if item_count is None:
            item_count = len(link_keys)
        elif len(link_keys) != int(item_count):
            raise ValueError(f'link_keys count {len(link_keys)} does not match item_count {item_count}')
    elif item_count is None:
        raise TypeError('item_count must be provided when passing a raw link_keys pointer')
    return _raw.dvz_visual_set_link_keys(visual, channel, ptr, int(item_count or 0))


dvz_visual_set_link_keys.__doc__ = getattr(_raw.dvz_visual_set_link_keys, "__doc__", None)
dvz_visual_set_link_keys.argtypes = getattr(_raw.dvz_visual_set_link_keys, "argtypes", None)
dvz_visual_set_link_keys.restype = getattr(_raw.dvz_visual_set_link_keys, "restype", None)


'''
        if gui_special == 'visual_target_link_keys':
            return '''\
def dvz_visual_set_target_link_keys(visual, target, channel, link_keys, target_count=None):
    link_keys = _typed_sequence(link_keys, np.uint64)
    ptr, keepalive = _array_arg(
        link_keys, 'link_keys', _raw.dvz_visual_set_target_link_keys, 3, np.uint64)
    if keepalive is not None:
        if target_count is None:
            target_count = len(link_keys)
        elif len(link_keys) != int(target_count):
            raise ValueError(
                f'link_keys count {len(link_keys)} does not match target_count {target_count}')
    elif target_count is None:
        raise TypeError('target_count must be provided when passing a raw link_keys pointer')
    return _raw.dvz_visual_set_target_link_keys(
        visual, target, channel, ptr, int(target_count or 0))


dvz_visual_set_target_link_keys.__doc__ = getattr(
    _raw.dvz_visual_set_target_link_keys, "__doc__", None)
dvz_visual_set_target_link_keys.argtypes = getattr(
    _raw.dvz_visual_set_target_link_keys, "argtypes", None)
dvz_visual_set_target_link_keys.restype = getattr(
    _raw.dvz_visual_set_target_link_keys, "restype", None)


'''
        if gui_special == 'colormap_custom':
            return '''\
def dvz_colormap_custom(scene, label, colors, count=None):
    label_bytes = _encode_string(label, 'label')
    colors = _typed_sequence(colors, np.uint8)
    ptr, keepalive = _array_arg(colors, 'colors', _raw.dvz_colormap_custom, 2, np.uint8, (4,))
    if keepalive is not None:
        if count is None:
            count = len(colors)
        elif len(colors) != int(count):
            raise ValueError(f'colors count {len(colors)} does not match count {count}')
    elif count is None:
        raise TypeError('count must be provided when passing a raw colors pointer')
    return _raw.dvz_colormap_custom(scene, label_bytes, ptr, int(count or 0))


dvz_colormap_custom.__doc__ = getattr(_raw.dvz_colormap_custom, "__doc__", None)
dvz_colormap_custom.argtypes = getattr(_raw.dvz_colormap_custom, "argtypes", None)
dvz_colormap_custom.restype = getattr(_raw.dvz_colormap_custom, "restype", None)


'''
        if gui_special == 'panel_set_lights':
            return '''\
def dvz_panel_set_lights(panel, lights, count=None):
    if _raw_pointer(lights):
        if count is None:
            raise TypeError('count must be provided when passing a raw light pointer')
        ptr = lights
    else:
        items = list(lights)
        if count is not None and len(items) != int(count):
            raise ValueError(f'lights length {len(items)} does not match count {count}')
        count = len(items)
        target = _raw.dvz_panel_set_lights.argtypes[1]._type_
        ptr = (target * count)(*items) if count else None
    return _raw.dvz_panel_set_lights(panel, ptr, int(count or 0))


dvz_panel_set_lights.__doc__ = getattr(_raw.dvz_panel_set_lights, "__doc__", None)
dvz_panel_set_lights.argtypes = getattr(_raw.dvz_panel_set_lights, "argtypes", None)
dvz_panel_set_lights.restype = getattr(_raw.dvz_panel_set_lights, "restype", None)


'''
        return _emit_gui_wrapper(gui_special)
    if name == 'dvz_visual_set_data_many':
        return '''\
def dvz_visual_set_data_many(visual, updates, update_count=None):
    if update_count is not None:
        return _raw.dvz_visual_set_data_many(visual, updates, update_count)
    if _raw_pointer(updates):
        raise TypeError('update_count must be provided when passing raw update descriptors')
    _updates_records, _updates_keepalive = _visual_data_updates_arg(updates)
    _keepalive = (_updates_records, _updates_keepalive,)
    return _raw.dvz_visual_set_data_many(visual, _updates_records, len(_updates_records))


dvz_visual_set_data_many.__doc__ = getattr(_raw.dvz_visual_set_data_many, "__doc__", None)
dvz_visual_set_data_many.argtypes = getattr(_raw.dvz_visual_set_data_many, "argtypes", None)
dvz_visual_set_data_many.restype = getattr(_raw.dvz_visual_set_data_many, "restype", None)


'''
    if name == 'dvz_axis_set_ticks':
        return '''\
def dvz_axis_set_ticks(axis, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _axis_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_axis_set_ticks(axis, _ticks_ptr)


dvz_axis_set_ticks.__doc__ = getattr(_raw.dvz_axis_set_ticks, "__doc__", None)
dvz_axis_set_ticks.argtypes = getattr(_raw.dvz_axis_set_ticks, "argtypes", None)
dvz_axis_set_ticks.restype = getattr(_raw.dvz_axis_set_ticks, "restype", None)


'''
    if name == 'dvz_colorbar_set_ticks':
        return '''\
def dvz_colorbar_set_ticks(colorbar, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _colorbar_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_colorbar_set_ticks(colorbar, _ticks_ptr)


dvz_colorbar_set_ticks.__doc__ = getattr(_raw.dvz_colorbar_set_ticks, "__doc__", None)
dvz_colorbar_set_ticks.argtypes = getattr(_raw.dvz_colorbar_set_ticks, "argtypes", None)
dvz_colorbar_set_ticks.restype = getattr(_raw.dvz_colorbar_set_ticks, "restype", None)


'''
    params = [param.get('name') or f'arg{i}' for i, param in enumerate(function.get('parameters', []))]
    param_index = {param: i for i, param in enumerate(params)}
    signature, inferred_targets = _signature(function, rules)
    lines = [f'def {name}({", ".join(signature)}):\n']
    call_args = {param: param for param in params}
    keepalive_names = []

    for string_arg in rules.get('strings', []) or []:
        local_name = f'_{string_arg}_bytes'
        lines.append(f"    {local_name} = _encode_string({string_arg}, '{string_arg}')\n")
        call_args[string_arg] = local_name
        keepalive_names.append(local_name)

    for group_idx, group in enumerate(rules.get('groups', []) or []):
        pointer_arg = group['pointer_arg']
        pointer_local = f'_{pointer_arg}_ptr'
        array_local = f'_{pointer_arg}_array'
        dtype = group.get('dtype')
        shape_tail = group.get('shape_tail')
        dtype_arg = repr(dtype) if dtype else 'None'
        lines.append(
            f"    {pointer_local}, {array_local} = _array_arg("
            f"{pointer_arg}, '{pointer_arg}', _raw.{name}, {param_index[pointer_arg]}, {dtype_arg}, {shape_tail!r})\n"
        )
        call_args[pointer_arg] = pointer_local
        keepalive_names.append(array_local)

        count_arg = group.get('count_arg')
        size_arg = group.get('size_arg')
        if count_arg:
            if group.get('count_from') != 'shape0':
                raise SystemExit(f'array_facade.{name} only supports count_from: shape0')
            count_local = f'_{pointer_arg}_count'
            lines.append(f'    if {array_local} is not None:\n')
            lines.append(f"        {count_local} = _shape0_count({array_local}, '{pointer_arg}')\n")
            lines.append(f'        if {count_arg} is None:\n')
            lines.append(f'            {count_arg} = {count_local}\n')
            lines.append(f'        elif {count_local} != int({count_arg}):\n')
            lines.append(
                f"            raise ValueError(f'{pointer_arg} count {{{count_local}}} does not "
                f"match {count_arg} {{{count_arg}}}')\n"
            )
            lines.append(f'    elif {count_arg} is None:\n')
            lines.append(f"        {count_arg} = _shape0_count({array_local}, '{pointer_arg}')\n")
        elif size_arg:
            if group.get('size_from') != 'nbytes':
                raise SystemExit(f'array_facade.{name} only supports size_from: nbytes')
            size_local = f'_{pointer_arg}_size'
            lines.append(f'    if {array_local} is not None:\n')
            lines.append(f"        {size_local} = _nbytes_size({array_local}, '{pointer_arg}')\n")
            lines.append(f'        if {size_arg} is None:\n')
            lines.append(f'            {size_arg} = {size_local}\n')
            lines.append(f'        elif {size_local} != int({size_arg}):\n')
            lines.append(
                f"            raise ValueError(f'{pointer_arg} byte size {{{size_local}}} does not "
                f"match {size_arg} {{{size_arg}}}')\n"
            )
            lines.append(f'    elif {size_arg} is None:\n')
            lines.append(f"        {size_arg} = _nbytes_size({array_local}, '{pointer_arg}')\n")
        else:
            raise SystemExit(f'array_facade.{name} group {group_idx} lacks count_arg or size_arg')

    if keepalive_names:
        lines.append(f'    _keepalive = ({", ".join(keepalive_names)},)\n')
    call = ', '.join(call_args[param] for param in params)
    lines.append(f'    return _raw.{name}({call})\n\n\n')
    lines.append(f'{name}.__doc__ = getattr(_raw.{name}, "__doc__", None)\n')
    lines.append(f'{name}.argtypes = getattr(_raw.{name}, "argtypes", None)\n')
    lines.append(f'{name}.restype = getattr(_raw.{name}, "restype", None)\n\n\n')
    return ''.join(lines)


def _emit_gui_wrapper(special: str) -> str:
    common = "\n\n"
    if special == 'gui_tree_set_rows':
        body = '''def dvz_gui_tree_set_rows(tree, keys, parents, labels, secondary_labels=None, flags=0, row_count=None):
    keys_ptr, keys_keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, row_count)
    if row_count is None:
        row_count = len(keys) if not _raw_pointer(keys) else None
    parents_ptr, parents_keepalive = _gui_array(parents, 'parents', ctypes.POINTER(ctypes.c_uint32), np.uint32, row_count)
    labels_ptr, labels_keepalive = _gui_strings(labels, 'labels', row_count)
    secondary_ptr, secondary_keepalive = _gui_strings(secondary_labels, 'secondary_labels', row_count, optional=True)
    return _raw.dvz_gui_tree_set_rows(tree, int(row_count), keys_ptr, parents_ptr, labels_ptr, secondary_ptr, flags)
'''
    elif special.startswith('gui_tree_set_'):
        op = special.removeprefix('gui_tree_set_')
        if op in {'swatches', 'styles', 'visible', 'matches'}:
            arg = {'swatches': 'colors', 'styles': 'styles', 'visible': 'visible', 'matches': 'matches'}[op]
            target = {'swatches': 'ctypes.POINTER(_raw.DvzColor)', 'styles': 'ctypes.POINTER(_raw.DvzGuiDataStyle)', 'visible': 'ctypes.POINTER(ctypes.c_bool)', 'matches': 'ctypes.POINTER(ctypes.c_bool)'}[op]
            dtype = {'swatches': 'np.uint8', 'styles': 'None', 'visible': 'np.bool_', 'matches': 'np.bool_'}[op]
            shape_tail = ', shape_tail=(4,)' if op == 'swatches' else ''
            body = f'''def dvz_gui_tree_set_{op}(tree, {arg}, row_count=None):
    if row_count is None and {arg} is not None and not _raw_pointer({arg}):
        row_count = len({arg})
    ptr, keepalive = _gui_records({arg}, _raw.DvzGuiDataStyle, '{arg}', row_count) if '{op}' == 'styles' else _gui_array({arg}, '{arg}', {target}, {dtype}, row_count, optional=True{shape_tail})
    return _raw.dvz_gui_tree_set_{op}(tree, int(row_count or 0), ptr)
'''
        else:
            body = f'''def dvz_gui_tree_set_{op}(tree, keys, key_count=None):
    if key_count is None and not _raw_pointer(keys):
        key_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, key_count)
    return _raw.dvz_gui_tree_set_{op}(tree, int(key_count or 0), ptr)
'''
    elif special == 'gui_tree_draw':
        body = '''def dvz_gui_tree_draw(gui, tree, events=None, capacity=None):
    return _gui_draw(_raw.dvz_gui_tree_draw, gui, tree, events, capacity)
'''
    elif special in {'gui_tree_get_selection', 'gui_tree_get_expanded', 'gui_table_get_selection'}:
        function = special
        body = f'''def dvz_{function}(widget):
    count = _raw.dvz_{function}(widget, 0, None)
    values = (ctypes.c_uint64 * int(count))() if count else None
    if count:
        _raw.dvz_{function}(widget, int(count), values)
    return [] if not count else [int(values[i]) for i in range(int(count))]
'''
    elif special in {'gui_tree_get_filter', 'gui_table_get_filter'}:
        function = special
        body = f'''def dvz_{function}(widget):
    size = _raw.dvz_{function}(widget, 0, None)
    if not size:
        return ''
    buffer = ctypes.create_string_buffer(int(size))
    _raw.dvz_{function}(widget, int(size), buffer)
    return buffer.value.decode('utf-8')
'''
    elif special == 'gui_table':
        body = '''def dvz_gui_table(widget_id, columns, flags=0, column_count=None):
    widget_id = _encode_string(widget_id, 'widget_id')
    if _raw_pointer(columns):
        if column_count is None:
            raise TypeError('column_count must be provided for a raw column pointer')
        return _raw.dvz_gui_table(widget_id, int(column_count), columns, flags)
    items = list(columns)
    if column_count is not None and len(items) != int(column_count):
        raise ValueError(f'columns length {len(items)} does not match column_count {column_count}')
    records = (_raw.DvzGuiTableColumnDesc * len(items))()
    keepalive = [widget_id]
    allowed = {'struct_size', 'flags', 'column_id', 'type', 'initial_width', 'title', 'format', 'reserved'}
    for i, item in enumerate(items):
        if isinstance(item, dict):
            item = dict(item)
            unknown = sorted(set(item) - allowed)
            if unknown:
                raise TypeError(f'columns[{i}] has unknown fields: {", ".join(unknown)}')
            title = _encode_string(item.get('title'), f'columns[{i}].title')
            fmt = _encode_string(item.get('format'), f'columns[{i}].format')
            record = _raw.dvz_gui_table_column_desc()
            for key, value in item.items():
                if key not in {'title', 'format'} and hasattr(record, key):
                    setattr(record, key, value)
            record.title, record.format = title, fmt
            keepalive.extend((title, fmt))
        elif isinstance(item, _raw.DvzGuiTableColumnDesc):
            record = item
        else:
            raise TypeError(f'columns[{i}] must be a mapping or DvzGuiTableColumnDesc')
        if not record.struct_size:
            record.struct_size = ctypes.sizeof(_raw.DvzGuiTableColumnDesc)
        records[i] = record
    return _raw.dvz_gui_table(widget_id, len(records), records, flags)
'''
    elif special == 'gui_table_set_rows':
        body = '''def dvz_gui_table_set_rows(table, keys, flags=0, row_count=None):
    if row_count is None and not _raw_pointer(keys):
        row_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, row_count)
    return _raw.dvz_gui_table_set_rows(table, int(row_count or 0), ptr, flags)
'''
    elif special == 'gui_table_set_column_text':
        body = '''def dvz_gui_table_set_column_text(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_strings(values, 'values', row_count)
    return _raw.dvz_gui_table_set_column_text(table, column_id, int(row_count or 0), ptr)
'''
    elif special.startswith('gui_table_set_column_'):
        op = special.removeprefix('gui_table_set_column_')
        target = {'int64': 'ctypes.POINTER(ctypes.c_int64)', 'double': 'ctypes.POINTER(ctypes.c_double)', 'bool': 'ctypes.POINTER(ctypes.c_bool)', 'color': 'ctypes.POINTER(_raw.DvzColor)'}[op]
        dtype = {'int64': 'np.int64', 'double': 'np.float64', 'bool': 'np.bool_', 'color': 'np.uint8'}[op]
        shape_tail = ', shape_tail=(4,)' if op == 'color' else ''
        body = f'''def dvz_gui_table_set_column_{op}(table, column_id, values, row_count=None):
    if row_count is None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', {target}, {dtype}, row_count{shape_tail})
    return _raw.dvz_gui_table_set_column_{op}(table, column_id, int(row_count or 0), ptr)
'''
    elif special == 'gui_table_set_styles':
        body = '''def dvz_gui_table_set_styles(table, styles, style_count=None):
    if style_count is None and not _raw_pointer(styles):
        style_count = len(styles)
    ptr, keepalive = _gui_records(styles, _raw.DvzGuiDataStyle, 'styles', style_count)
    return _raw.dvz_gui_table_set_styles(table, int(style_count or 0), ptr)
'''
    elif special == 'gui_table_set_selection':
        body = '''def dvz_gui_table_set_selection(table, keys, key_count=None):
    if key_count is None and not _raw_pointer(keys):
        key_count = len(keys)
    ptr, keepalive = _gui_array(keys, 'keys', ctypes.POINTER(ctypes.c_uint64), np.uint64, key_count)
    return _raw.dvz_gui_table_set_selection(table, int(key_count or 0), ptr)
'''
    elif special in {'gui_table_set_visible', 'gui_table_set_matches'}:
        op = special.removeprefix('gui_table_set_')
        body = f'''def dvz_gui_table_set_{op}(table, values, row_count=None):
    if row_count is None and values is not None and not _raw_pointer(values):
        row_count = len(values)
    ptr, keepalive = _gui_array(values, 'values', ctypes.POINTER(ctypes.c_bool), np.bool_, row_count, optional=True)
    return _raw.dvz_gui_table_set_{op}(table, int(row_count or 0), ptr)
'''
    elif special == 'gui_table_draw':
        body = '''def dvz_gui_table_draw(gui, table, events=None, capacity=None):
    return _gui_draw(_raw.dvz_gui_table_draw, gui, table, events, capacity)
'''
    elif special == 'gui_table_get_sort':
        body = '''def dvz_gui_table_get_sort(table):
    column_id = ctypes.c_uint32()
    direction = ctypes.c_int32()
    result = _raw.dvz_gui_table_get_sort(table, ctypes.byref(column_id), ctypes.byref(direction))
    return result, int(column_id.value), int(direction.value)
'''
    else:
        raise SystemExit(f'unknown GUI facade special {special}')
    name = body.split('def ', 1)[1].split('(', 1)[0]
    return body + common + f'_raw_{name} = getattr(_raw, "{name}", None)\n{name}.__doc__ = getattr(_raw_{name}, "__doc__", None)\n{name}.argtypes = getattr(_raw_{name}, "argtypes", None)\n{name}.restype = getattr(_raw_{name}, "restype", None)\n\n\n'


def generate(api: dict, policy: dict) -> str:
    _validate_policy(api, policy)
    functions = _functions_by_name(api)
    lines = [HEADER]
    for function_name in sorted(policy):
        lines.append(_emit_wrapper(functions[function_name], policy[function_name]))
    lines.append('_ARRAY_FACADE_FUNCTIONS = ')
    lines.append(repr(sorted(policy)))
    lines.append('\n\n')
    lines.append('for _name in getattr(_raw, "__all__", dir(_raw)):\n')
    lines.append('    if _name not in globals():\n')
    lines.append('        globals()[_name] = getattr(_raw, _name)\n')
    lines.append('\n')
    lines.append("__all__ = [name for name in globals() if name.startswith(('dvz_', 'Dvz', 'DVZ_'))]\n")
    return ''.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, default=DEFAULT_INPUT)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--policy', type=Path, default=DEFAULT_POLICY)
    parser.add_argument('--check', action='store_true', help='fail if the generated file is stale')
    args = parser.parse_args()

    with args.input.open(encoding='utf8') as f:
        api = json.load(f)
    text = generate(api, _load_policy(args.policy))

    if args.check:
        current = args.output.read_text() if args.output.exists() else ''
        if current != text:
            raise SystemExit(f'{args.output} is stale; run `just ctypes`')
        print(f'{args.output} is up to date')
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding='utf8')
    print(f'wrote {args.output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
