#!/usr/bin/env python3
"""Generate the array-aware Datoviz facade from API JSON and binding policy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT_DIR / 'build' / 'bindings' / 'datoviz_api.json'
DEFAULT_OUTPUT = ROOT_DIR / 'datoviz' / '_array_facade.py'
DEFAULT_POLICY = ROOT_DIR / 'spec' / 'bindings' / 'ctypes.yml'

HEADER = '''\
"""
Array-aware facade for the Datoviz v0.4 Python binding.

This file is generated by tools/bindings/generate_array_facade.py. Do not edit it by hand.
"""

from __future__ import annotations

import ctypes

import numpy as np

from . import raw as _raw


def _encode_string(value, name):
    if isinstance(value, str):
        return value.encode('utf-8')
    if isinstance(value, bytes) or value is None:
        return value
    raise TypeError(f'{name} must be str, bytes, or None')


def _raw_pointer(value):
    if isinstance(value, (int, ctypes.c_void_p, ctypes.Array, ctypes._Pointer)):
        return True
    if type(value).__name__ == 'CArgObject' and hasattr(value, '_obj'):
        return True
    return hasattr(value, '_as_parameter_')


def _array_arg(value, name, raw_func, pointer_index, dtype=None):
    if _raw_pointer(value):
        return value, None
    array = np.asarray(value)
    if dtype is not None:
        expected = np.dtype(dtype)
        if array.dtype != expected:
            raise ValueError(f'{name} must have dtype {expected}, got {array.dtype}')
    if array.ndim == 0:
        raise ValueError(f'{name} must be at least one-dimensional')
    if not array.flags.c_contiguous:
        array = np.ascontiguousarray(array)
    pointer = ctypes.c_void_p(array.ctypes.data)
    target = None
    argtypes = getattr(raw_func, 'argtypes', None)
    if argtypes is not None and pointer_index < len(argtypes):
        target = argtypes[pointer_index]
    if target is not None and target is not ctypes.c_void_p:
        pointer = ctypes.cast(pointer, target)
    return pointer, array


def _shape0_count(array, name):
    if array is None:
        raise TypeError(f'{name} count must be provided when passing a raw pointer')
    return int(array.shape[0])


def _nbytes_size(array, name):
    if array is None:
        raise TypeError(f'{name} byte size must be provided when passing a raw pointer')
    return int(array.nbytes)


def _visual_data_updates_arg(updates):
    if isinstance(updates, dict):
        items = list(updates.items())
    else:
        try:
            items = list(updates)
        except TypeError as exc:
            raise TypeError('updates must be a mapping or iterable of (attr_name, data) pairs') from exc
    if not items:
        raise ValueError('updates must not be empty')

    records = (_raw.DvzVisualDataUpdate * len(items))()
    keepalive = []
    item_count = None

    for i, item in enumerate(items):
        try:
            attr_name, data = item
        except (TypeError, ValueError) as exc:
            raise TypeError('updates must contain (attr_name, data) pairs') from exc

        attr_name_bytes = _encode_string(attr_name, f'updates[{i}].attr_name')
        data_array = np.asarray(data)
        if data_array.ndim == 0:
            raise ValueError(f'updates[{attr_name!r}] data must be at least one-dimensional')
        if not data_array.flags.c_contiguous:
            data_array = np.ascontiguousarray(data_array)
        count = int(data_array.shape[0])
        if item_count is None:
            item_count = count
        elif count != item_count:
            raise ValueError(
                f'updates[{attr_name!r}] item count {count} does not match expected {item_count}'
            )

        records[i].attr_name = attr_name_bytes
        records[i].data = ctypes.c_void_p(data_array.ctypes.data)
        records[i].item_count = count
        keepalive.extend((attr_name_bytes, data_array))

    return records, keepalive


def _axis_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzAxisTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzAxisTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzAxisTicks
    ):
        return value
    return None


def _axis_ticks_arg(values, labels):
    raw_descriptor = _axis_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzAxisTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzAxisTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzAxisTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def _colorbar_ticks_raw_descriptor(value):
    if isinstance(value, _raw.DvzColorbarTicks):
        return ctypes.byref(value)
    pointer_type = ctypes.POINTER(_raw.DvzColorbarTicks)
    if isinstance(value, pointer_type):
        return value
    if type(value).__name__ == 'CArgObject' and isinstance(
        getattr(value, '_obj', None), _raw.DvzColorbarTicks
    ):
        return value
    return None


def _colorbar_ticks_arg(values, labels):
    raw_descriptor = _colorbar_ticks_raw_descriptor(values)
    if raw_descriptor is not None:
        if labels is not None:
            raise TypeError('labels must be omitted when passing a raw DvzColorbarTicks descriptor')
        return raw_descriptor, (values,)

    value_array = np.asarray(values, dtype=np.float64)
    if value_array.ndim != 1:
        raise ValueError('values must be one-dimensional')
    if not value_array.flags.c_contiguous:
        value_array = np.ascontiguousarray(value_array)

    count = int(value_array.shape[0])
    label_array = None
    encoded_labels = None
    if labels is not None:
        encoded_labels = [
            _encode_string(label, f'labels[{i}]') for i, label in enumerate(labels)
        ]
        if len(encoded_labels) != count:
            raise ValueError(f'labels length {len(encoded_labels)} does not match tick count {count}')
        if count > 0:
            label_array = (ctypes.c_char_p * count)(*encoded_labels)

    record = _raw.DvzColorbarTicks()
    record.struct_size = ctypes.sizeof(_raw.DvzColorbarTicks)
    record.flags = 0
    record.count = count
    record.values = (
        value_array.ctypes.data_as(ctypes.POINTER(ctypes.c_double)) if count > 0 else None
    )
    record.labels = label_array
    keepalive = (record, value_array, encoded_labels, label_array)
    return ctypes.byref(record), keepalive


def dvz_view_capture_rgba(view):
    canvas = _raw.dvz_view_canvas(view)
    if not canvas:
        raise RuntimeError('dvz_view_capture_rgba failed: view has no canvas')

    width = ctypes.c_uint32()
    height = ctypes.c_uint32()
    _raw.dvz_view_framebuffer_size(view, ctypes.byref(width), ctypes.byref(height))
    if width.value == 0 or height.value == 0:
        raise RuntimeError('dvz_view_capture_rgba failed: view framebuffer size is zero')

    rgba = np.empty((height.value, width.value, 4), dtype=np.uint8)
    out = rgba.ctypes.data_as(ctypes.POINTER(ctypes.c_uint8))
    rc = _raw.dvz_canvas_capture_rgba_into(
        canvas, width.value, height.value, out, rgba.nbytes
    )
    if rc != 0:
        raise RuntimeError(f'dvz_view_capture_rgba failed with code {rc}')
    return rgba


'''


def _load_policy(path: Path) -> dict:
    try:
        import yaml  # type: ignore

        with path.open(encoding='utf8') as f:
            policy = yaml.safe_load(f) or {}
        facade = policy.get('array_facade', {})
    except ModuleNotFoundError:
        facade = _array_facade_policy_fallback(path)
    if not isinstance(facade, dict):
        raise SystemExit('array_facade policy must be a mapping')
    return facade


def _array_facade_policy_fallback(path: Path) -> dict:
    facade: dict[str, dict] = {}
    current_function: str | None = None
    current_section: str | None = None
    current_group: dict | None = None
    in_facade = False

    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        indent = len(line) - len(line.lstrip(' '))
        if stripped == 'array_facade:':
            in_facade = True
            current_function = None
            current_section = None
            current_group = None
            continue
        if not in_facade:
            continue
        if indent == 0 and stripped != 'array_facade:':
            break
        if indent == 2 and stripped.endswith(':'):
            current_function = stripped[:-1]
            facade[current_function] = {}
            current_section = None
            current_group = None
            continue
        if current_function is None:
            continue
        if indent == 4 and stripped.endswith(':'):
            current_section = stripped[:-1]
            if current_section == 'strings':
                facade[current_function][current_section] = []
            elif current_section == 'groups':
                facade[current_function][current_section] = []
            current_group = None
            continue
        if indent == 4 and ':' in stripped and current_section is None:
            key, value = stripped.split(':', 1)
            facade[current_function][key.strip()] = value.strip()
            continue
        if current_section == 'strings' and indent == 6 and stripped.startswith('- '):
            facade[current_function]['strings'].append(stripped[2:].strip())
            continue
        if current_section == 'groups' and indent == 6 and stripped.startswith('- '):
            current_group = {}
            facade[current_function]['groups'].append(current_group)
            key, value = stripped[2:].split(':', 1)
            current_group[key.strip()] = value.strip()
            continue
        if current_section == 'groups' and current_group is not None and indent == 8:
            key, value = stripped.split(':', 1)
            current_group[key.strip()] = value.strip()
    return facade


def _functions_by_name(api: dict) -> dict[str, dict]:
    return {
        function['name']: function
        for function in api.get('functions', [])
        if isinstance(function, dict) and function.get('name')
    }


def _validate_policy(api: dict, policy: dict) -> None:
    functions = _functions_by_name(api)
    for function_name, rules in policy.items():
        if function_name not in functions:
            raise SystemExit(f'array_facade policy references unknown function {function_name}')
        if not isinstance(rules, dict):
            raise SystemExit(f'array_facade.{function_name} must be a mapping')
        params = {
            param.get('name')
            for param in functions[function_name].get('parameters', [])
            if param.get('name')
        }
        for string_arg in rules.get('strings', []) or []:
            if string_arg not in params:
                raise SystemExit(
                    f'array_facade.{function_name} references unknown string arg {string_arg}'
                )
        for group in rules.get('groups', []) or []:
            for key in ('pointer_arg',):
                if group.get(key) not in params:
                    raise SystemExit(
                        f'array_facade.{function_name} references unknown {key} {group.get(key)}'
                    )
            count_arg = group.get('count_arg')
            size_arg = group.get('size_arg')
            if bool(count_arg) == bool(size_arg):
                raise SystemExit(
                    f'array_facade.{function_name} group must define exactly one count_arg or size_arg'
                )
            if count_arg and count_arg not in params:
                raise SystemExit(
                    f'array_facade.{function_name} references unknown count_arg {count_arg}'
                )
            if size_arg and size_arg not in params:
                raise SystemExit(
                    f'array_facade.{function_name} references unknown size_arg {size_arg}'
                )
            if group.get('lifetime') != 'copied_before_return':
                raise SystemExit(
                    f'array_facade.{function_name} group lifetime must be copied_before_return'
                )
        special = rules.get('special')
        if special is not None and special not in {
            'visual_data_updates',
            'axis_ticks',
            'colorbar_ticks',
        }:
            raise SystemExit(f'array_facade.{function_name} has unknown special wrapper {special}')


def _signature(function: dict, rules: dict) -> tuple[list[str], set[str]]:
    group_targets = set()
    for group in rules.get('groups', []) or []:
        group_targets.add(group.get('count_arg') or group.get('size_arg'))
    params = [
        param.get('name') or f'arg{i}'
        for i, param in enumerate(function.get('parameters', []))
    ]
    signature = [f'{name}=None' if name in group_targets else name for name in params]
    return signature, group_targets


def _emit_wrapper(function: dict, rules: dict) -> str:
    name = function['name']
    if name == 'dvz_visual_set_data_many':
        return '''\
def dvz_visual_set_data_many(visual, updates, update_count=None):
    if update_count is not None:
        return _raw.dvz_visual_set_data_many(visual, updates, update_count)
    if _raw_pointer(updates):
        raise TypeError('update_count must be provided when passing raw update descriptors')
    _updates_records, _updates_keepalive = _visual_data_updates_arg(updates)
    _keepalive = (_updates_records, _updates_keepalive,)
    return _raw.dvz_visual_set_data_many(visual, _updates_records, len(_updates_records))


dvz_visual_set_data_many.__doc__ = getattr(_raw.dvz_visual_set_data_many, "__doc__", None)
dvz_visual_set_data_many.argtypes = getattr(_raw.dvz_visual_set_data_many, "argtypes", None)
dvz_visual_set_data_many.restype = getattr(_raw.dvz_visual_set_data_many, "restype", None)


'''
    if name == 'dvz_axis_set_ticks':
        return '''\
def dvz_axis_set_ticks(axis, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _axis_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_axis_set_ticks(axis, _ticks_ptr)


dvz_axis_set_ticks.__doc__ = getattr(_raw.dvz_axis_set_ticks, "__doc__", None)
dvz_axis_set_ticks.argtypes = getattr(_raw.dvz_axis_set_ticks, "argtypes", None)
dvz_axis_set_ticks.restype = getattr(_raw.dvz_axis_set_ticks, "restype", None)


'''
    if name == 'dvz_colorbar_set_ticks':
        return '''\
def dvz_colorbar_set_ticks(colorbar, values, labels=None):
    _ticks_ptr, _ticks_keepalive = _colorbar_ticks_arg(values, labels)
    _keepalive = (_ticks_keepalive,)
    return _raw.dvz_colorbar_set_ticks(colorbar, _ticks_ptr)


dvz_colorbar_set_ticks.__doc__ = getattr(_raw.dvz_colorbar_set_ticks, "__doc__", None)
dvz_colorbar_set_ticks.argtypes = getattr(_raw.dvz_colorbar_set_ticks, "argtypes", None)
dvz_colorbar_set_ticks.restype = getattr(_raw.dvz_colorbar_set_ticks, "restype", None)


'''
    params = [param.get('name') or f'arg{i}' for i, param in enumerate(function.get('parameters', []))]
    param_index = {param: i for i, param in enumerate(params)}
    signature, inferred_targets = _signature(function, rules)
    lines = [f'def {name}({", ".join(signature)}):\n']
    call_args = {param: param for param in params}
    keepalive_names = []

    for string_arg in rules.get('strings', []) or []:
        local_name = f'_{string_arg}_bytes'
        lines.append(f"    {local_name} = _encode_string({string_arg}, '{string_arg}')\n")
        call_args[string_arg] = local_name
        keepalive_names.append(local_name)

    for group_idx, group in enumerate(rules.get('groups', []) or []):
        pointer_arg = group['pointer_arg']
        pointer_local = f'_{pointer_arg}_ptr'
        array_local = f'_{pointer_arg}_array'
        dtype = group.get('dtype')
        dtype_arg = repr(dtype) if dtype else 'None'
        lines.append(
            f"    {pointer_local}, {array_local} = _array_arg("
            f"{pointer_arg}, '{pointer_arg}', _raw.{name}, {param_index[pointer_arg]}, {dtype_arg})\n"
        )
        call_args[pointer_arg] = pointer_local
        keepalive_names.append(array_local)

        count_arg = group.get('count_arg')
        size_arg = group.get('size_arg')
        if count_arg:
            if group.get('count_from') != 'shape0':
                raise SystemExit(f'array_facade.{name} only supports count_from: shape0')
            lines.append(f'    if {count_arg} is None:\n')
            lines.append(f"        {count_arg} = _shape0_count({array_local}, '{pointer_arg}')\n")
        elif size_arg:
            if group.get('size_from') != 'nbytes':
                raise SystemExit(f'array_facade.{name} only supports size_from: nbytes')
            lines.append(f'    if {size_arg} is None:\n')
            lines.append(f"        {size_arg} = _nbytes_size({array_local}, '{pointer_arg}')\n")
        else:
            raise SystemExit(f'array_facade.{name} group {group_idx} lacks count_arg or size_arg')

    if keepalive_names:
        lines.append(f'    _keepalive = ({", ".join(keepalive_names)},)\n')
    call = ', '.join(call_args[param] for param in params)
    lines.append(f'    return _raw.{name}({call})\n\n\n')
    lines.append(f'{name}.__doc__ = getattr(_raw.{name}, "__doc__", None)\n')
    lines.append(f'{name}.argtypes = getattr(_raw.{name}, "argtypes", None)\n')
    lines.append(f'{name}.restype = getattr(_raw.{name}, "restype", None)\n\n\n')
    return ''.join(lines)


def generate(api: dict, policy: dict) -> str:
    _validate_policy(api, policy)
    functions = _functions_by_name(api)
    lines = [HEADER]
    for function_name in sorted(policy):
        lines.append(_emit_wrapper(functions[function_name], policy[function_name]))
    lines.append('_ARRAY_FACADE_FUNCTIONS = ')
    lines.append(repr(sorted(policy)))
    lines.append('\n\n')
    lines.append('for _name in getattr(_raw, "__all__", dir(_raw)):\n')
    lines.append('    if _name not in globals():\n')
    lines.append('        globals()[_name] = getattr(_raw, _name)\n')
    lines.append('\n')
    lines.append("__all__ = [name for name in globals() if name.startswith(('dvz_', 'Dvz'))]\n")
    return ''.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, default=DEFAULT_INPUT)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--policy', type=Path, default=DEFAULT_POLICY)
    parser.add_argument('--check', action='store_true', help='fail if the generated file is stale')
    args = parser.parse_args()

    with args.input.open(encoding='utf8') as f:
        api = json.load(f)
    text = generate(api, _load_policy(args.policy))

    if args.check:
        current = args.output.read_text() if args.output.exists() else ''
        if current != text:
            raise SystemExit(f'{args.output} is stale; run `just ctypes`')
        print(f'{args.output} is up to date')
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding='utf8')
    print(f'wrote {args.output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
