#!/usr/bin/env python3
"""Generate the raw Datoviz ctypes module from extracted API JSON."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT_DIR / 'build' / 'bindings' / 'datoviz_api.json'
DEFAULT_OUTPUT = ROOT_DIR / 'datoviz' / '_ctypes.py'
DEFAULT_POLICY = ROOT_DIR / 'spec' / 'bindings' / 'ctypes.yml'

HEADER = '''\
"""
Raw ctypes bindings for Datoviz v0.4.

This file is generated by tools/bindings/generate_ctypes.py. Do not edit it by hand.
"""

from __future__ import annotations

import ctypes
import os
import pathlib
import platform
from enum import IntEnum


class CtypesEnum(IntEnum):
    @classmethod
    def from_param(cls, obj):
        return int(obj)


_PLATFORM_LIB_NAMES = {
    'Linux': ('libdatoviz.so',),
    'Darwin': ('libdatoviz.dylib',),
    'Windows': ('datoviz.dll', 'libdatoviz.dll'),
}


def _candidate_library_paths():
    env_path = os.environ.get('DATOVIZ_LIBRARY')
    if env_path:
        yield pathlib.Path(env_path)

    names = _PLATFORM_LIB_NAMES.get(platform.system())
    if not names:
        return

    here = pathlib.Path(__file__).resolve().parent
    root = here.parent
    for name in names:
        yield here / name
        yield root / 'build' / 'src' / name
        yield root / 'build' / name

    # Conda installs Python modules under <prefix>/lib/pythonX.Y/site-packages and native
    # libraries under <prefix>/lib on Unix or <prefix>/Library/bin on Windows.
    for parent in here.parents:
        for name in names:
            yield parent / 'lib' / name
            yield parent / 'Library' / 'bin' / name


def _configure_runtime_dirs():
    here = pathlib.Path(__file__).resolve().parent
    existing = [
        path
        for path in os.environ.get('DVZ_WHEEL_RUNTIME_DIRS', '').split(os.pathsep)
        if path
    ]
    here_str = str(here)
    dirs = [here_str, *[path for path in existing if path != here_str]]
    os.environ['DVZ_WHEEL_RUNTIME_DIRS'] = os.pathsep.join(dirs)
    if platform.system() == 'Windows' and hasattr(os, 'add_dll_directory'):
        os.add_dll_directory(here_str)


def _load_library():
    _configure_runtime_dirs()
    errors = []
    missing = []
    for path in _candidate_library_paths():
        if not path.exists():
            missing.append(str(path))
            continue
        try:
            return ctypes.cdll.LoadLibrary(str(path))
        except OSError as exc:
            errors.append(f'{path}: {exc}')
    loader_env_names = ('LD_LIBRARY_PATH', 'DYLD_LIBRARY_PATH', 'PATH')
    loader_env = ', '.join(
        f'{name}={os.environ.get(name, "")!r}' for name in loader_env_names
    )
    context = (
        f'platform={platform.system()!r}; '
        f'DATOVIZ_LIBRARY={os.environ.get("DATOVIZ_LIBRARY", "")!r}; '
        f'{loader_env}'
    )
    details = []
    if errors:
        details.append('load errors: ' + '; '.join(errors))
    if missing:
        details.append('missing candidates: ' + ', '.join(missing))
    if not details:
        details.append('no candidate path was generated')
    raise RuntimeError(f'Unable to load libdatoviz ({context}; {"; ".join(details)})')


dvz = _load_library()
_MISSING_FUNCTIONS = []
_UNSUPPORTED_FUNCTIONS = {}
_UNSUPPORTED_LAYOUT_RECORDS = {}
_DATOVIZ_CTYPES_LAYOUT_RECORDS = []
_CALLBACK_KEEPALIVE = {}


def _ctypes_alignment_is_effective(requested):
    class _AlignmentProbe(ctypes.Structure):
        _align_ = requested
        _fields_ = [('_value', ctypes.c_char)]

    return ctypes.alignment(_AlignmentProbe) == requested


def _ptr_value(obj):
    if obj is None:
        return None
    if isinstance(obj, int):
        return obj
    try:
        return ctypes.cast(obj, ctypes.c_void_p).value
    except (ctypes.ArgumentError, TypeError, ValueError):
        value = getattr(obj, 'value', None)
        return value if isinstance(value, int) else id(obj)


def _callback_user_data_value(obj):
    if obj is None:
        return None
    if isinstance(obj, int):
        return obj
    value = getattr(obj, 'value', None)
    if value is None or isinstance(value, int):
        return value
    return _ptr_value(obj)


def _callback_identity(callback):
    if callback is None:
        return None
    try:
        ptr = ctypes.cast(callback, ctypes.c_void_p).value
    except (ctypes.ArgumentError, TypeError, ValueError):
        ptr = None
    if ptr is not None:
        return ('ctypes', ptr)
    self_obj = getattr(callback, '__self__', None)
    func = getattr(callback, '__func__', None)
    if self_obj is not None and func is not None:
        return ('method', id(self_obj), id(func))
    return ('object', id(callback))


def _callback_subscription_key(callback_type, owner, callback, user_data):
    return (
        'subscription',
        callback_type.__name__,
        _ptr_value(owner),
        _callback_identity(callback),
        _callback_user_data_value(user_data),
    )


def _callback_setter_key(function_name, callback_type, owner):
    return ('setter', function_name, callback_type.__name__, _ptr_value(owner))


def _callback_global_key(function_name, callback_type):
    return ('global', function_name, callback_type.__name__)


def _callback_coerce(callback_type, callback):
    if callback is None:
        return callback_type()
    if isinstance(callback, callback_type):
        return callback
    return callback_type(callback)


def _callback_store_subscription(callback_type, owner, callback, user_data):
    c_callback = _callback_coerce(callback_type, callback)
    if callback is not None:
        key = _callback_subscription_key(callback_type, owner, callback, user_data)
        _CALLBACK_KEEPALIVE[key] = c_callback
    return c_callback


def _callback_pop_subscription(callback_type, owner, callback, user_data):
    if callback is None:
        return callback_type()
    key = _callback_subscription_key(callback_type, owner, callback, user_data)
    return _CALLBACK_KEEPALIVE.pop(key, None) or _callback_coerce(callback_type, callback)


def _callback_store_subscription_id(owner, subscription_id, callback):
    if subscription_id:
        _CALLBACK_KEEPALIVE[('subscription_id', _ptr_value(owner), int(subscription_id))] = callback
    return subscription_id


def _callback_pop_subscription_id(owner, subscription_id):
    if subscription_id:
        _CALLBACK_KEEPALIVE.pop(('subscription_id', _ptr_value(owner), int(subscription_id)), None)


def _callback_store_setter(function_name, callback_type, owner, callback):
    key = _callback_setter_key(function_name, callback_type, owner)
    if callback is None:
        _CALLBACK_KEEPALIVE.pop(key, None)
        return callback_type()
    c_callback = _callback_coerce(callback_type, callback)
    _CALLBACK_KEEPALIVE[key] = c_callback
    return c_callback


def _callback_store_global(function_name, callback_type, callback):
    key = _callback_global_key(function_name, callback_type)
    if callback is None:
        _CALLBACK_KEEPALIVE.pop(key, None)
        return callback_type()
    c_callback = _callback_coerce(callback_type, callback)
    _CALLBACK_KEEPALIVE[key] = c_callback
    return c_callback

'''

CTYPE_MAP = {
    'void': 'None',
    'bool': 'ctypes.c_bool',
    '_Bool': 'ctypes.c_bool',
    'char': 'ctypes.c_char',
    'signed char': 'ctypes.c_int8',
    'unsigned char': 'ctypes.c_uint8',
    'int8_t': 'ctypes.c_int8',
    'uint8_t': 'ctypes.c_uint8',
    'int16_t': 'ctypes.c_int16',
    'uint16_t': 'ctypes.c_uint16',
    'int32_t': 'ctypes.c_int32',
    'uint32_t': 'ctypes.c_uint32',
    'int64_t': 'ctypes.c_int64',
    'uint64_t': 'ctypes.c_uint64',
    'int': 'ctypes.c_int',
    'unsigned int': 'ctypes.c_uint',
    'long': 'ctypes.c_long',
    'unsigned long': 'ctypes.c_ulong',
    'long long': 'ctypes.c_longlong',
    'unsigned long long': 'ctypes.c_ulonglong',
    'size_t': 'ctypes.c_size_t',
    'ssize_t': 'ctypes.c_ssize_t',
    'float': 'ctypes.c_float',
    'double': 'ctypes.c_double',
    'DvzId': 'ctypes.c_uint64',
    'DvzCallbackId': 'ctypes.c_uint64',
    'DvzCategoryId': 'ctypes.c_int64',
    'DvzResult': 'ctypes.c_int32',
    'DvzSize': 'ctypes.c_uint64',
    'DvzTimestamp': 'ctypes.c_int64',
    'VkAccessFlags2': 'ctypes.c_uint64',
    'VkDeviceSize': 'ctypes.c_uint64',
    'VkPipelineStageFlags2': 'ctypes.c_uint64',
}

SYNTHETIC_RECORD_CLASSES = {
    'DvzInputEventContent': 'Union',
}

SCALAR_TYPEDEF_ALIASES = {
    'DvzResult',
}

SYNTHETIC_RECORD_FIELDS = {
    'DvzInputEventContent': [
        ('pointer', 'DvzPointerEvent'),
        ('keyboard', 'DvzKeyboardEvent'),
        ('resize', 'DvzInputResizeEvent'),
        ('scale', 'DvzInputScaleEvent'),
    ],
}

ANONYMOUS_FIELD_CTYPES = {
    'union DvzInputEvent::(unnamed': 'DvzInputEventContent',
    'union (unnamed union at include/datoviz/input/router.h:86:5)': 'DvzInputEventContent',
}


ARRAY_RE = re.compile(r'^(?P<base>.+?)(?P<dims>(?:\[[0-9]+\])+)$')
DIM_RE = re.compile(r'\[([0-9]+)\]')
SUPPORTED_VECTOR_FIELD_ALIASES = {
    'vec2',
    'vec3',
    'vec4',
    'dvec2',
    'dvec3',
    'dvec4',
}


def _clean_type(qualtype: str) -> str:
    out = ' '.join(qualtype.replace(' *', '*').replace('*', ' * ').split())
    return ' '.join(token for token in out.split() if token != 'const')


def _split_args(args: str) -> list[str]:
    args = args.strip()
    if not args or args == 'void':
        return []
    out = []
    start = 0
    depth = 0
    for i, char in enumerate(args):
        if char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
        elif char == ',' and depth == 0:
            out.append(args[start:i].strip())
            start = i + 1
    out.append(args[start:].strip())
    return out


def _function_pointer_parts(qualtype: str) -> tuple[str, list[str]] | None:
    t = ' '.join(qualtype.split())
    match = re.match(r'^(?P<result>.+?)\s*\(\s*\*\s*\)\s*\((?P<args>.*)\)$', t)
    if not match:
        return None
    return match.group('result').strip(), _split_args(match.group('args'))


def _callback_typedefs(api: dict) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for typedef in api.get('typedefs', []):
        name = typedef.get('name')
        if not name:
            continue
        type_info = typedef.get('type', {})
        for spelling in (type_info.get('qualtype', ''), type_info.get('canonical', '')):
            parts = _function_pointer_parts(spelling)
            if parts is None:
                continue
            result, args = parts
            out[name] = {'name': name, 'result': result, 'args': args}
            break
    return out


def _array_ctype(
    qualtype: str,
    records: set[str],
    enums: set[str],
    value_records: set[str] | None = None,
    callbacks: set[str] | None = None,
) -> str | None:
    if '(*' in ''.join(qualtype.split()):
        return None
    match = ARRAY_RE.match(_clean_type(qualtype))
    if not match:
        return None
    ctype = _ctype_for(
        match.group('base').strip(),
        records,
        enums,
        value_records=value_records,
        callbacks=callbacks,
    )
    if ctype is None:
        return None
    for dim in reversed([int(dim) for dim in DIM_RE.findall(match.group('dims'))]):
        ctype = f'({ctype} * {dim})'
    return ctype


def _pointer_ctype(qualtype: str, records: set[str], enums: set[str]) -> str | None:
    t = _clean_type(qualtype)
    if '*' not in t:
        return None
    if '(*' in qualtype:
        return 'ctypes.c_void_p'

    depth = t.count('*')
    target = t.replace('*', ' ').strip()
    if target.startswith('struct '):
        target = target[len('struct ') :]
    if target.startswith('enum '):
        target = target[len('enum ') :]

    if target == 'char' and depth == 1:
        return 'ctypes.c_char_p'
    if target == 'char' and depth == 2:
        return 'ctypes.POINTER(ctypes.c_char_p)'
    if target == 'void' and depth == 1:
        return 'ctypes.c_void_p'
    if target in SUPPORTED_VECTOR_FIELD_ALIASES:
        return 'ctypes.c_void_p'
    if target in records:
        base = target
        for _ in range(depth):
            base = f'ctypes.POINTER({base})'
        return base

    base = _ctype_for(target, records, enums)
    if base is None:
        return 'ctypes.c_void_p'
    for _ in range(depth):
        base = f'ctypes.POINTER({base})'
    return base


def _ctype_for_type(
    type_info: dict,
    records: set[str],
    enums: set[str],
    value_records: set[str] | None = None,
    callbacks: set[str] | None = None,
) -> str | None:
    spellings = [type_info.get('qualtype', ''), type_info.get('canonical', '')]
    for spelling in spellings:
        for prefix, ctype in ANONYMOUS_FIELD_CTYPES.items():
            if spelling.startswith(prefix):
                return ctype
    for spelling in spellings:
        ctype = _array_ctype(
            spelling, records, enums, value_records=value_records, callbacks=callbacks
        )
        if ctype is not None:
            return ctype
    for spelling in spellings:
        ctype = _ctype_for(
            spelling,
            records,
            enums,
            value_records=value_records,
            callbacks=callbacks,
        )
        if ctype is not None:
            return ctype
    return None


def _unsupported_field_layout(type_info: dict) -> bool:
    qualtype = _clean_type(type_info.get('qualtype', ''))
    if qualtype in SUPPORTED_VECTOR_FIELD_ALIASES:
        return False
    for spelling in (type_info.get('qualtype', ''), type_info.get('canonical', '')):
        t = _clean_type(spelling)
        if t.startswith(('vec', 'dvec', 'mat')):
            return True
        if ('float[' in t or 'double[' in t) and '*' not in t:
            return True
    return False


def _record_dependency(type_info: dict, records: set[str]) -> str | None:
    for spelling in (type_info.get('qualtype', ''), type_info.get('canonical', '')):
        t = _clean_type(spelling)
        if '*' in t:
            continue
        match = ARRAY_RE.match(t)
        if match:
            t = match.group('base').strip()
        if t.startswith('struct '):
            t = t[len('struct ') :]
        if t in records:
            return t
    return None


def _ordered_records(api: dict, records: set[str]) -> list[dict]:
    by_name = {record['name']: record for record in api.get('records', []) if record.get('name')}
    visiting: set[str] = set()
    visited: set[str] = set()
    ordered: list[dict] = []

    def visit(name: str) -> None:
        if name in visited or name in visiting:
            return
        record = by_name.get(name)
        if record is None:
            return
        visiting.add(name)
        if not record.get('opaque'):
            for field in record.get('fields', []):
                dep = _record_dependency(field.get('type', {}), records)
                if dep and dep != name:
                    visit(dep)
        visiting.remove(name)
        visited.add(name)
        ordered.append(record)

    for name in sorted(by_name):
        visit(name)
    return ordered


def _layout_records_from_policy(path: Path) -> set[str]:
    if not path.exists():
        return set()
    try:
        import yaml  # type: ignore

        with path.open(encoding='utf8') as f:
            policy = yaml.safe_load(f) or {}
        include = policy.get('layout_records', {}).get('include', [])
        if isinstance(include, list) and all(isinstance(item, str) for item in include):
            return set(include)
    except ModuleNotFoundError:
        pass

    out: set[str] = set()
    in_layout = False
    in_include = False
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped == 'layout_records:':
            in_layout = True
            in_include = False
            continue
        if in_layout and not line.startswith(' ') and stripped:
            break
        if in_layout and stripped == 'include:':
            in_include = True
            continue
        if in_include and stripped.startswith('- '):
            out.add(stripped[2:].strip())
        elif in_include and stripped and not stripped.startswith('#'):
            break
    return out


def _required_alignments_from_policy(path: Path) -> dict[str, int]:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore

        with path.open(encoding='utf8') as f:
            policy = yaml.safe_load(f) or {}
        entries = policy.get('layout_records', {}).get('required_alignment', {})
        if isinstance(entries, dict):
            out = {}
            for name, alignment in entries.items():
                if (
                    isinstance(name, str)
                    and isinstance(alignment, int)
                    and not isinstance(alignment, bool)
                    and alignment > 0
                ):
                    out[name] = alignment
            return out
    except ModuleNotFoundError:
        pass

    out: dict[str, int] = {}
    in_layout = False
    in_alignments = False
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped == 'layout_records:':
            in_layout = True
            in_alignments = False
            continue
        if in_layout and not line.startswith(' ') and stripped:
            break
        if in_layout and stripped == 'required_alignment:':
            in_alignments = True
            continue
        if in_alignments and line.startswith('    ') and ':' in stripped:
            name, value = stripped.split(':', 1)
            try:
                alignment = int(value.strip())
            except ValueError:
                continue
            if alignment > 0:
                out[name.strip()] = alignment
        elif in_alignments and stripped and not stripped.startswith('#'):
            break
    return out


def _callback_policy_from_policy(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore

        with path.open(encoding='utf8') as f:
            policy = yaml.safe_load(f) or {}
        groups = policy.get('callback_functions', {})
        out: dict[str, str] = {}
        if isinstance(groups, dict):
            for kind, names in groups.items():
                if isinstance(kind, str) and isinstance(names, list):
                    for name in names:
                        if isinstance(name, str):
                            out[name] = kind
        return out
    except ModuleNotFoundError:
        pass

    out: dict[str, str] = {}
    in_callbacks = False
    current_kind: str | None = None
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped == 'callback_functions:':
            in_callbacks = True
            current_kind = None
            continue
        if in_callbacks and not line.startswith(' ') and stripped:
            break
        if in_callbacks and stripped.endswith(':'):
            current_kind = stripped[:-1]
            continue
        if in_callbacks and current_kind is not None and stripped.startswith('- '):
            out[stripped[2:].strip()] = current_kind
    return out


def _owned_string_returns_from_policy(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore

        with path.open() as f:
            policy = yaml.safe_load(f) or {}
        entries = policy.get('owned_string_returns', {})
        out: dict[str, str] = {}
        if isinstance(entries, dict):
            for name, entry in entries.items():
                if isinstance(name, str) and isinstance(entry, dict):
                    destroy = entry.get('destroy')
                    if isinstance(destroy, str):
                        out[name] = destroy
        return out
    except ModuleNotFoundError:
        pass

    out: dict[str, str] = {}
    in_section = False
    current_name: str | None = None
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped == 'owned_string_returns:':
            in_section = True
            current_name = None
            continue
        if in_section and not line.startswith(' ') and stripped:
            break
        if (
            in_section
            and line.startswith('  ')
            and not line.startswith('    ')
            and stripped.endswith(':')
        ):
            current_name = stripped[:-1]
            continue
        if in_section and current_name is not None and stripped.startswith('destroy:'):
            out[current_name] = stripped.split(':', 1)[1].strip()
    return out


def _concrete_record_policy_from_policy(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore

        with path.open(encoding='utf8') as f:
            policy = yaml.safe_load(f) or {}
        entries = policy.get('concrete_records', {})
        out: dict[str, dict] = {}
        if isinstance(entries, dict):
            for name, entry in entries.items():
                if not isinstance(name, str) or not isinstance(entry, dict):
                    continue
                disposition = entry.get('disposition')
                provenance = entry.get('provenance', [])
                if not isinstance(disposition, str):
                    continue
                if not isinstance(provenance, list) or not all(
                    isinstance(item, str) for item in provenance
                ):
                    provenance = []
                out[name] = {
                    'disposition': disposition,
                    'provenance': list(provenance),
                }
        return out
    except ModuleNotFoundError:
        pass

    out: dict[str, dict] = {}
    in_section = False
    current_name: str | None = None
    in_provenance = False
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped == 'concrete_records:':
            in_section = True
            current_name = None
            in_provenance = False
            continue
        if in_section and not line.startswith(' ') and stripped:
            break
        if in_section and line.startswith('  ') and not line.startswith('    ') and stripped.endswith(':'):
            current_name = stripped[:-1]
            out[current_name] = {'disposition': '', 'provenance': []}
            in_provenance = False
            continue
        if current_name is None:
            continue
        if line.startswith('    ') and not line.startswith('      ') and stripped.startswith(
            'disposition:'
        ):
            out[current_name]['disposition'] = stripped.split(':', 1)[1].strip()
            in_provenance = False
            continue
        if line.startswith('    ') and not line.startswith('      ') and stripped == 'provenance:':
            in_provenance = True
            continue
        if in_provenance and line.startswith('      ') and stripped.startswith('- '):
            out[current_name]['provenance'].append(stripped[2:].strip())
        elif line.startswith('    ') and not line.startswith('      ') and stripped:
            in_provenance = False
    return out


def _record_reference(qualtype: str, records: set[str]) -> tuple[str, int] | None:
    t = _clean_type(qualtype)
    pointer_depth = t.count('*')
    t = t.replace('*', ' ').strip()
    match = ARRAY_RE.match(t)
    if match:
        t = match.group('base').strip()
    if t.startswith('struct '):
        t = t[len('struct ') :]
    if t in records:
        return t, pointer_depth
    return None


def _record_reference_from_type(type_info: dict, records: set[str]) -> tuple[str, int] | None:
    for spelling in (type_info.get('qualtype', ''), type_info.get('canonical', '')):
        reference = _record_reference(spelling, records)
        if reference is not None:
            return reference
    return None


def _concrete_record_closure(api: dict, records_by_name: dict[str, dict]) -> set[str]:
    records = set(records_by_name)
    roots: set[str] = set()
    for function in api.get('functions', []):
        type_infos = [
            function.get('result', {'qualtype': 'void'}),
            *[param.get('type', {}) for param in function.get('parameters', [])],
        ]
        for type_info in type_infos:
            reference = _record_reference_from_type(type_info, records)
            if reference is not None:
                roots.add(reference[0])
    for typedef in _callback_typedefs(api).values():
        for spelling in [typedef['result'], *typedef['args']]:
            reference = _record_reference(spelling, records)
            if reference is not None:
                roots.add(reference[0])

    concrete: set[str] = set()

    def visit(name: str) -> None:
        record = records_by_name.get(name)
        if not record or record.get('opaque') or not record.get('fields') or name in concrete:
            return
        concrete.add(name)
        for field in record.get('fields', []):
            dependency = _record_dependency(field.get('type', {}), records)
            if dependency is not None:
                visit(dependency)

    for name in roots:
        visit(name)
    return concrete


def _validate_concrete_record_policy(
    api: dict,
    layoutable_records: set[str],
    concrete_record_policy: dict[str, dict],
) -> dict[str, str]:
    records_by_name = {
        record['name']: record for record in api.get('records', []) if record.get('name')
    }
    records = set(records_by_name)
    concrete = _concrete_record_closure(api, records_by_name)
    valid_dispositions = {'pointer-opaque', 'unsupported'}
    unknown = sorted(set(concrete_record_policy) - concrete)
    if unknown:
        raise ValueError(
            'concrete record policy names unused or non-concrete records: ' + ', '.join(unknown)
        )
    invalid = sorted(
        name
        for name, entry in concrete_record_policy.items()
        if entry.get('disposition') not in valid_dispositions
    )
    if invalid:
        raise ValueError('invalid concrete record disposition: ' + ', '.join(invalid))

    missing = sorted(concrete - layoutable_records - set(concrete_record_policy))
    if missing:
        raise ValueError('missing concrete record disposition: ' + ', '.join(missing))

    callback_typedefs = _callback_typedefs(api)
    for name, entry in concrete_record_policy.items():
        if entry.get('disposition') != 'pointer-opaque':
            continue
        provenance = set(entry.get('provenance', []))
        for function in api.get('functions', []):
            result_reference = _record_reference_from_type(
                function.get('result', {'qualtype': 'void'}), records
            )
            if result_reference and result_reference[0] == name and result_reference[1] > 0:
                if 'native-returned' not in provenance:
                    raise ValueError(
                        f'{name}: pointer result {function["name"]} lacks '
                        'native-returned provenance'
                    )
            for param in function.get('parameters', []):
                reference = _record_reference_from_type(param.get('type', {}), records)
                if reference and reference[0] == name and reference[1] > 0:
                    if 'native-owned-input' not in provenance:
                        raise ValueError(
                            f'{name}: pointer parameter '
                            f'{function["name"]}.{param.get("name", "?")} '
                            'lacks native-owned-input provenance'
                        )

    for callback_name, typedef in callback_typedefs.items():
        for spelling in [typedef['result'], *typedef['args']]:
            reference = _record_reference(spelling, records)
            if reference is None or reference[0] in layoutable_records:
                continue
            record_name, pointer_depth = reference
            record = records_by_name.get(record_name, {})
            if record.get('opaque') or not record.get('fields'):
                continue
            if pointer_depth == 0:
                raise ValueError(
                    f'{callback_name}: unavailable concrete record {record_name} '
                    'is passed by value'
                )
            provenance = set(concrete_record_policy.get(record_name, {}).get('provenance', []))
            expected = f'callback-borrowed:{callback_name}'
            if expected not in provenance:
                raise ValueError(
                    f'{record_name}: callback {callback_name} lacks explicit {expected} provenance'
                )

    dispositions = {}
    for name in sorted(concrete):
        entry = concrete_record_policy.get(name)
        dispositions[name] = entry.get('disposition') if entry else 'layout'
    return dispositions


def _layoutable_records(
    ordered_records: list[dict],
    records: set[str],
    enums: set[str],
    callbacks: set[str],
    forced_records: set[str] | None = None,
    blocked_records: set[str] | None = None,
) -> set[str]:
    out: set[str] = set()
    forced_records = forced_records or set()
    blocked_records = blocked_records or set()
    for record in ordered_records:
        name = record.get('name')
        if not name or record.get('opaque') or name in blocked_records:
            continue
        for field in record.get('fields', []):
            field_name = field.get('name')
            if not field_name:
                break
            if name not in forced_records and _unsupported_field_layout(field.get('type', {})):
                break
            dep = _record_dependency(field.get('type', {}), records)
            if dep and dep not in out:
                break
            ctype = _ctype_for_type(
                field.get('type', {}), records, enums, value_records=out, callbacks=callbacks
            )
            if ctype is None:
                break
        else:
            out.add(name)
    return out


def _class_name_for_pointer(qualtype: str, records: set[str]) -> str | None:
    t = _clean_type(qualtype)
    if not t.endswith('*'):
        return None
    target = t[:-1].strip()
    if target.startswith('struct '):
        target = target[len('struct ') :]
    if target.startswith('enum '):
        target = target[len('enum ') :]
    if target in records:
        return target
    return None


def _function_record_dependencies(
    function: dict,
    records_by_name: dict[str, dict],
    layoutable_records: set[str],
    required_alignments: dict[str, int],
    concrete_record_policy: dict[str, dict],
    callback_typedefs: dict[str, dict],
) -> tuple[list[str], str | None]:
    records = set(records_by_name)
    conditional_records = set(required_alignments)
    runtime_dependencies: set[str] = set()

    def visit_layout(name: str, root: str, visiting: set[str]) -> str | None:
        if name in visiting:
            return None
        visiting.add(name)
        entry = concrete_record_policy.get(name, {})
        disposition = entry.get('disposition')
        if disposition == 'unsupported':
            if name == root:
                return f'requires unsupported concrete record {name}'
            return f'requires unsupported concrete record {name} through {root}'
        if disposition == 'pointer-opaque' or name not in layoutable_records:
            if name == root:
                return f'requires unavailable concrete layout {name}'
            return f'requires unavailable concrete layout {name} through {root}'
        if name in conditional_records:
            runtime_dependencies.add(name)
        record = records_by_name.get(name, {})
        for field in record.get('fields', []):
            dependency = _record_dependency(field.get('type', {}), records)
            if dependency is None:
                continue
            diagnostic = visit_layout(dependency, root, visiting)
            if diagnostic is not None:
                return diagnostic
        visiting.remove(name)
        return None

    def inspect_reference(reference: tuple[str, int] | None) -> str | None:
        if reference is None:
            return None
        name, pointer_depth = reference
        record = records_by_name.get(name, {})
        if record.get('opaque') or not record.get('fields'):
            return None
        disposition = concrete_record_policy.get(name, {}).get('disposition')
        if disposition == 'pointer-opaque' and pointer_depth > 0:
            return None
        return visit_layout(name, name, set())

    result_reference = _record_reference_from_type(
        function.get('result', {'qualtype': 'void'}), records
    )
    diagnostic = inspect_reference(result_reference)
    if diagnostic is not None:
        return [], diagnostic

    for param in function.get('parameters', []):
        type_info = param.get('type', {})
        diagnostic = inspect_reference(_record_reference_from_type(type_info, records))
        if diagnostic is not None:
            return [], diagnostic
        callback = callback_typedefs.get(_clean_type(type_info.get('qualtype', '')))
        if callback is None:
            continue
        for spelling in [callback['result'], *callback['args']]:
            reference = _record_reference(spelling, records)
            if reference is None:
                continue
            name, pointer_depth = reference
            disposition = concrete_record_policy.get(name, {}).get('disposition')
            provenance = set(concrete_record_policy.get(name, {}).get('provenance', []))
            if pointer_depth > 0 and f'callback-borrowed:{callback["name"]}' in provenance:
                continue
            if disposition == 'pointer-opaque' and pointer_depth > 0:
                continue
            diagnostic = inspect_reference(reference)
            if diagnostic is not None:
                return [], diagnostic

    return sorted(runtime_dependencies), None


def _ctype_for(
    qualtype: str,
    records: set[str],
    enums: set[str],
    value_records: set[str] | None = None,
    callbacks: set[str] | None = None,
) -> str | None:
    t = _clean_type(qualtype)
    if callbacks is not None and t in callbacks:
        return t
    ctype = _array_ctype(t, records, enums, value_records=value_records, callbacks=callbacks)
    if ctype is not None:
        return ctype
    ctype = _pointer_ctype(t, records, enums)
    if ctype is not None:
        return ctype
    if t in CTYPE_MAP:
        return CTYPE_MAP[t]
    if t in SYNTHETIC_RECORD_CLASSES:
        return t
    if t in enums:
        return 'ctypes.c_int'
    if t.startswith('enum '):
        return 'ctypes.c_int'
    if t in records:
        return t if value_records is None or t in value_records else None
    cls = _class_name_for_pointer(t, records)
    if cls:
        return f'ctypes.POINTER({cls})'
    return None


def generate(
    api: dict,
    *,
    forced_layout_records: set[str] | None = None,
    required_alignments: dict[str, int] | None = None,
    concrete_record_policy: dict[str, dict] | None = None,
    callback_policy: dict[str, str] | None = None,
    owned_string_returns: dict[str, str] | None = None,
) -> tuple[str, list[str]]:
    records = {record['name'] for record in api.get('records', []) if record.get('name')}
    enums = {enum['name'] for enum in api.get('enums', []) if enum.get('name')}
    callback_typedefs = _callback_typedefs(api)
    callbacks = set(callback_typedefs)
    callback_policy = callback_policy or {}
    owned_string_returns = owned_string_returns or {}
    required_alignments = required_alignments or {}
    concrete_record_policy = concrete_record_policy or {}
    forced_layout_records = forced_layout_records or set()
    lines = [HEADER]

    for enum in api.get('enums', []):
        name = enum.get('name')
        if not name:
            continue
        lines.append(f'class {name}(CtypesEnum):\n')
        values = [value for value in enum.get('values', []) if value.get('name')]
        if values:
            for value in values:
                lines.append(f"    {value['name']} = {value.get('value', 0)}\n")
        else:
            lines.append('    pass\n')
        lines.append('\n\n')
        for value in values:
            value_name = value['name']
            lines.append(f'{value_name} = {name}.{value_name}\n')
        if values:
            lines.append('\n\n')

    ordered_records = _ordered_records(api, records)
    blocked_records = set(concrete_record_policy)
    layoutable_records = _layoutable_records(
        ordered_records,
        records,
        enums,
        callbacks,
        forced_records=forced_layout_records,
        blocked_records=blocked_records,
    )
    concrete_record_dispositions = _validate_concrete_record_policy(
        api, layoutable_records, concrete_record_policy
    )
    for name in required_alignments:
        if concrete_record_dispositions.get(name) == 'layout':
            concrete_record_dispositions[name] = 'conditional-layout'

    for record in ordered_records:
        name = record.get('name')
        if not name:
            continue
        base = 'Union' if record.get('kind') == 'union' else 'Structure'
        lines.append(f'class {name}(ctypes.{base}):\n')
        lines.append('    pass\n\n\n')
    for name, base in SYNTHETIC_RECORD_CLASSES.items():
        lines.append(f'class {name}(ctypes.{base}):\n')
        lines.append('    pass\n\n\n')

    for name in sorted(callback_typedefs):
        typedef = callback_typedefs[name]
        result = _ctype_for(
            typedef['result'], records, enums, value_records=layoutable_records, callbacks=callbacks
        )
        if result is None:
            continue
        argtypes = []
        for arg in typedef['args']:
            ctype = _ctype_for(
                arg, records, enums, value_records=layoutable_records, callbacks=callbacks
            )
            if ctype is None:
                break
            argtypes.append(ctype)
        else:
            lines.append(f'{name} = ctypes.CFUNCTYPE({", ".join([result, *argtypes])})\n\n\n')

    for typedef in api.get('typedefs', []):
        name = typedef.get('name')
        if name not in SCALAR_TYPEDEF_ALIASES:
            continue
        ctype = _ctype_for_type(
            typedef.get('type', {}),
            records,
            enums,
            value_records=layoutable_records,
            callbacks=callbacks,
        )
        if ctype is not None:
            lines.append(f'{name} = {ctype}\n\n\n')

    layout_records = []
    conditional_layout_records = []
    deferred_layout_records = []

    def conditional_field_dependencies(name: str, visiting: set[str] | None = None) -> set[str]:
        visiting = visiting or set()
        if name in visiting:
            return set()
        visiting.add(name)
        dependencies = set()
        record = next(
            (item for item in ordered_records if item.get('name') == name),
            {},
        )
        for field in record.get('fields', []):
            dependency = _record_dependency(field.get('type', {}), records)
            if dependency is None:
                continue
            if dependency in required_alignments:
                dependencies.add(dependency)
            dependencies.update(conditional_field_dependencies(dependency, visiting))
        visiting.remove(name)
        return dependencies

    for record in ordered_records:
        name = record.get('name')
        if not name or record.get('opaque'):
            continue
        if name not in layoutable_records:
            continue
        if name == 'DvzInputEvent':
            deferred_layout_records.append(record)
            continue
        fields = []
        for field in record.get('fields', []):
            field_name = field.get('name')
            if not field_name:
                break
            ctype = _ctype_for_type(
                field.get('type', {}),
                records,
                enums,
                value_records=layoutable_records,
                callbacks=callbacks,
            )
            if ctype is None:
                break
            fields.append((field_name, ctype, field.get('offset'), field.get('size')))
        else:
            if name in forced_layout_records and record.get('kind') != 'union':
                padded_fields = []
                current_end = 0
                padding_index = 0
                for field_name, ctype, offset, field_size in fields:
                    if not isinstance(offset, int) or not isinstance(field_size, int):
                        padded_fields = fields
                        break
                    if offset < current_end:
                        padded_fields = fields
                        break
                    if offset > current_end:
                        padded_fields.append(
                            (
                                f'_ctypes_padding_{padding_index}',
                                f'(ctypes.c_uint8 * {offset - current_end})',
                                current_end,
                                offset - current_end,
                            )
                        )
                        padding_index += 1
                    padded_fields.append((field_name, ctype, offset, field_size))
                    current_end = offset + field_size
                record_size = record.get('size')
                if (
                    padded_fields is not fields
                    and isinstance(record_size, int)
                    and record_size > current_end
                ):
                    padded_fields.append(
                        (
                            f'_ctypes_padding_{padding_index}',
                            f'(ctypes.c_uint8 * {record_size - current_end})',
                            current_end,
                            record_size - current_end,
                        )
                    )
                fields = padded_fields
            alignment = required_alignments.get(name)
            nested_conditional = sorted(conditional_field_dependencies(name) - {name})
            condition_parts = []
            if alignment is not None:
                condition_parts.append(f'_ctypes_alignment_is_effective({alignment})')
            condition_parts.extend(
                f"'{dependency}' in _DATOVIZ_CTYPES_LAYOUT_RECORDS"
                for dependency in nested_conditional
            )
            conditional = bool(condition_parts)
            if conditional:
                lines.append(f"if {' and '.join(condition_parts)}:\n")
            if alignment is not None:
                lines.append(f'    {name}._align_ = {alignment}\n')
                lines.append(f'    {name}._fields_ = [\n')
            elif conditional:
                lines.append(f'    {name}._fields_ = [\n')
            else:
                lines.append(f'{name}._fields_ = [\n')
            for field_name, ctype, _offset, _field_size in fields:
                indent = '        ' if conditional else '    '
                lines.append(f"{indent}('{field_name}', {ctype}),\n")
            if conditional:
                lines.append('    ]\n')
                checks = [f'ctypes.sizeof({name}) > 0']
                if alignment is not None:
                    checks.append(f'ctypes.alignment({name}) == {alignment}')
                lines.append(f"    if {' and '.join(checks)}:\n")
                lines.append(f"        _DATOVIZ_CTYPES_LAYOUT_RECORDS.append('{name}')\n")
                lines.append('    else:\n')
                if alignment is not None:
                    lines.append(
                        f"        _UNSUPPORTED_LAYOUT_RECORDS['{name}'] = "
                        f"'ctypes did not produce the requested {alignment}-byte alignment'\n"
                    )
                else:
                    lines.append(
                        f"        _UNSUPPORTED_LAYOUT_RECORDS['{name}'] = "
                        "'ctypes did not produce a nonzero nested record layout'\n"
                    )
                lines.append('else:\n')
                requirements = []
                if alignment is not None:
                    requirements.append(f'effective {alignment}-byte structure alignment')
                if nested_conditional:
                    requirements.append(
                        'available nested layout(s): ' + ', '.join(nested_conditional)
                    )
                lines.append(
                    f"    _UNSUPPORTED_LAYOUT_RECORDS['{name}'] = "
                    f"{('requires ' + ' and '.join(requirements))!r}\n"
                )
                lines.append('\n\n')
                conditional_layout_records.append(name)
            else:
                lines.append(']\n\n\n')
                layout_records.append(name)

    for name, fields in SYNTHETIC_RECORD_FIELDS.items():
        lines.append(f'{name}._fields_ = [\n')
        for field_name, ctype in fields:
            lines.append(f"    ('{field_name}', {ctype}),\n")
        lines.append(']\n\n\n')

    for record in deferred_layout_records:
        name = record.get('name')
        fields = []
        for field in record.get('fields', []):
            field_name = field.get('name')
            if not field_name:
                break
            ctype = _ctype_for_type(
                field.get('type', {}),
                records,
                enums,
                value_records=layoutable_records,
                callbacks=callbacks,
            )
            if ctype is None:
                break
            fields.append((field_name, ctype))
        else:
            lines.append(f'{name}._fields_ = [\n')
            for field_name, ctype in fields:
                lines.append(f"    ('{field_name}', {ctype}),\n")
            lines.append(']\n\n\n')
            layout_records.append(name)

    skipped = []
    emitted = []
    function_layout_dependencies = {}
    policy_unsupported_functions = {}
    records_by_name = {
        record['name']: record for record in api.get('records', []) if record.get('name')
    }
    for function in api.get('functions', []):
        name = function['name']
        dependencies, unsupported_diagnostic = _function_record_dependencies(
            function,
            records_by_name,
            layoutable_records,
            required_alignments,
            concrete_record_policy,
            callback_typedefs,
        )
        if unsupported_diagnostic is not None:
            policy_unsupported_functions[name] = unsupported_diagnostic
            continue
        if dependencies:
            function_layout_dependencies[name] = dependencies
        result = _ctype_for_type(
            function.get('result', {'qualtype': 'void'}),
            records,
            enums,
            value_records=layoutable_records,
            callbacks=callbacks,
        )
        argtypes = []
        callback_param_indices = []
        for param in function.get('parameters', []):
            ctype = _ctype_for_type(
                param.get('type', {}),
                records,
                enums,
                value_records=layoutable_records,
                callbacks=callbacks,
            )
            if ctype is None:
                break
            if ctype in callbacks:
                callback_param_indices.append(len(argtypes))
            argtypes.append(ctype)
        else:
            if result is None:
                skipped.append(name)
                continue
            if name in owned_string_returns and result == 'ctypes.c_char_p':
                result = 'ctypes.c_void_p'
            lines.append('try:\n')
            raw_name = f'_{name}' if callback_param_indices or name == 'dvz_input_unsubscribe' else name
            lines.append(f'    {raw_name} = dvz.{name}\n')
            lines.append('except AttributeError:\n')
            lines.append(f"    _MISSING_FUNCTIONS.append('{name}')\n")
            lines.append('else:\n')
            if function.get('doc'):
                doc = function['doc'].replace('"""', "'''")
                lines.append(f'    {raw_name}.__doc__ = """{doc}"""\n')
            lines.append(f'    {raw_name}.argtypes = [{", ".join(argtypes)}]\n')
            lines.append(f'    {raw_name}.restype = {result}\n')
            if callback_param_indices:
                callback_idx = callback_param_indices[0]
                callback_type = argtypes[callback_idx]
                param_names = [param.get('name') or f'arg{i}' for i, param in enumerate(function.get('parameters', []))]
                signature = ', '.join(param_names)
                call_args = ', '.join(param_names)
                callback_name = param_names[callback_idx]
                owner_name = param_names[0] if callback_idx > 0 and param_names else 'None'
                user_data_name = (
                    param_names[callback_idx + 1]
                    if callback_idx + 1 < len(param_names)
                    else 'None'
                )
                lines.append(f'    def {name}({signature}):\n')
                callback_kind = callback_policy.get(name)
                if callback_kind == 'unsubscribe' or (
                    callback_kind is None and name.startswith('dvz_input_unsubscribe')
                ):
                    lines.append(
                        f'        {callback_name} = _callback_pop_subscription'
                        f'({callback_type}, {owner_name}, {callback_name}, {user_data_name})\n'
                    )
                elif callback_kind == 'subscription' or (
                    callback_kind is None and name.startswith('dvz_input_subscribe')
                ):
                    if name.startswith('dvz_input_subscribe'):
                        lines.append(
                            f'        {callback_name} = '
                            f'_callback_coerce({callback_type}, {callback_name})\n'
                        )
                        lines.append(
                            f'        subscription_id = {raw_name}({call_args})\n'
                        )
                        lines.append(
                            f'        return _callback_store_subscription_id'
                            f'({owner_name}, subscription_id, {callback_name})\n'
                        )
                        lines.append(f'    {name}.__doc__ = {raw_name}.__doc__\n')
                        lines.append(f'    {name}.argtypes = {raw_name}.argtypes\n')
                        lines.append(f'    {name}.restype = {raw_name}.restype\n')
                        lines.append('\n\n')
                        emitted.append(name)
                        continue
                    else:
                        lines.append(
                            f'        {callback_name} = _callback_store_subscription'
                            f'({callback_type}, {owner_name}, {callback_name}, {user_data_name})\n'
                        )
                elif callback_kind == 'setter' or (callback_kind is None and '_set_' in name):
                    lines.append(
                        f"        {callback_name} = _callback_store_setter('{name}', "
                        f'{callback_type}, {owner_name}, {callback_name})\n'
                    )
                elif callback_kind == 'global' or (
                    callback_kind is None and len(param_names) == 1
                ):
                    lines.append(
                        f"        {callback_name} = _callback_store_global('{name}', "
                        f'{callback_type}, {callback_name})\n'
                    )
                else:
                    lines.append(
                        f'        {callback_name} = _callback_store_subscription'
                        f'({callback_type}, {owner_name}, {callback_name}, {user_data_name})\n'
                    )
                lines.append(f'        return {raw_name}({call_args})\n')
                lines.append(f'    {name}.__doc__ = {raw_name}.__doc__\n')
                lines.append(f'    {name}.argtypes = {raw_name}.argtypes\n')
                lines.append(f'    {name}.restype = {raw_name}.restype\n')
            elif name == 'dvz_input_unsubscribe':
                param_names = [
                    param.get('name') or f'arg{i}'
                    for i, param in enumerate(function.get('parameters', []))
                ]
                signature = ', '.join(param_names)
                call_args = ', '.join(param_names)
                owner_name = param_names[0] if param_names else 'None'
                subscription_id_name = param_names[1] if len(param_names) > 1 else '0'
                lines.append(f'    def {name}({signature}):\n')
                lines.append(f'        ok = {raw_name}({call_args})\n')
                lines.append('        if ok:\n')
                lines.append(
                    f'            _callback_pop_subscription_id({owner_name}, {subscription_id_name})\n'
                )
                lines.append('        return ok\n')
                lines.append(f'    {name}.__doc__ = {raw_name}.__doc__\n')
                lines.append(f'    {name}.argtypes = {raw_name}.argtypes\n')
                lines.append(f'    {name}.restype = {raw_name}.restype\n')
            lines.append('\n\n')
            emitted.append(name)
            continue
        skipped.append(name)

    lines.append(
        f'_DATOVIZ_CTYPES_LAYOUT_RECORDS[:0] = {layout_records!r}\n'
    )
    lines.append(f'_POLICY_UNSUPPORTED_FUNCTIONS = {policy_unsupported_functions!r}\n')
    lines.append('_UNSUPPORTED_FUNCTIONS.update(_POLICY_UNSUPPORTED_FUNCTIONS)\n')
    lines.append(f'_FUNCTION_LAYOUT_DEPENDENCIES = {function_layout_dependencies!r}\n')
    lines.append(
        'for _function_name, _required_records in _FUNCTION_LAYOUT_DEPENDENCIES.items():\n'
    )
    lines.append(
        '    _missing_records = [name for name in _required_records '
        'if name not in _DATOVIZ_CTYPES_LAYOUT_RECORDS]\n'
    )
    lines.append('    if _missing_records:\n')
    lines.append('        globals().pop(_function_name, None)\n')
    lines.append('        globals().pop(f"_{_function_name}", None)\n')
    lines.append(
        '        _UNSUPPORTED_FUNCTIONS[_function_name] = '
        '"requires unavailable ABI-exact concrete record layout(s): " '
        '+ ", ".join(_missing_records)\n'
    )
    if function_layout_dependencies:
        lines.append('del _function_name, _required_records, _missing_records\n')
    lines.append(f'_GENERATED_FUNCTION_COUNT = {len(emitted)}\n')
    lines.append(f'_SKIPPED_FUNCTIONS = {skipped!r}\n')
    lines.append(
        f'_DATOVIZ_CTYPES_DECLARED_LAYOUT_RECORDS = '
        f'{sorted(set(layout_records) | set(conditional_layout_records))!r}\n'
    )
    lines.append(
        f'_CONCRETE_RECORD_DISPOSITIONS = {concrete_record_dispositions!r}\n'
    )
    lines.append(f'_CONCRETE_RECORD_POLICY = {concrete_record_policy!r}\n')
    lines.append("__all__ = [name for name in globals() if name.startswith(('dvz_', 'Dvz', 'DVZ_'))]\n")
    return ''.join(lines), skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, default=DEFAULT_INPUT)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--policy', type=Path, default=DEFAULT_POLICY)
    parser.add_argument('--check', action='store_true', help='fail if the generated file is stale')
    args = parser.parse_args()

    with args.input.open(encoding='utf8') as f:
        api = json.load(f)
    text, skipped = generate(
        api,
        forced_layout_records=_layout_records_from_policy(args.policy),
        required_alignments=_required_alignments_from_policy(args.policy),
        concrete_record_policy=_concrete_record_policy_from_policy(args.policy),
        callback_policy=_callback_policy_from_policy(args.policy),
        owned_string_returns=_owned_string_returns_from_policy(args.policy),
    )

    if args.check:
        current = args.output.read_text() if args.output.exists() else ''
        if current != text:
            raise SystemExit(f'{args.output} is stale; run `just ctypes`')
        print(f'{args.output} is up to date ({len(skipped)} skipped functions)')
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding='utf8')
    print(f'wrote {args.output} ({len(skipped)} skipped functions)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
