/*
* Copyright (c) 2021 Cyrille Rossant and contributors. All rights reserved.
* Licensed under the MIT license. See LICENSE file in the project root for details.
* SPDX-License-Identifier: MIT
*/

#version 450

#define WORKGROUP_SIZE 32

// NOTE: the number of items could be passed via a push constant or uniform buffer, or even
// as the first element of the storage buffer.
#define ITEM_COUNT 20

layout (local_size_x=WORKGROUP_SIZE, local_size_y=1, local_size_z=1) in;

layout(push_constant) uniform push {
    float power;
} u_push;

layout(binding = 0) buffer buf {
   float number[];
};

void main() {
    if(gl_GlobalInvocationID.x >= ITEM_COUNT)
        return;
    number[gl_GlobalInvocationID.x] = pow(number[gl_GlobalInvocationID.x], u_push.power);
}
