#!/usr/bin/env python3
"""Normalize generated example-data bundles to the shared manifest schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from common import EXAMPLES_ROOT, SCHEMA, artifact, command_argv, write_manifest, write_provenance


SKIP_NAMES = {"manifest.json", "PROVENANCE.md", "BLOCKERS.md", "provenance.json"}


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf8"))
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def _has_schema_manifest(root: Path) -> bool:
    manifest = _load_json(root / "manifest.json")
    return manifest.get("schema") == SCHEMA


def _format_for(path: Path) -> str:
    name = path.name.lower()
    if name.endswith(".npy.gz"):
        return "npy.gz"
    if name.endswith(".npz"):
        return "npz"
    if name.endswith(".npy"):
        return "npy"
    if name.endswith(".bin"):
        return "binary"
    if name.endswith(".csv"):
        return "csv"
    if name.endswith(".json") or name.endswith(".geojson"):
        return "json"
    if name.endswith(".ig"):
        return "cms-ig"
    if name.endswith(".hea"):
        return "physionet-header"
    if name.endswith(".png"):
        return "png"
    return path.suffix.lstrip(".") or "file"


def _role_for(path: Path) -> str:
    stem = path.name.lower()
    if stem == "metadata.json":
        return "metadata"
    if "position" in stem or "pos" in stem or "nodes" in stem:
        return "position"
    if "color" in stem or "rgba" in stem:
        return "color"
    if "label" in stem:
        return "label"
    if "track" in stem:
        return "track"
    if "event" in stem or "aftershock" in stem:
        return "event"
    if "volume" in stem:
        return "volume"
    if "data" in stem:
        return "bundle"
    return "artifact"


def _artifact_entries(root: Path) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.name in SKIP_NAMES:
            continue
        entries.append(artifact(path, root, _role_for(path), _format_for(path)))
    return entries


def _title_from_id(example_id: str) -> str:
    return example_id.replace("/", " / ").replace("_", " ").title()


def _source_from_metadata(metadata: dict[str, Any], provenance: dict[str, Any]) -> dict[str, Any]:
    source: dict[str, Any] = {
        "name": metadata.get("source")
        or provenance.get("source")
        or provenance.get("method")
        or metadata.get("name")
        or "Generated Datoviz example data",
    }
    for key in (
        "source_url",
        "source_urls",
        "source_file_url",
        "source_record_url",
        "source_api_url",
        "license",
        "license_note",
        "record",
        "dataset",
        "kind",
        "seed",
    ):
        if key in metadata:
            source[key] = metadata[key]
        elif key in provenance:
            source[key] = provenance[key]
    return source


def _validation_from_metadata(metadata: dict[str, Any], old_manifest: dict[str, Any]) -> dict[str, Any]:
    validation: dict[str, Any] = {}
    for key in (
        "point_count",
        "event_count",
        "label_count",
        "track_count",
        "frame_count",
        "shape_zyx",
        "image_shape_yx",
        "arrays",
    ):
        if key in metadata:
            validation[key] = metadata[key]
        elif key in old_manifest:
            validation[key] = old_manifest[key]
    return validation


def _normalize_root(root: Path) -> bool:
    if _has_schema_manifest(root):
        if not (root / "PROVENANCE.md").exists():
            write_provenance(
                root,
                title=_title_from_id(root.relative_to(EXAMPLES_ROOT).as_posix()),
                source_lines=["Existing schema manifest; provenance note generated by normalizer."],
                processing_lines=["No binary artifacts were modified."],
            )
        return False

    artifacts = _artifact_entries(root)
    if not artifacts:
        return False

    rel_id = root.relative_to(EXAMPLES_ROOT).as_posix()
    metadata = _load_json(root / "metadata.json")
    old_manifest = _load_json(root / "manifest.json")
    provenance = _load_json(root / "provenance.json")
    source = _source_from_metadata(metadata or old_manifest, provenance)
    validation = _validation_from_metadata(metadata, old_manifest)

    write_manifest(
        root,
        example_id=rel_id,
        title=_title_from_id(rel_id),
        status="committed" if "external_public" not in rel_id else "external-public",
        script="tools/data/normalize_manifests.py",
        command=command_argv("tools/data/normalize_manifests.py"),
        source=source,
        artifacts=artifacts,
        validation=validation,
        extra={"normalized_from": "metadata-or-legacy-manifest"},
    )
    write_provenance(
        root,
        title=_title_from_id(rel_id),
        source_lines=[
            str(source.get("name", "Generated Datoviz example data")),
            "See manifest.json for source fields, artifact hashes, and validation metadata.",
        ],
        processing_lines=[
            "Bundle metadata was normalized to datoviz.example-data.v1.",
            "Binary artifacts were not modified by the normalizer.",
        ],
        license_lines=[
            str(source.get("license") or source.get("license_note") or "See source documentation.")
        ],
    )
    return True


def _candidate_roots(base: Path) -> list[Path]:
    roots: set[Path] = set()
    for path in base.rglob("*"):
        if not path.is_file():
            continue
        if "prepared" in path.relative_to(base).parts:
            continue
        if path.name in {"metadata.json", "manifest.json", "provenance.json"}:
            roots.add(path.parent)
        elif path.suffix.lower() in {".npz", ".npy", ".bin", ".csv", ".geojson", ".ig", ".hea"}:
            roots.add(path.parent)
    return sorted(roots)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("roots", nargs="*", type=Path, help="bundle roots; default scans data/examples")
    args = parser.parse_args()

    roots = args.roots or _candidate_roots(EXAMPLES_ROOT)
    changed = 0
    for root in roots:
        if _normalize_root(root):
            changed += 1
    print(f"normalized {changed} bundle(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
