#!/usr/bin/env python3
"""Check mechanically verifiable properties of handwritten documentation snippets."""

from __future__ import annotations

import ast
import re
import sys
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HOWTO = ROOT / "docs" / "how-to"
START = ROOT / "docs" / "start"
REFERENCE = ROOT / "docs" / "reference"
TUTORIALS = ROOT / "docs" / "tutorials"
GENERATED_WARNING = "<!-- WARNING: generated by tools/build_api_c.py"
PYTHON_BINDING_FILES = (
    ROOT / "datoviz" / "_ctypes.py",
    ROOT / "datoviz" / "_array_facade.py",
)
PYTHON_PACKAGE = ROOT / "datoviz" / "__init__.py"
PYTHON_PUBLIC_PREFIXES = ("dvz_", "Dvz", "DVZ_")
FENCE_RE = re.compile(
    r"^(?P<indent>[ \t]*)```([^\n]*)\n(.*?)^(?P=indent)```", re.MULTILINE | re.DOTALL
)


def _assigned_names(tree: ast.Module) -> tuple[set[str], set[str]]:
    """Return module-scope bindings and literal ``__all__`` exports without importing code."""
    names: set[str] = set()
    exports: set[str] = set()

    def target_names(target: ast.expr) -> None:
        if isinstance(target, ast.Name):
            names.add(target.id)
        elif isinstance(target, (ast.Tuple, ast.List)):
            for item in target.elts:
                target_names(item)

    def statements(items: list[ast.stmt]) -> None:
        for node in items:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                names.add(node.name)
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                for alias in node.names:
                    names.add(alias.asname or alias.name.split(".")[0])
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    target_names(target)
                has_literal_exports = any(
                    isinstance(target, ast.Name) and target.id == "__all__"
                    for target in node.targets
                )
                if has_literal_exports:
                    if isinstance(node.value, (ast.List, ast.Tuple, ast.Set)):
                        exports.update(
                            item.value
                            for item in node.value.elts
                            if isinstance(item, ast.Constant) and isinstance(item.value, str)
                        )
            elif isinstance(node, ast.AnnAssign):
                target_names(node.target)
            elif isinstance(node, (ast.If, ast.For, ast.AsyncFor, ast.While)):
                statements(node.body)
                statements(node.orelse)
            elif isinstance(node, (ast.With, ast.AsyncWith)):
                statements(node.body)
            elif isinstance(node, ast.Try):
                statements(node.body)
                for handler in node.handlers:
                    statements(handler.body)
                statements(node.orelse)
                statements(node.finalbody)
            elif isinstance(node, ast.Match):
                for case in node.cases:
                    statements(case.body)

    statements(tree.body)
    return names, exports


def _python_public_symbols() -> set[str]:
    """Build the top-level Python facade inventory without loading the native library."""
    public: set[str] = set()
    for path in PYTHON_BINDING_FILES:
        tree = ast.parse(path.read_text(), filename=str(path))
        names, _ = _assigned_names(tree)
        public.update(name for name in names if name.startswith(PYTHON_PUBLIC_PREFIXES))

    package_tree = ast.parse(PYTHON_PACKAGE.read_text(), filename=str(PYTHON_PACKAGE))
    _, managed_exports = _assigned_names(package_tree)
    public.update(managed_exports)
    return public


def _python_dvz_attributes(tree: ast.AST) -> list[tuple[str, int]]:
    """Return ``dvz.<name>`` attributes and source lines from one parsed snippet."""
    return sorted(
        {
            (node.attr, node.lineno)
            for node in ast.walk(tree)
            if isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Name)
            and node.value.id == "dvz"
        },
        key=lambda item: (item[1], item[0]),
    )


def _public_identifiers() -> tuple[dict[str, int], set[str], set[str]]:
    text = "\n".join(path.read_text(errors="replace") for path in (ROOT / "include").rglob("*.h"))
    declarations = re.sub(r"/\*.*?\*/|//[^\n]*", "", text, flags=re.DOTALL)
    functions: dict[str, int] = {}
    for match in re.finditer(r"\b(dvz_[A-Za-z0-9_]+)\s*\((.*?)\)\s*;", declarations, re.DOTALL):
        args = match.group(2).strip()
        functions[match.group(1)] = 0 if args in ("", "void") else len(args.split(","))
    types = set(re.findall(r"\b(Dvz[A-Za-z0-9_]+)\b", text))
    constants = set(re.findall(r"\b(DVZ_[A-Z0-9_]+)\b", text))
    return functions, types, constants


def _calls(code: str):
    """Yield public-looking calls and their top-level argument counts."""
    for match in re.finditer(r"\b(dvz_[A-Za-z0-9_]+)\s*\(", code):
        start = match.end()
        depth = 1
        quote = None
        for index in range(start, len(code)):
            char = code[index]
            if quote is not None:
                if char == quote and code[index - 1] != "\\":
                    quote = None
            elif char in "\"'":
                quote = char
            elif char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    body = code[start:index]
                    arg_depth = 0
                    arg_quote = None
                    count = 0 if not body.strip() else 1
                    for offset, item in enumerate(body):
                        if arg_quote is not None:
                            if item == arg_quote and (offset == 0 or body[offset - 1] != "\\"):
                                arg_quote = None
                        elif item in "\"'":
                            arg_quote = item
                        elif item in "([{":
                            arg_depth += 1
                        elif item in ")]}":
                            arg_depth -= 1
                        elif item == "," and arg_depth == 0:
                            count += 1
                    yield match.group(1), count
                    break


def main() -> int:
    functions, types, constants = _public_identifiers()
    python_public = _python_public_symbols()
    errors: list[str] = []
    counts = {"documents": 0, "python": 0, "python_symbols": 0, "c": 0, "includes": 0}

    reference_documents = [
        path
        for path in sorted(REFERENCE.rglob("*.md"))
        if GENERATED_WARNING not in path.read_text(errors="replace")
    ]
    documents = (
        [ROOT / "docs/index.md", ROOT / "docs/ai-agents.md"]
        + sorted(HOWTO.glob("*.md"))
        + sorted(START.glob("*.md"))
        + sorted(TUTORIALS.rglob("*.md"))
        + reference_documents
    )
    for path in documents:
        counts["documents"] += 1
        text = path.read_text()
        for match in FENCE_RE.finditer(text):
            language = match.group(2).strip()
            code = textwrap.dedent(match.group(3))
            line = text.count("\n", 0, match.start(3)) + 1
            include = re.fullmatch(r'\s*--8<--\s+"([^\"]+)"\s*', code)
            if include is not None:
                include_path = ROOT / include.group(1)
                if not include_path.is_file():
                    errors.append(
                        f"{path.relative_to(ROOT)}:{line}: missing snippet include {include.group(1)}"
                    )
                    continue
                code = include_path.read_text()
                counts["includes"] += 1
            if language == "python":
                counts["python"] += 1
                try:
                    tree = ast.parse(code, filename=f"{path}:{line}")
                except SyntaxError as exc:
                    errors.append(f"{path.relative_to(ROOT)}:{line + (exc.lineno or 1) - 1}: {exc.msg}")
                    continue
                for name, relative_line in _python_dvz_attributes(tree):
                    counts["python_symbols"] += 1
                    if name not in python_public:
                        errors.append(
                            f"{path.relative_to(ROOT)}:{line + relative_line - 1}: "
                            f"unknown top-level Python symbol dvz.{name}"
                        )
            elif language == "c":
                counts["c"] += 1
                checks = (
                    (r"\b(dvz_[A-Za-z0-9_]+)\s*\(", set(functions), "function"),
                    (r"\b(Dvz[A-Za-z0-9_]+)\b", types, "type"),
                    (r"\b(DVZ_[A-Z0-9_]+)\b", constants, "constant"),
                )
                for pattern, public, kind in checks:
                    for token in sorted(set(re.findall(pattern, code)) - public):
                        errors.append(
                            f"{path.relative_to(ROOT)}:{line}: non-public or unknown C {kind} {token}"
                        )
                for name, count in _calls(code):
                    if name in functions and count != functions[name]:
                        errors.append(
                            f"{path.relative_to(ROOT)}:{line}: {name} takes {functions[name]} "
                            f"arguments in the public header, snippet passes {count}"
                        )

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print(
        f"Authored public docs: {counts['documents']} pages, {counts['python']} Python AST blocks "
        f"with {counts['python_symbols']} verified dvz.* symbols, "
        f"and {counts['c']} C public "
        f"identifier/arity blocks passed, including {counts['includes']} resolved source includes "
        "(generated C API modules are delegated to docs-api-check; context excerpts are not compiled)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
