#!/usr/bin/env python3
"""Check that DRP2 runtime command metadata is the only implemented packet authority."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENUM_PATH = ROOT / "include" / "datoviz" / "drp2" / "enums.h"
METADATA_PATH = ROOT / "src" / "drp2" / "command_metadata.c"
COMMANDS_PATH = ROOT / "spec" / "drp2" / "COMMANDS.md"
SCHEMA_ROOT_PATH = ROOT / "spec" / "drp2" / "schema" / "drp_command.json"
JS_METADATA_PATH = ROOT / "web" / "drp2" / "command_metadata.js"


def _fail(message: str) -> int:
    print(f"ERROR: {message}", file=sys.stderr)
    return 1


def _enum_commands() -> list[str]:
    text = ENUM_PATH.read_text(encoding="utf-8")
    match = re.search(
        r"typedef enum\s*\{(?P<body>.*?)\}\s*DvzDrp2CommandType;", text, re.S
    )
    if match is None:
        raise RuntimeError(f"could not find DvzDrp2CommandType in {ENUM_PATH}")
    return re.findall(r"\bDVZ_DRP2_COMMAND_[A-Z0-9_]+\b", match.group("body"))


def _metadata_entries() -> list[dict[str, str]]:
    text = METADATA_PATH.read_text(encoding="utf-8")
    table_match = re.search(
        r"static const DvzDrp2CommandMetadata _command_metadata"
        r"\[DVZ_DRP2_COMMAND_METADATA_COUNT\]\s*=\s*\{(?P<table>.*?)\};",
        text,
        re.S,
    )
    if table_match is None:
        raise RuntimeError(f"could not find _command_metadata table in {METADATA_PATH}")
    table = table_match.group("table")
    entries: list[dict[str, str]] = []
    for match in re.finditer(
        r"\[(DVZ_DRP2_COMMAND_[A-Z0-9_]+)\]\s*=\s*\{(?P<body>.*?)\}",
        table,
        re.S,
    ):
        body = match.group("body")
        name_match = re.search(r'"([^"]+)"', body)
        kind_match = re.search(r"\bDVZ_DRP2_PACKET_[A-Z_]+\b", body)
        type_match = re.search(r"\bDVZ_DRP2_COMMAND_[A-Z0-9_]+\b", body)
        if name_match is None or kind_match is None or type_match is None:
            raise RuntimeError(f"incomplete metadata entry for {match.group(1)}")
        entries.append(
            {
                "designator": match.group(1),
                "type": type_match.group(0),
                "name": name_match.group(1),
                "kind": kind_match.group(0),
            }
        )
    return entries


def _schema_commands() -> list[str]:
    root = json.loads(SCHEMA_ROOT_PATH.read_text(encoding="utf-8"))
    commands = []
    for entry in root.get("oneOf", []):
        ref = entry.get("$ref", "")
        if not ref.startswith("./commands/") or not ref.endswith(".json"):
            raise RuntimeError(f"unexpected DRP2 command schema ref: {ref!r}")
        commands.append(Path(ref).stem)
    return commands


def _prose_commands() -> list[str]:
    text = COMMANDS_PATH.read_text(encoding="utf-8")
    match = re.search(
        r"## Active Command Surface(?P<body>.*?)## Deferred And Non-Authoritative Commands",
        text,
        re.S,
    )
    if match is None:
        raise RuntimeError(f"could not find active command surface in {COMMANDS_PATH}")
    return re.findall(r"`([A-Za-z0-9]+)`", match.group("body"))


def _generated_js(names: list[str]) -> str:
    lines = [
        "// Generated by tools/check_drp2_command_metadata.py.",
        "// Source of truth: src/drp2/command_metadata.c, validated against spec/drp2.",
        "",
        "export const COMMAND_NAMES = [",
    ]
    lines.extend(f'  "{name}",' for name in names)
    lines.extend(["];", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write-js",
        action="store_true",
        help="rewrite the generated JS command-name metadata module",
    )
    args = parser.parse_args(argv)

    enum_commands = _enum_commands()
    entries = _metadata_entries()
    metadata_by_type = {entry["designator"]: entry for entry in entries}
    schema_commands = _schema_commands()
    prose_commands = _prose_commands()

    if len(metadata_by_type) != len(entries):
        return _fail("duplicate DRP2 command metadata designators")

    if set(schema_commands) != set(prose_commands):
        missing_schema = sorted(set(prose_commands) - set(schema_commands))
        extra_schema = sorted(set(schema_commands) - set(prose_commands))
        return _fail(
            "schema/prose active command mismatch: "
            f"missing_schema={missing_schema}, extra_schema={extra_schema}"
        )

    missing_metadata = [name for name in enum_commands if name not in metadata_by_type]
    if missing_metadata:
        return _fail(f"DvzDrp2CommandType values missing metadata: {missing_metadata}")

    for entry in entries:
        if entry["designator"] != entry["type"]:
            return _fail(
                f"metadata designator/type mismatch: {entry['designator']} != {entry['type']}"
            )
        if entry["designator"] == "DVZ_DRP2_COMMAND_NONE":
            if entry["name"] != "None" or entry["kind"] != "DVZ_DRP2_PACKET_NONE":
                return _fail("DVZ_DRP2_COMMAND_NONE metadata must use name None and packet NONE")
            continue
        if entry["name"] not in schema_commands:
            return _fail(f"runtime command {entry['name']} is not in the active schema root")
        if entry["kind"] == "DVZ_DRP2_PACKET_NONE":
            return _fail(f"runtime command {entry['name']} has packet kind NONE")

    names = [metadata_by_type[name]["name"] for name in enum_commands]
    generated_js = _generated_js(names)
    if args.write_js:
        JS_METADATA_PATH.write_text(generated_js, encoding="utf-8")
    else:
        current_js = JS_METADATA_PATH.read_text(encoding="utf-8")
        if current_js != generated_js:
            return _fail(
                f"{JS_METADATA_PATH.relative_to(ROOT)} is stale; "
                "run tools/check_drp2_command_metadata.py --write-js"
            )

    duplicate_names = sorted({name for name in names if names.count(name) > 1 and name != "None"})
    if duplicate_names:
        return _fail(f"duplicate runtime command names: {duplicate_names}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
