#!/usr/bin/env python3
"""Validate local links and explicit anchors in the generated C API reference."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs/reference/c-api"
GENERATED_MARKER = "generated by tools/build_api_c.py"
LINK_RE = re.compile(r"\[[^]]*\]\(([^)]+)\)")
ANCHOR_RE = re.compile(r"\{[^}\n]*#([A-Za-z0-9_-]+)[^}\n]*\}")
HTML_ANCHOR_RE = re.compile(r'<a\s+id="([A-Za-z0-9_-]+)"\s*></a>')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", type=Path, default=DOCS_DIR)
    return parser.parse_args()


def anchors(path: Path) -> set[str]:
    text = path.read_text(encoding="utf8")
    return set(ANCHOR_RE.findall(text)) | set(HTML_ANCHOR_RE.findall(text))


def validate(docs_dir: Path) -> list[str]:
    pages = sorted(docs_dir.glob("*.md"))
    anchor_cache = {path.resolve(): anchors(path) for path in pages}
    errors = []
    for source in pages:
        text = source.read_text(encoding="utf8")
        if GENERATED_MARKER not in text:
            continue
        for raw_target in LINK_RE.findall(text):
            if raw_target.startswith(("http://", "https://", "mailto:")):
                continue
            relative, separator, fragment = raw_target.partition("#")
            target = (source.parent / relative).resolve() if relative else source.resolve()
            if relative and not target.exists():
                errors.append(f"{source.name}: missing target {raw_target}")
                continue
            if separator and fragment:
                if target not in anchor_cache:
                    if not target.exists():
                        continue
                    anchor_cache[target] = anchors(target)
                if fragment not in anchor_cache[target]:
                    errors.append(f"{source.name}: missing anchor {raw_target}")
    return errors


def main() -> int:
    errors = validate(parse_args().docs_dir)
    if errors:
        print("Invalid generated C API links:")
        for error in errors:
            print(f"  {error}")
        return 1
    print("Generated C API links and anchors OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
