#!/usr/bin/env python3
"""Check mechanically verifiable properties of handwritten documentation snippets."""

from __future__ import annotations

import ast
import re
import sys
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HOWTO = ROOT / "docs" / "how-to"
START = ROOT / "docs" / "start"
REFERENCE = ROOT / "docs" / "reference"
GENERATED_WARNING = "<!-- WARNING: generated by tools/build_api_c.py"
FENCE_RE = re.compile(
    r"^(?P<indent>[ \t]*)```([^\n]*)\n(.*?)^(?P=indent)```", re.MULTILINE | re.DOTALL
)


def _public_identifiers() -> tuple[dict[str, int], set[str], set[str]]:
    text = "\n".join(path.read_text(errors="replace") for path in (ROOT / "include").rglob("*.h"))
    declarations = re.sub(r"/\*.*?\*/|//[^\n]*", "", text, flags=re.DOTALL)
    functions: dict[str, int] = {}
    for match in re.finditer(r"\b(dvz_[A-Za-z0-9_]+)\s*\((.*?)\)\s*;", declarations, re.DOTALL):
        args = match.group(2).strip()
        functions[match.group(1)] = 0 if args in ("", "void") else len(args.split(","))
    types = set(re.findall(r"\b(Dvz[A-Za-z0-9_]+)\b", text))
    constants = set(re.findall(r"\b(DVZ_[A-Z0-9_]+)\b", text))
    return functions, types, constants


def _calls(code: str):
    """Yield public-looking calls and their top-level argument counts."""
    for match in re.finditer(r"\b(dvz_[A-Za-z0-9_]+)\s*\(", code):
        start = match.end()
        depth = 1
        quote = None
        for index in range(start, len(code)):
            char = code[index]
            if quote is not None:
                if char == quote and code[index - 1] != "\\":
                    quote = None
            elif char in "\"'":
                quote = char
            elif char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    body = code[start:index]
                    arg_depth = 0
                    arg_quote = None
                    count = 0 if not body.strip() else 1
                    for offset, item in enumerate(body):
                        if arg_quote is not None:
                            if item == arg_quote and (offset == 0 or body[offset - 1] != "\\"):
                                arg_quote = None
                        elif item in "\"'":
                            arg_quote = item
                        elif item in "([{":
                            arg_depth += 1
                        elif item in ")]}":
                            arg_depth -= 1
                        elif item == "," and arg_depth == 0:
                            count += 1
                    yield match.group(1), count
                    break


def main() -> int:
    functions, types, constants = _public_identifiers()
    errors: list[str] = []
    counts = {"documents": 0, "python": 0, "c": 0, "includes": 0}

    reference_documents = [
        path
        for path in sorted(REFERENCE.rglob("*.md"))
        if GENERATED_WARNING not in path.read_text(errors="replace")
    ]
    documents = (
        [ROOT / "docs/index.md", ROOT / "docs/ai-agents.md"]
        + sorted(HOWTO.glob("*.md"))
        + sorted(START.glob("*.md"))
        + reference_documents
    )
    for path in documents:
        counts["documents"] += 1
        text = path.read_text()
        for match in FENCE_RE.finditer(text):
            language = match.group(2).strip()
            code = textwrap.dedent(match.group(3))
            line = text.count("\n", 0, match.start(3)) + 1
            include = re.fullmatch(r'\s*--8<--\s+"([^\"]+)"\s*', code)
            if include is not None:
                include_path = ROOT / include.group(1)
                if not include_path.is_file():
                    errors.append(
                        f"{path.relative_to(ROOT)}:{line}: missing snippet include {include.group(1)}"
                    )
                    continue
                code = include_path.read_text()
                counts["includes"] += 1
            if language == "python":
                counts["python"] += 1
                try:
                    ast.parse(code, filename=f"{path}:{line}")
                except SyntaxError as exc:
                    errors.append(f"{path.relative_to(ROOT)}:{line + (exc.lineno or 1) - 1}: {exc.msg}")
            elif language == "c":
                counts["c"] += 1
                checks = (
                    (r"\b(dvz_[A-Za-z0-9_]+)\s*\(", set(functions), "function"),
                    (r"\b(Dvz[A-Za-z0-9_]+)\b", types, "type"),
                    (r"\b(DVZ_[A-Z0-9_]+)\b", constants, "constant"),
                )
                for pattern, public, kind in checks:
                    for token in sorted(set(re.findall(pattern, code)) - public):
                        errors.append(
                            f"{path.relative_to(ROOT)}:{line}: non-public or unknown C {kind} {token}"
                        )
                for name, count in _calls(code):
                    if name in functions and count != functions[name]:
                        errors.append(
                            f"{path.relative_to(ROOT)}:{line}: {name} takes {functions[name]} "
                            f"arguments in the public header, snippet passes {count}"
                        )

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print(
        f"Authored public docs: {counts['documents']} pages, {counts['python']} Python AST blocks, "
        f"and {counts['c']} C public "
        f"identifier/arity blocks passed, including {counts['includes']} resolved source includes "
        "(generated C API modules are delegated to docs-api-check; context excerpts are not compiled)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
