#!/usr/bin/env python3
"""Utility that converts a SPIR-V binary into a C header with const data."""

import argparse
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description="Export SPIR-V blob as C data.")
    parser.add_argument("--input", "-i", required=True, help="Source SPIR-V binary.")
    parser.add_argument("--output", "-o", required=True, help="Generated C header path.")
    parser.add_argument(
        "--symbol",
        "-s",
        required=True,
        help="Symbol name for the exported SPIR-V array (dots and dashes become underscores).",
    )
    return parser.parse_args()


def format_data(words):
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        yield "    " + ", ".join(f"0x{value:08x}" for value in chunk) + ","


def main():
    args = parse_args()
    input_path = Path(args.input)
    data = input_path.read_bytes()

    if len(data) % 4 != 0:
        raise SystemExit(f"SPIR-V size must be a multiple of 4: {len(data)}")

    words = [
        int.from_bytes(data[i : i + 4], "little")
        for i in range(0, len(data), 4)
    ]

    header_path = Path(args.output)
    header_path.parent.mkdir(parents=True, exist_ok=True)

    normalized_symbol = args.symbol.replace(".", "_").replace("-", "_")

    with header_path.open("w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/spirv_to_c.py — do not edit manually.\n")
        handle.write("#pragma once\n\n")
        handle.write("#include <stddef.h>\n")
        handle.write("#include <stdint.h>\n\n")
        handle.write(f"static const uint32_t {normalized_symbol}[] = {{\n")
        if words:
            handle.write("\n".join(format_data(words)))
            handle.write("\n")
        handle.write("};\n\n")
        handle.write(
            f"static const size_t {normalized_symbol}_size = sizeof({normalized_symbol});\n"
        )


if __name__ == "__main__":
    main()
