name: RELEASE

on:
  workflow_dispatch:

jobs:
  get-run-id:
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.get_run_id.outputs.run_id }}
    steps:
      - name: run-id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get_run_id
        run: |
          run_id=$(gh api -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/actions/workflows/wheels.yml/runs \
              -q '.workflow_runs[] | select(.conclusion == "success") | .id' | head -n 1)
          echo "run_id=$run_id" >> $GITHUB_ENV  # Set environment variable for use in next steps

  release:
    needs: get-run-id
    runs-on: ubuntu-latest
    steps:
      - name: run-id
        run: echo ${{ needs.get-run-id.outputs.run-id }}

      - name: Download
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.get-run-id.outputs.run-id }}
          path: ./dist

      - name: List
        run: ls -l ./dist

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./dist/**/*.whl
