name: RELEASE

on:
  workflow_dispatch:

jobs:
  get-run-id:
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.get_run_id.outputs.run_id }}
    steps:
      - name: gh
        if: env.USING_ACT == 1
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
          sudo apt-add-repository -y "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
          sudo apt update
          sudo apt install gh -y

      - name: run-id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get_run_id
        run: |
          run_id=$(gh run list -R datoviz/datoviz --workflow=WHEELS --json conclusion,databaseId \
          --jq '.[] | select(.conclusion == "success") | .databaseId' | head -n 1)
          echo $run_id
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

  release:
    needs: get-run-id
    runs-on: ubuntu-latest
    steps:
      - name: run-id
        run: echo ${{ needs.get-run-id.outputs.run-id }}

      - name: Download
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ needs.get-run-id.outputs.run-id }}

      - name: List
        run: ls -l

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./**/*.whl
