name: Test

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

env:
  DVZ_LOG_LEVEL: 2
  USING_ACT: 0  # will be 1 when using "just act", skip repo cloning to use local instead

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rossant/datoviz_build

    steps:
    - name: Checkout Datoviz repository
      if: env.USING_ACT == 'false'
      uses: actions/checkout@v3

    - name: Build Datoviz
      if: env.USING_ACT == 'false'
      run: just build || just build

      # WARNING: disabling the MIT-SHM X extension is crucial as it avoid random X crashes that
      # make the tests fail.
    - name: Run tests with Xvfb
      run:
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24 -extension MIT-SHM" ./build/datoviz test
