name: Build and test datoviz on Linux

on:
  workflow_dispatch:
  push:
    branches:
      - "v0.2x"

env:
  DVZ_LOG_LEVEL: 0

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install -y build-essential cmake gcc ccache ninja-build xorg-dev clang-format libtinyxml2-dev libfreetype-dev xvfb
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash

    - name: Add just to PATH
      run: echo "$HOME/bin" >> $GITHUB_PATH

    # - name: Setup Vulkan
    #   run: |
    #     sudo mkdir -p /usr/local/lib/
    #     sudo cp -P libs/vulkan/libvulkan.so* /usr/local/lib/
    #     echo "/usr/local/lib/" | sudo tee /etc/ld.so.conf.d/vulkan.conf
    #     sudo ldconfig

    - name: Install SwiftShader
      run: |
        # Copy the swiftshader library from the data submodule to the main tree.
        cp ./data/swiftshader/linux/libvk_swiftshader.so libs/swiftshader/

    - name: Start Xvfb
      run: |
        Xvfb :1 -screen 0 1024x768x24 &
        export DISPLAY=:1

    - name: Build the library
      run: |
        just build || true
        just build

    - name: Run tests
      run: |
        VK_ICD_FILENAMES=libs/swiftshader/vk_swiftshader_icd.json DISPLAY=:1 just test
