name: "TEST on Linux"

# Trigger on push and PR on main
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DVZ_LOG_LEVEL: 2  # 1 for DEBUG and 0 for TRACE
  USING_ACT: 0  # will be 1 when using "just act", skip repo cloning to use local instead

jobs:
  test:
    runs-on: ubuntu-latest

    # Use a pre-built Docker image with all build and run dependencies.
    container:
      image: rossant/datoviz_build

    # Clone the repo (except if local with "act")
    steps:
    - name: Checkout Datoviz repository
      if: env.USING_ACT == 0
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Build the library (except if local with "act")
    - name: Build Datoviz
      if: env.USING_ACT == 0
      run: just build || just build

      # WARNING: disabling the MIT-SHM X extension is crucial as it avoid random X crashes that
      # make the tests fail.
    - name: Run tests with Xvfb
      run:
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24 -extension MIT-SHM" ./build/datoviz test
