name: "TEST"

# Trigger on push and PR on main
on:
  workflow_dispatch: # enable manual workflow trigger from the GitHub website
  push:
    # branches:
    #   - main
  pull_request:
    branches:
      - main

env:
  DVZ_LOG_LEVEL: 2  # 1 for DEBUG and 0 for TRACE
  USING_ACT: 0  # will be 1 when using "just act", skip repo cloning to use local instead

jobs:

  # -----------------------------------------------------------------------------------------------
  # Linux
  # -----------------------------------------------------------------------------------------------

  test-linux:
    if: ${{ false }}
    runs-on: ubuntu-latest

    # Use a pre-built Docker image with all build and run dependencies.
    container:
      image: rossant/datoviz_ubuntu

    # Clone the repo (except if local with "act")
    steps:
    - name: Checkout
      if: env.USING_ACT == 0
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Build the library (except if local with "act")
    - name: Build
      if: env.USING_ACT == 0
      run: just build || just build

      # WARNING: disabling the MIT-SHM X extension is crucial as it avoid random X crashes that
      # make the tests fail.
    - name: Test
      run:
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24 -extension MIT-SHM" ./build/datoviz test

  # -----------------------------------------------------------------------------------------------
  # macOS
  # -----------------------------------------------------------------------------------------------

  test-macos:
    if: ${{ false }}
    runs-on: macos-latest

    # Clone the repo (except if local with "act")
    steps:
    - name: Checkout
      if: env.USING_ACT == 0
      uses: actions/checkout@v4
      with:
        submodules: recursive


    # Cache Homebrew dependencies
    - name: Cache Homebrew
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/Homebrew/Library/Homebrew
          /usr/local/Cellar
          /usr/local/var/homebrew/linked
        key: ${{ runner.os }}-brew-${{ hashFiles('~/.Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-brew-

    # Install Homebrew dependencies
    - name: Homebrew Dependencies
      run: |
        brew update
        brew bundle dump --force --file ~/.Brewfile || true
        brew install just ccache ninja clang-format tree cloc

    # Cache pip dependencies
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install pip dependencies
    - name: Python dependencies
      run: pip install -r requirements-dev.txt


    # HACK: the compilation fails because the compiler uses the Mono freetype which
    # does not work for some reason. So here we just brutally remove the Mono framework
    # that we don't need for building.
    - name: FreeType fixes
      run: |
        sudo rm -rf /Library/Frameworks/Mono.framework
        export CPATH=$(brew --prefix freetype)/include/freetype2:$CPATH
        export LIBRARY_PATH=$(brew --prefix freetype)/lib:$LIBRARY_PATH
        export PKG_CONFIG_PATH=$(brew --prefix freetype)/lib/pkgconfig:$PKG_CONFIG_PATH

    # Build the library (except if local with "act")
    - name: Build
      if: env.USING_ACT == 0
      run: just build || just build

    # Run the tests
    - name: Test
      run:
        ./build/datoviz test

  # -----------------------------------------------------------------------------------------------
  # Windows
  # -----------------------------------------------------------------------------------------------

  test-windows:
    runs-on: windows-latest

    # NOTE: Windows Docker images are not yet supported on GitHub Actions
    # see https://github.com/docker/build-push-action/issues/18
    # In the meantime we just replicate the Dockerfile steps here.

    # Use a pre-built Docker image with all build and run dependencies.
    # container:
    #   image: rossant/datoviz_windows

    env:
      VCPKG_ROOT: C:/vcpkg
      VULKAN_SDK: C:/VulkanSDK/1.3.280.0/

    steps:

    # Cache
    # C:/mingw64
    - name: Cache
      if: env.USING_ACT == 0
      uses: actions/cache@v4
      with:
        path: |
          C:/ProgramData/chocolatey
          C:/vcpkg
          C:/VulkanSDK
        key: ${{ runner.os }}-build-2
        restore-keys: |
          ${{ runner.os }}-build

    # Chocolatey
    - name: Chocolatey
      run: |
        if (!(Test-Path "C:\ProgramData\chocolatey")) {
          choco install git -y --params "/GitAndUnixToolsOnPath"
          choco install 7zip python just mingw cmake ccache ninja tree cloc -y
        }

    # vcpkg
    - name: vcpkg
      run: |
        if (!(Test-Path "C:\vcpkg")) {
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          powershell.exe -NoProfile -ExecutionPolicy Bypass C:\vcpkg\scripts\bootstrap.ps1
        }

    # Vulkan SDK
    - name: Vulkan SDK
      run: |
        if (!(Test-Path "C:\VulkanSDK")) {
          curl -LO https://sdk.lunarg.com/sdk/download/1.3.280.0/windows/vulkan-sdk.exe
          .\vulkan-sdk.exe --accept-licenses --default-answer --confirm-command install
        }

    # Checkout
    - name: Checkout
      if: env.USING_ACT == 0
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Decompress Swiftshader DLL (compressed on the git data submodule to bypass the 100M file size limit)
    - name: Decompress Swiftshader
      run: |
        if (!(Test-Path -Path "data/swiftshader/windows/vk_swiftshader.dll")) {
          7z x data/swiftshader/windows/vk_swiftshader.dll.zip -odata/swiftshader/windows
        }

    # Cache Python
    - name: Cache Python
      uses: actions/cache@v4
      with:
        path: |
          c:/hostedtoolcache/windows/python/3.9.13/x64/lib/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip

    # Python
    - name: Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    # Build
    - name: Build
      run: |
        just build || just build

    # Test
    - name: Test
      run: |
        just swiftshader just test
